"""Collect the per-figure .status.json sidecars into MANIFEST.md."""
import glob
import json
import os
import time
from pathlib import Path

OUT = os.path.dirname(os.path.abspath(__file__))
REPO = Path(__file__).resolve().parents[2]
WORK_ROOT = Path(os.environ.get('WORK_ROOT') or REPO / 'samples' / '_work')
ARCHIVE = WORK_ROOT / 'runs_system-malloc_archive_2026-08-11.tar.gz'

HEAD = """# f2dace-artifact look-alike figures -- manifest

Generated by `make_manifest.py` from the `*.status.json` sidecars each plotting
script writes. Regenerate everything with:

```
cd {out}
RUNS="<runs dir> [<runs dir> ...]"
PY="${{PYTHON:-python3}}"
$PY plot_cloudsc_fig.py        --runs-dir $RUNS      # FIG A: fig_cloudsc_bar / _violin
$PY plot_velocity_fig.py       --runs-dir $RUNS      # FIG B: fig_velocity_bar / _violin
$PY plot_cloudsc_efficiency.py --runs-dir $RUNS      # FIG C: fig_cloudsc_eff
$PY plot_gpu_weakscaling.py    --runs-dir $RUNS      # FIG D: fig_gpu_weakscaling
$PY make_manifest.py
```

All four scripts are data driven against the run CSV schema
`kernel,mode,<sizeA>,<sizeB>,threads,rep,ms,inputs,lane[,alloc]` (the `alloc`
column is optional, `--alloc` selects one allocator when several are present).
Series that are not in the CSVs are dropped from the figure and listed under
MISSING -- they are never filled in with invented numbers.

Last built: {when}

"""


def main():
    rows = []
    for path in sorted(glob.glob(os.path.join(OUT, '*.status.json'))):
        with open(path) as fh:
            rows.append(json.load(fh))

    body = [HEAD.format(out=OUT, when=time.strftime('%Y-%m-%d %H:%M:%S'))]
    body.append('## Figures\n')
    for r in rows:
        name = r['figure']
        body.append(f'### `{name}.pdf` / `{name}.png`\n')
        for key in ('rows', 'panels', 'lanes', 'problem_sizes', 'grids'):
            if key in r and r[key]:
                body.append(f'- {key}: `{r[key]}`')
        body.append('')

    body.append(f"""## Lane -> colour / legend map (`f2dace_style.py`)

Set1, artifact assignment: red = DaCe, blue = the Fortran OpenMP/OpenACC
baseline, green = the C rewrite.

| lane | colour | legend text |
|---|---|---|
| `dace-gcc` | Set1 red | Original Code ▶ DaCe ▶ G++ w. OpenMP |
| `dace-llvm` | Set1 purple | Original Code ▶ DaCe ▶ Clang++ w. OpenMP |
| `dace-gpu` | Set1 red | Original Code ▶ DaCe ▶ nvcc w. CUDA |
| `original-openmp` | Set1 blue | Original Code ▶ GFortran w. OpenMP |
| `openacc-gpu` | Set1 blue | Original Code ▶ NVHPC w. OpenACC |
| `c-openmp` | Set1 green | C Rewrite ▶ G++ w. OpenMP |
| `cuda-ref` | Set1 green | C Rewrite ▶ nvcc w. CUDA |
| `gfortran-autopar` | Set1 orange | Original Code ▶ GFortran w. -ftree-parallelize-loops |
| `openacc-cpu` | Set1 brown | Original Code ▶ NVHPC w. OpenACC (multicore) |
| `flang-serial` | Set1 yellow | Original Code ▶ Flang (serial) |
| `gfortran-serial` | Set1 pink | Original Code ▶ GFortran (serial) |

`c-openmp` (dwarf C rewrite, g++ OpenMP) is wired for the harness lane that is
being added; it takes the artifact's green C-rewrite slot, so `gfortran-autopar`
moved off green to orange and now carries the flag it actually uses in its
label.  Both are inactive until such rows appear in the CSVs.  The velocity
figure takes any number of grids: `inputs` is upper-cased to `R02B0x`, relabelled
via the artifact's grid->km map (`R02B05` = 80 km, `R02B06` = 40 km) and sorted,
so r02b06 rows simply add a second x group.  Verified on synthetic rows in
scratch; no synthetic data was used for any delivered figure.

## Data provenance

The run CSVs under `$WORK_ROOT/{{meas,dev}}/runs/` were removed while these
figures were being built, so every figure currently on disk was rendered from
the archived pre-mimalloc runs in
`{ARCHIVE}`
(extracted to scratch, allocator column absent -> reported as `unspecified`).
Each figure carries that path in its footer.  Re-run the four scripts with
`--runs-dir` pointing at the new mimalloc runs to replace them; do not compare
the two allocator generations in one plot.

## Earlier-brief figures (superseded, kept for reference)

- `cloudsc_cpu.*`, `velocity_cpu.*`, `cloudsc_cpu_threads.*`, `velocity_cpu_threads.*`
  and the fast-math pair -- DELETED along with the scripts that made them
  (`plot_cloudsc_cpu.py`, `plot_velocity_cpu.py`, `plot_cloudsc_fastmath.py`).
  The first two were superseded by `fig_cloudsc_bar` / `fig_velocity_bar`; the
  thread sweeps existed only because a single size/grid left no other
  non-degenerate x axis, which the size sweep has since fixed; fast-math was
  never measured.  All three also kept private lane colour/label dicts, so
  deleting them is what stops the shared palette drifting again.
  NOTE: nothing else plots x = OpenMP threads for velocity.
- `compare_cloudsc.png`, `compare_velocity.png` -- artifact reference figure
  stacked above ours for the fidelity check (`make_side_by_side.py`).
- `reference/ref_cloudsc.png`, `reference/ref_icon_velocity.png` -- the
  reference images extracted from the artifact notebooks' stored outputs.
""")

    allmissing = []
    for r in rows:
        for m in r.get('missing', []):
            if m not in allmissing:
                allmissing.append(m)
    body.append('## MISSING (not measured, therefore not plotted)\n')
    body += [f'- {m}' for m in allmissing] or ['- (nothing missing)']
    body.append('')

    with open(os.path.join(OUT, 'MANIFEST.md'), 'w') as fh:
        fh.write('\n'.join(body))
    print('wrote', os.path.join(OUT, 'MANIFEST.md'))


if __name__ == '__main__':
    main()
