! GENERATED by tools/gen_acc_mirror.py from include/velocity_tendencies_no_nproma.h.
! Do not edit by hand -- rerun the generator after regenerating the C++ header.
MODULE velocity_acc_mirror
  USE iso_c_binding, ONLY: c_int, c_double, c_ptr, c_size_t, c_sizeof
  IMPLICIT NONE
  PUBLIC

  !> Shape and Fortran lower bounds of one component, as recorded by the f2dace
  !> SA (size) / SOA (offset) extent fields.
  TYPE :: cm_meta
    INTEGER :: rank = 0
    INTEGER :: dims(4) = 1
    INTEGER :: lbs(4) = 1
  END TYPE cm_meta

  TYPE, BIND(C) :: cm_t_grid_edges
    INTEGER(c_int) :: f___f2dace_SA_area_edge_d_0_s_188
    INTEGER(c_int) :: f___f2dace_SA_area_edge_d_1_s_189
    INTEGER(c_int) :: f___f2dace_SA_cell_blk_d_0_s_167
    INTEGER(c_int) :: f___f2dace_SA_cell_blk_d_1_s_168
    INTEGER(c_int) :: f___f2dace_SA_cell_blk_d_2_s_169
    INTEGER(c_int) :: f___f2dace_SA_cell_idx_d_0_s_164
    INTEGER(c_int) :: f___f2dace_SA_cell_idx_d_1_s_165
    INTEGER(c_int) :: f___f2dace_SA_cell_idx_d_2_s_166
    INTEGER(c_int) :: f___f2dace_SA_end_block_d_0_s_199
    INTEGER(c_int) :: f___f2dace_SA_end_index_d_0_s_197
    INTEGER(c_int) :: f___f2dace_SA_f_e_d_0_s_190
    INTEGER(c_int) :: f___f2dace_SA_f_e_d_1_s_191
    INTEGER(c_int) :: f___f2dace_SA_fn_e_d_0_s_192
    INTEGER(c_int) :: f___f2dace_SA_fn_e_d_1_s_193
    INTEGER(c_int) :: f___f2dace_SA_ft_e_d_0_s_194
    INTEGER(c_int) :: f___f2dace_SA_ft_e_d_1_s_195
    INTEGER(c_int) :: f___f2dace_SA_inv_dual_edge_length_d_0_s_186
    INTEGER(c_int) :: f___f2dace_SA_inv_dual_edge_length_d_1_s_187
    INTEGER(c_int) :: f___f2dace_SA_inv_primal_edge_length_d_0_s_184
    INTEGER(c_int) :: f___f2dace_SA_inv_primal_edge_length_d_1_s_185
    INTEGER(c_int) :: f___f2dace_SA_quad_blk_d_0_s_181
    INTEGER(c_int) :: f___f2dace_SA_quad_blk_d_1_s_182
    INTEGER(c_int) :: f___f2dace_SA_quad_blk_d_2_s_183
    INTEGER(c_int) :: f___f2dace_SA_quad_idx_d_0_s_178
    INTEGER(c_int) :: f___f2dace_SA_quad_idx_d_1_s_179
    INTEGER(c_int) :: f___f2dace_SA_quad_idx_d_2_s_180
    INTEGER(c_int) :: f___f2dace_SA_start_block_d_0_s_198
    INTEGER(c_int) :: f___f2dace_SA_start_index_d_0_s_196
    INTEGER(c_int) :: f___f2dace_SA_tangent_orientation_d_0_s_176
    INTEGER(c_int) :: f___f2dace_SA_tangent_orientation_d_1_s_177
    INTEGER(c_int) :: f___f2dace_SA_vertex_blk_d_0_s_173
    INTEGER(c_int) :: f___f2dace_SA_vertex_blk_d_1_s_174
    INTEGER(c_int) :: f___f2dace_SA_vertex_blk_d_2_s_175
    INTEGER(c_int) :: f___f2dace_SA_vertex_idx_d_0_s_170
    INTEGER(c_int) :: f___f2dace_SA_vertex_idx_d_1_s_171
    INTEGER(c_int) :: f___f2dace_SA_vertex_idx_d_2_s_172
    INTEGER(c_int) :: f___f2dace_SOA_area_edge_d_0_s_188
    INTEGER(c_int) :: f___f2dace_SOA_area_edge_d_1_s_189
    INTEGER(c_int) :: f___f2dace_SOA_cell_blk_d_0_s_167
    INTEGER(c_int) :: f___f2dace_SOA_cell_blk_d_1_s_168
    INTEGER(c_int) :: f___f2dace_SOA_cell_blk_d_2_s_169
    INTEGER(c_int) :: f___f2dace_SOA_cell_idx_d_0_s_164
    INTEGER(c_int) :: f___f2dace_SOA_cell_idx_d_1_s_165
    INTEGER(c_int) :: f___f2dace_SOA_cell_idx_d_2_s_166
    INTEGER(c_int) :: f___f2dace_SOA_end_block_d_0_s_199
    INTEGER(c_int) :: f___f2dace_SOA_end_index_d_0_s_197
    INTEGER(c_int) :: f___f2dace_SOA_f_e_d_0_s_190
    INTEGER(c_int) :: f___f2dace_SOA_f_e_d_1_s_191
    INTEGER(c_int) :: f___f2dace_SOA_fn_e_d_0_s_192
    INTEGER(c_int) :: f___f2dace_SOA_fn_e_d_1_s_193
    INTEGER(c_int) :: f___f2dace_SOA_ft_e_d_0_s_194
    INTEGER(c_int) :: f___f2dace_SOA_ft_e_d_1_s_195
    INTEGER(c_int) :: f___f2dace_SOA_inv_dual_edge_length_d_0_s_186
    INTEGER(c_int) :: f___f2dace_SOA_inv_dual_edge_length_d_1_s_187
    INTEGER(c_int) :: f___f2dace_SOA_inv_primal_edge_length_d_0_s_184
    INTEGER(c_int) :: f___f2dace_SOA_inv_primal_edge_length_d_1_s_185
    INTEGER(c_int) :: f___f2dace_SOA_quad_blk_d_0_s_181
    INTEGER(c_int) :: f___f2dace_SOA_quad_blk_d_1_s_182
    INTEGER(c_int) :: f___f2dace_SOA_quad_blk_d_2_s_183
    INTEGER(c_int) :: f___f2dace_SOA_quad_idx_d_0_s_178
    INTEGER(c_int) :: f___f2dace_SOA_quad_idx_d_1_s_179
    INTEGER(c_int) :: f___f2dace_SOA_quad_idx_d_2_s_180
    INTEGER(c_int) :: f___f2dace_SOA_start_block_d_0_s_198
    INTEGER(c_int) :: f___f2dace_SOA_start_index_d_0_s_196
    INTEGER(c_int) :: f___f2dace_SOA_tangent_orientation_d_0_s_176
    INTEGER(c_int) :: f___f2dace_SOA_tangent_orientation_d_1_s_177
    INTEGER(c_int) :: f___f2dace_SOA_vertex_blk_d_0_s_173
    INTEGER(c_int) :: f___f2dace_SOA_vertex_blk_d_1_s_174
    INTEGER(c_int) :: f___f2dace_SOA_vertex_blk_d_2_s_175
    INTEGER(c_int) :: f___f2dace_SOA_vertex_idx_d_0_s_170
    INTEGER(c_int) :: f___f2dace_SOA_vertex_idx_d_1_s_171
    INTEGER(c_int) :: f___f2dace_SOA_vertex_idx_d_2_s_172
    TYPE(c_ptr) :: f_area_edge
    TYPE(c_ptr) :: f_cell_blk
    TYPE(c_ptr) :: f_cell_idx
    TYPE(c_ptr) :: f_end_block
    TYPE(c_ptr) :: f_end_index
    TYPE(c_ptr) :: f_f_e
    TYPE(c_ptr) :: f_fn_e
    TYPE(c_ptr) :: f_ft_e
    TYPE(c_ptr) :: f_inv_dual_edge_length
    TYPE(c_ptr) :: f_inv_primal_edge_length
    TYPE(c_ptr) :: f_quad_blk
    TYPE(c_ptr) :: f_quad_idx
    TYPE(c_ptr) :: f_start_block
    TYPE(c_ptr) :: f_start_index
    TYPE(c_ptr) :: f_tangent_orientation
    TYPE(c_ptr) :: f_vertex_blk
    TYPE(c_ptr) :: f_vertex_idx
  END TYPE cm_t_grid_edges

  TYPE, BIND(C) :: cm_t_int_state
    INTEGER(c_int) :: f___f2dace_SA_c_lin_e_d_0_s_25
    INTEGER(c_int) :: f___f2dace_SA_c_lin_e_d_1_s_26
    INTEGER(c_int) :: f___f2dace_SA_c_lin_e_d_2_s_27
    INTEGER(c_int) :: f___f2dace_SA_cells_aw_verts_d_0_s_31
    INTEGER(c_int) :: f___f2dace_SA_cells_aw_verts_d_1_s_32
    INTEGER(c_int) :: f___f2dace_SA_cells_aw_verts_d_2_s_33
    INTEGER(c_int) :: f___f2dace_SA_e_bln_c_s_d_0_s_28
    INTEGER(c_int) :: f___f2dace_SA_e_bln_c_s_d_1_s_29
    INTEGER(c_int) :: f___f2dace_SA_e_bln_c_s_d_2_s_30
    INTEGER(c_int) :: f___f2dace_SA_geofac_grdiv_d_0_s_37
    INTEGER(c_int) :: f___f2dace_SA_geofac_grdiv_d_1_s_38
    INTEGER(c_int) :: f___f2dace_SA_geofac_grdiv_d_2_s_39
    INTEGER(c_int) :: f___f2dace_SA_geofac_n2s_d_0_s_43
    INTEGER(c_int) :: f___f2dace_SA_geofac_n2s_d_1_s_44
    INTEGER(c_int) :: f___f2dace_SA_geofac_n2s_d_2_s_45
    INTEGER(c_int) :: f___f2dace_SA_geofac_rot_d_0_s_40
    INTEGER(c_int) :: f___f2dace_SA_geofac_rot_d_1_s_41
    INTEGER(c_int) :: f___f2dace_SA_geofac_rot_d_2_s_42
    INTEGER(c_int) :: f___f2dace_SA_rbf_vec_coeff_e_d_0_s_34
    INTEGER(c_int) :: f___f2dace_SA_rbf_vec_coeff_e_d_1_s_35
    INTEGER(c_int) :: f___f2dace_SA_rbf_vec_coeff_e_d_2_s_36
    INTEGER(c_int) :: f___f2dace_SOA_c_lin_e_d_0_s_25
    INTEGER(c_int) :: f___f2dace_SOA_c_lin_e_d_1_s_26
    INTEGER(c_int) :: f___f2dace_SOA_c_lin_e_d_2_s_27
    INTEGER(c_int) :: f___f2dace_SOA_cells_aw_verts_d_0_s_31
    INTEGER(c_int) :: f___f2dace_SOA_cells_aw_verts_d_1_s_32
    INTEGER(c_int) :: f___f2dace_SOA_cells_aw_verts_d_2_s_33
    INTEGER(c_int) :: f___f2dace_SOA_e_bln_c_s_d_0_s_28
    INTEGER(c_int) :: f___f2dace_SOA_e_bln_c_s_d_1_s_29
    INTEGER(c_int) :: f___f2dace_SOA_e_bln_c_s_d_2_s_30
    INTEGER(c_int) :: f___f2dace_SOA_geofac_grdiv_d_0_s_37
    INTEGER(c_int) :: f___f2dace_SOA_geofac_grdiv_d_1_s_38
    INTEGER(c_int) :: f___f2dace_SOA_geofac_grdiv_d_2_s_39
    INTEGER(c_int) :: f___f2dace_SOA_geofac_n2s_d_0_s_43
    INTEGER(c_int) :: f___f2dace_SOA_geofac_n2s_d_1_s_44
    INTEGER(c_int) :: f___f2dace_SOA_geofac_n2s_d_2_s_45
    INTEGER(c_int) :: f___f2dace_SOA_geofac_rot_d_0_s_40
    INTEGER(c_int) :: f___f2dace_SOA_geofac_rot_d_1_s_41
    INTEGER(c_int) :: f___f2dace_SOA_geofac_rot_d_2_s_42
    INTEGER(c_int) :: f___f2dace_SOA_rbf_vec_coeff_e_d_0_s_34
    INTEGER(c_int) :: f___f2dace_SOA_rbf_vec_coeff_e_d_1_s_35
    INTEGER(c_int) :: f___f2dace_SOA_rbf_vec_coeff_e_d_2_s_36
    TYPE(c_ptr) :: f_c_lin_e
    TYPE(c_ptr) :: f_cells_aw_verts
    TYPE(c_ptr) :: f_e_bln_c_s
    TYPE(c_ptr) :: f_geofac_grdiv
    TYPE(c_ptr) :: f_geofac_n2s
    TYPE(c_ptr) :: f_geofac_rot
    TYPE(c_ptr) :: f_rbf_vec_coeff_e
  END TYPE cm_t_int_state

  TYPE, BIND(C) :: cm_t_nh_prog
    INTEGER(c_int) :: f___f2dace_SA_vn_d_0_s_288
    INTEGER(c_int) :: f___f2dace_SA_vn_d_1_s_289
    INTEGER(c_int) :: f___f2dace_SA_vn_d_2_s_290
    INTEGER(c_int) :: f___f2dace_SA_w_d_0_s_285
    INTEGER(c_int) :: f___f2dace_SA_w_d_1_s_286
    INTEGER(c_int) :: f___f2dace_SA_w_d_2_s_287
    INTEGER(c_int) :: f___f2dace_SOA_vn_d_0_s_288
    INTEGER(c_int) :: f___f2dace_SOA_vn_d_1_s_289
    INTEGER(c_int) :: f___f2dace_SOA_vn_d_2_s_290
    INTEGER(c_int) :: f___f2dace_SOA_w_d_0_s_285
    INTEGER(c_int) :: f___f2dace_SOA_w_d_1_s_286
    INTEGER(c_int) :: f___f2dace_SOA_w_d_2_s_287
    TYPE(c_ptr) :: f_vn
    TYPE(c_ptr) :: f_w
  END TYPE cm_t_nh_prog

  TYPE, BIND(C) :: cm_global_data_type
    INTEGER(c_int) :: f_i_am_accel_node
    INTEGER(c_int) :: f_lextra_diffu
    TYPE(c_ptr) :: f_nflatlev
    INTEGER(c_int) :: f_nproma
    TYPE(c_ptr) :: f_nrdmax
    INTEGER(c_int) :: f_timer_intp
    INTEGER(c_int) :: f_timer_solve_nh_veltend
    INTEGER(c_int) :: f_timers_level
  END TYPE cm_global_data_type

  TYPE, BIND(C) :: cm_t_grid_domain_decomp_info
    INTEGER(c_int) :: f___f2dace_SA_owner_mask_d_0_s_2
    INTEGER(c_int) :: f___f2dace_SA_owner_mask_d_1_s_3
    INTEGER(c_int) :: f___f2dace_SOA_owner_mask_d_0_s_2
    INTEGER(c_int) :: f___f2dace_SOA_owner_mask_d_1_s_3
    TYPE(c_ptr) :: f_owner_mask
  END TYPE cm_t_grid_domain_decomp_info

  TYPE, BIND(C) :: cm_t_grid_cells
    INTEGER(c_int) :: f___f2dace_SA_area_d_0_s_158
    INTEGER(c_int) :: f___f2dace_SA_area_d_1_s_159
    INTEGER(c_int) :: f___f2dace_SA_edge_blk_d_0_s_155
    INTEGER(c_int) :: f___f2dace_SA_edge_blk_d_1_s_156
    INTEGER(c_int) :: f___f2dace_SA_edge_blk_d_2_s_157
    INTEGER(c_int) :: f___f2dace_SA_edge_idx_d_0_s_152
    INTEGER(c_int) :: f___f2dace_SA_edge_idx_d_1_s_153
    INTEGER(c_int) :: f___f2dace_SA_edge_idx_d_2_s_154
    INTEGER(c_int) :: f___f2dace_SA_end_block_d_0_s_163
    INTEGER(c_int) :: f___f2dace_SA_end_index_d_0_s_161
    INTEGER(c_int) :: f___f2dace_SA_neighbor_blk_d_0_s_149
    INTEGER(c_int) :: f___f2dace_SA_neighbor_blk_d_1_s_150
    INTEGER(c_int) :: f___f2dace_SA_neighbor_blk_d_2_s_151
    INTEGER(c_int) :: f___f2dace_SA_neighbor_idx_d_0_s_146
    INTEGER(c_int) :: f___f2dace_SA_neighbor_idx_d_1_s_147
    INTEGER(c_int) :: f___f2dace_SA_neighbor_idx_d_2_s_148
    INTEGER(c_int) :: f___f2dace_SA_start_block_d_0_s_162
    INTEGER(c_int) :: f___f2dace_SA_start_index_d_0_s_160
    INTEGER(c_int) :: f___f2dace_SOA_area_d_0_s_158
    INTEGER(c_int) :: f___f2dace_SOA_area_d_1_s_159
    INTEGER(c_int) :: f___f2dace_SOA_edge_blk_d_0_s_155
    INTEGER(c_int) :: f___f2dace_SOA_edge_blk_d_1_s_156
    INTEGER(c_int) :: f___f2dace_SOA_edge_blk_d_2_s_157
    INTEGER(c_int) :: f___f2dace_SOA_edge_idx_d_0_s_152
    INTEGER(c_int) :: f___f2dace_SOA_edge_idx_d_1_s_153
    INTEGER(c_int) :: f___f2dace_SOA_edge_idx_d_2_s_154
    INTEGER(c_int) :: f___f2dace_SOA_end_block_d_0_s_163
    INTEGER(c_int) :: f___f2dace_SOA_end_index_d_0_s_161
    INTEGER(c_int) :: f___f2dace_SOA_neighbor_blk_d_0_s_149
    INTEGER(c_int) :: f___f2dace_SOA_neighbor_blk_d_1_s_150
    INTEGER(c_int) :: f___f2dace_SOA_neighbor_blk_d_2_s_151
    INTEGER(c_int) :: f___f2dace_SOA_neighbor_idx_d_0_s_146
    INTEGER(c_int) :: f___f2dace_SOA_neighbor_idx_d_1_s_147
    INTEGER(c_int) :: f___f2dace_SOA_neighbor_idx_d_2_s_148
    INTEGER(c_int) :: f___f2dace_SOA_start_block_d_0_s_162
    INTEGER(c_int) :: f___f2dace_SOA_start_index_d_0_s_160
    TYPE(c_ptr) :: f_area
    TYPE(c_ptr) :: f_decomp_info
    TYPE(c_ptr) :: f_edge_blk
    TYPE(c_ptr) :: f_edge_idx
    TYPE(c_ptr) :: f_end_block
    TYPE(c_ptr) :: f_end_index
    TYPE(c_ptr) :: f_neighbor_blk
    TYPE(c_ptr) :: f_neighbor_idx
    TYPE(c_ptr) :: f_start_block
    TYPE(c_ptr) :: f_start_index
  END TYPE cm_t_grid_cells

  TYPE, BIND(C) :: cm_t_nh_metrics
    INTEGER(c_int) :: f___f2dace_SA_coeff1_dwdz_d_0_s_332
    INTEGER(c_int) :: f___f2dace_SA_coeff1_dwdz_d_1_s_333
    INTEGER(c_int) :: f___f2dace_SA_coeff1_dwdz_d_2_s_334
    INTEGER(c_int) :: f___f2dace_SA_coeff2_dwdz_d_0_s_335
    INTEGER(c_int) :: f___f2dace_SA_coeff2_dwdz_d_1_s_336
    INTEGER(c_int) :: f___f2dace_SA_coeff2_dwdz_d_2_s_337
    INTEGER(c_int) :: f___f2dace_SA_coeff_gradekin_d_0_s_329
    INTEGER(c_int) :: f___f2dace_SA_coeff_gradekin_d_1_s_330
    INTEGER(c_int) :: f___f2dace_SA_coeff_gradekin_d_2_s_331
    INTEGER(c_int) :: f___f2dace_SA_ddqz_z_full_e_d_0_s_314
    INTEGER(c_int) :: f___f2dace_SA_ddqz_z_full_e_d_1_s_315
    INTEGER(c_int) :: f___f2dace_SA_ddqz_z_full_e_d_2_s_316
    INTEGER(c_int) :: f___f2dace_SA_ddqz_z_half_d_0_s_317
    INTEGER(c_int) :: f___f2dace_SA_ddqz_z_half_d_1_s_318
    INTEGER(c_int) :: f___f2dace_SA_ddqz_z_half_d_2_s_319
    INTEGER(c_int) :: f___f2dace_SA_ddxn_z_full_d_0_s_308
    INTEGER(c_int) :: f___f2dace_SA_ddxn_z_full_d_1_s_309
    INTEGER(c_int) :: f___f2dace_SA_ddxn_z_full_d_2_s_310
    INTEGER(c_int) :: f___f2dace_SA_ddxt_z_full_d_0_s_311
    INTEGER(c_int) :: f___f2dace_SA_ddxt_z_full_d_1_s_312
    INTEGER(c_int) :: f___f2dace_SA_ddxt_z_full_d_2_s_313
    INTEGER(c_int) :: f___f2dace_SA_deepatmo_gradh_ifc_d_0_s_340
    INTEGER(c_int) :: f___f2dace_SA_deepatmo_gradh_mc_d_0_s_338
    INTEGER(c_int) :: f___f2dace_SA_deepatmo_invr_ifc_d_0_s_341
    INTEGER(c_int) :: f___f2dace_SA_deepatmo_invr_mc_d_0_s_339
    INTEGER(c_int) :: f___f2dace_SA_wgtfac_c_d_0_s_320
    INTEGER(c_int) :: f___f2dace_SA_wgtfac_c_d_1_s_321
    INTEGER(c_int) :: f___f2dace_SA_wgtfac_c_d_2_s_322
    INTEGER(c_int) :: f___f2dace_SA_wgtfac_e_d_0_s_323
    INTEGER(c_int) :: f___f2dace_SA_wgtfac_e_d_1_s_324
    INTEGER(c_int) :: f___f2dace_SA_wgtfac_e_d_2_s_325
    INTEGER(c_int) :: f___f2dace_SA_wgtfacq_e_d_0_s_326
    INTEGER(c_int) :: f___f2dace_SA_wgtfacq_e_d_1_s_327
    INTEGER(c_int) :: f___f2dace_SA_wgtfacq_e_d_2_s_328
    INTEGER(c_int) :: f___f2dace_SOA_coeff1_dwdz_d_0_s_332
    INTEGER(c_int) :: f___f2dace_SOA_coeff1_dwdz_d_1_s_333
    INTEGER(c_int) :: f___f2dace_SOA_coeff1_dwdz_d_2_s_334
    INTEGER(c_int) :: f___f2dace_SOA_coeff2_dwdz_d_0_s_335
    INTEGER(c_int) :: f___f2dace_SOA_coeff2_dwdz_d_1_s_336
    INTEGER(c_int) :: f___f2dace_SOA_coeff2_dwdz_d_2_s_337
    INTEGER(c_int) :: f___f2dace_SOA_coeff_gradekin_d_0_s_329
    INTEGER(c_int) :: f___f2dace_SOA_coeff_gradekin_d_1_s_330
    INTEGER(c_int) :: f___f2dace_SOA_coeff_gradekin_d_2_s_331
    INTEGER(c_int) :: f___f2dace_SOA_ddqz_z_full_e_d_0_s_314
    INTEGER(c_int) :: f___f2dace_SOA_ddqz_z_full_e_d_1_s_315
    INTEGER(c_int) :: f___f2dace_SOA_ddqz_z_full_e_d_2_s_316
    INTEGER(c_int) :: f___f2dace_SOA_ddqz_z_half_d_0_s_317
    INTEGER(c_int) :: f___f2dace_SOA_ddqz_z_half_d_1_s_318
    INTEGER(c_int) :: f___f2dace_SOA_ddqz_z_half_d_2_s_319
    INTEGER(c_int) :: f___f2dace_SOA_ddxn_z_full_d_0_s_308
    INTEGER(c_int) :: f___f2dace_SOA_ddxn_z_full_d_1_s_309
    INTEGER(c_int) :: f___f2dace_SOA_ddxn_z_full_d_2_s_310
    INTEGER(c_int) :: f___f2dace_SOA_ddxt_z_full_d_0_s_311
    INTEGER(c_int) :: f___f2dace_SOA_ddxt_z_full_d_1_s_312
    INTEGER(c_int) :: f___f2dace_SOA_ddxt_z_full_d_2_s_313
    INTEGER(c_int) :: f___f2dace_SOA_deepatmo_gradh_ifc_d_0_s_340
    INTEGER(c_int) :: f___f2dace_SOA_deepatmo_gradh_mc_d_0_s_338
    INTEGER(c_int) :: f___f2dace_SOA_deepatmo_invr_ifc_d_0_s_341
    INTEGER(c_int) :: f___f2dace_SOA_deepatmo_invr_mc_d_0_s_339
    INTEGER(c_int) :: f___f2dace_SOA_wgtfac_c_d_0_s_320
    INTEGER(c_int) :: f___f2dace_SOA_wgtfac_c_d_1_s_321
    INTEGER(c_int) :: f___f2dace_SOA_wgtfac_c_d_2_s_322
    INTEGER(c_int) :: f___f2dace_SOA_wgtfac_e_d_0_s_323
    INTEGER(c_int) :: f___f2dace_SOA_wgtfac_e_d_1_s_324
    INTEGER(c_int) :: f___f2dace_SOA_wgtfac_e_d_2_s_325
    INTEGER(c_int) :: f___f2dace_SOA_wgtfacq_e_d_0_s_326
    INTEGER(c_int) :: f___f2dace_SOA_wgtfacq_e_d_1_s_327
    INTEGER(c_int) :: f___f2dace_SOA_wgtfacq_e_d_2_s_328
    TYPE(c_ptr) :: f_coeff1_dwdz
    TYPE(c_ptr) :: f_coeff2_dwdz
    TYPE(c_ptr) :: f_coeff_gradekin
    TYPE(c_ptr) :: f_ddqz_z_full_e
    TYPE(c_ptr) :: f_ddqz_z_half
    TYPE(c_ptr) :: f_ddxn_z_full
    TYPE(c_ptr) :: f_ddxt_z_full
    TYPE(c_ptr) :: f_deepatmo_gradh_ifc
    TYPE(c_ptr) :: f_deepatmo_gradh_mc
    TYPE(c_ptr) :: f_deepatmo_invr_ifc
    TYPE(c_ptr) :: f_deepatmo_invr_mc
    TYPE(c_ptr) :: f_wgtfac_c
    TYPE(c_ptr) :: f_wgtfac_e
    TYPE(c_ptr) :: f_wgtfacq_e
  END TYPE cm_t_nh_metrics

  TYPE, BIND(C) :: cm_t_grid_vertices
    INTEGER(c_int) :: f___f2dace_SA_cell_blk_d_0_s_203
    INTEGER(c_int) :: f___f2dace_SA_cell_blk_d_1_s_204
    INTEGER(c_int) :: f___f2dace_SA_cell_blk_d_2_s_205
    INTEGER(c_int) :: f___f2dace_SA_cell_idx_d_0_s_200
    INTEGER(c_int) :: f___f2dace_SA_cell_idx_d_1_s_201
    INTEGER(c_int) :: f___f2dace_SA_cell_idx_d_2_s_202
    INTEGER(c_int) :: f___f2dace_SA_edge_blk_d_0_s_209
    INTEGER(c_int) :: f___f2dace_SA_edge_blk_d_1_s_210
    INTEGER(c_int) :: f___f2dace_SA_edge_blk_d_2_s_211
    INTEGER(c_int) :: f___f2dace_SA_edge_idx_d_0_s_206
    INTEGER(c_int) :: f___f2dace_SA_edge_idx_d_1_s_207
    INTEGER(c_int) :: f___f2dace_SA_edge_idx_d_2_s_208
    INTEGER(c_int) :: f___f2dace_SA_end_block_d_0_s_215
    INTEGER(c_int) :: f___f2dace_SA_end_index_d_0_s_213
    INTEGER(c_int) :: f___f2dace_SA_start_block_d_0_s_214
    INTEGER(c_int) :: f___f2dace_SA_start_index_d_0_s_212
    INTEGER(c_int) :: f___f2dace_SOA_cell_blk_d_0_s_203
    INTEGER(c_int) :: f___f2dace_SOA_cell_blk_d_1_s_204
    INTEGER(c_int) :: f___f2dace_SOA_cell_blk_d_2_s_205
    INTEGER(c_int) :: f___f2dace_SOA_cell_idx_d_0_s_200
    INTEGER(c_int) :: f___f2dace_SOA_cell_idx_d_1_s_201
    INTEGER(c_int) :: f___f2dace_SOA_cell_idx_d_2_s_202
    INTEGER(c_int) :: f___f2dace_SOA_edge_blk_d_0_s_209
    INTEGER(c_int) :: f___f2dace_SOA_edge_blk_d_1_s_210
    INTEGER(c_int) :: f___f2dace_SOA_edge_blk_d_2_s_211
    INTEGER(c_int) :: f___f2dace_SOA_edge_idx_d_0_s_206
    INTEGER(c_int) :: f___f2dace_SOA_edge_idx_d_1_s_207
    INTEGER(c_int) :: f___f2dace_SOA_edge_idx_d_2_s_208
    INTEGER(c_int) :: f___f2dace_SOA_end_block_d_0_s_215
    INTEGER(c_int) :: f___f2dace_SOA_end_index_d_0_s_213
    INTEGER(c_int) :: f___f2dace_SOA_start_block_d_0_s_214
    INTEGER(c_int) :: f___f2dace_SOA_start_index_d_0_s_212
    TYPE(c_ptr) :: f_cell_blk
    TYPE(c_ptr) :: f_cell_idx
    TYPE(c_ptr) :: f_edge_blk
    TYPE(c_ptr) :: f_edge_idx
    TYPE(c_ptr) :: f_end_block
    TYPE(c_ptr) :: f_end_index
    TYPE(c_ptr) :: f_start_block
    TYPE(c_ptr) :: f_start_index
  END TYPE cm_t_grid_vertices

  TYPE, BIND(C) :: cm_t_patch
    TYPE(c_ptr) :: f_cells
    TYPE(c_ptr) :: f_edges
    INTEGER(c_int) :: f_nblks_c
    INTEGER(c_int) :: f_nblks_e
    INTEGER(c_int) :: f_nblks_v
    TYPE(c_ptr) :: f_verts
  END TYPE cm_t_patch

  TYPE, BIND(C) :: cm_t_nh_diag
    INTEGER(c_int) :: f___f2dace_SA_ddt_vn_apc_pc_d_0_s_300
    INTEGER(c_int) :: f___f2dace_SA_ddt_vn_apc_pc_d_1_s_301
    INTEGER(c_int) :: f___f2dace_SA_ddt_vn_apc_pc_d_2_s_302
    INTEGER(c_int) :: f___f2dace_SA_ddt_vn_apc_pc_d_3_s_303
    INTEGER(c_int) :: f___f2dace_SA_ddt_w_adv_pc_d_0_s_304
    INTEGER(c_int) :: f___f2dace_SA_ddt_w_adv_pc_d_1_s_305
    INTEGER(c_int) :: f___f2dace_SA_ddt_w_adv_pc_d_2_s_306
    INTEGER(c_int) :: f___f2dace_SA_ddt_w_adv_pc_d_3_s_307
    INTEGER(c_int) :: f___f2dace_SA_vn_ie_d_0_s_294
    INTEGER(c_int) :: f___f2dace_SA_vn_ie_d_1_s_295
    INTEGER(c_int) :: f___f2dace_SA_vn_ie_d_2_s_296
    INTEGER(c_int) :: f___f2dace_SA_vt_d_0_s_291
    INTEGER(c_int) :: f___f2dace_SA_vt_d_1_s_292
    INTEGER(c_int) :: f___f2dace_SA_vt_d_2_s_293
    INTEGER(c_int) :: f___f2dace_SA_w_concorr_c_d_0_s_297
    INTEGER(c_int) :: f___f2dace_SA_w_concorr_c_d_1_s_298
    INTEGER(c_int) :: f___f2dace_SA_w_concorr_c_d_2_s_299
    INTEGER(c_int) :: f___f2dace_SOA_ddt_vn_apc_pc_d_0_s_300
    INTEGER(c_int) :: f___f2dace_SOA_ddt_vn_apc_pc_d_1_s_301
    INTEGER(c_int) :: f___f2dace_SOA_ddt_vn_apc_pc_d_2_s_302
    INTEGER(c_int) :: f___f2dace_SOA_ddt_vn_apc_pc_d_3_s_303
    INTEGER(c_int) :: f___f2dace_SOA_ddt_w_adv_pc_d_0_s_304
    INTEGER(c_int) :: f___f2dace_SOA_ddt_w_adv_pc_d_1_s_305
    INTEGER(c_int) :: f___f2dace_SOA_ddt_w_adv_pc_d_2_s_306
    INTEGER(c_int) :: f___f2dace_SOA_ddt_w_adv_pc_d_3_s_307
    INTEGER(c_int) :: f___f2dace_SOA_vn_ie_d_0_s_294
    INTEGER(c_int) :: f___f2dace_SOA_vn_ie_d_1_s_295
    INTEGER(c_int) :: f___f2dace_SOA_vn_ie_d_2_s_296
    INTEGER(c_int) :: f___f2dace_SOA_vt_d_0_s_291
    INTEGER(c_int) :: f___f2dace_SOA_vt_d_1_s_292
    INTEGER(c_int) :: f___f2dace_SOA_vt_d_2_s_293
    INTEGER(c_int) :: f___f2dace_SOA_w_concorr_c_d_0_s_297
    INTEGER(c_int) :: f___f2dace_SOA_w_concorr_c_d_1_s_298
    INTEGER(c_int) :: f___f2dace_SOA_w_concorr_c_d_2_s_299
    TYPE(c_ptr) :: f_ddt_vn_apc_pc
    TYPE(c_ptr) :: f_ddt_w_adv_pc
    REAL(c_double) :: f_max_vcfl_dyn
    TYPE(c_ptr) :: f_vn_ie
    TYPE(c_ptr) :: f_vt
    TYPE(c_ptr) :: f_w_concorr_c
  END TYPE cm_t_nh_diag

CONTAINS

  PURE FUNCTION meta_t_grid_edges_area_edge(o) RESULT(m)
    TYPE(cm_t_grid_edges), INTENT(IN) :: o
    TYPE(cm_meta) :: m
    m%rank = 2
    m%dims(1) = o%f___f2dace_SA_area_edge_d_0_s_188
    m%lbs(1) = o%f___f2dace_SOA_area_edge_d_0_s_188
    m%dims(2) = o%f___f2dace_SA_area_edge_d_1_s_189
    m%lbs(2) = o%f___f2dace_SOA_area_edge_d_1_s_189
  END FUNCTION meta_t_grid_edges_area_edge

  PURE FUNCTION meta_t_grid_edges_cell_blk(o) RESULT(m)
    TYPE(cm_t_grid_edges), INTENT(IN) :: o
    TYPE(cm_meta) :: m
    m%rank = 3
    m%dims(1) = o%f___f2dace_SA_cell_blk_d_0_s_167
    m%lbs(1) = o%f___f2dace_SOA_cell_blk_d_0_s_167
    m%dims(2) = o%f___f2dace_SA_cell_blk_d_1_s_168
    m%lbs(2) = o%f___f2dace_SOA_cell_blk_d_1_s_168
    m%dims(3) = o%f___f2dace_SA_cell_blk_d_2_s_169
    m%lbs(3) = o%f___f2dace_SOA_cell_blk_d_2_s_169
  END FUNCTION meta_t_grid_edges_cell_blk

  PURE FUNCTION meta_t_grid_edges_cell_idx(o) RESULT(m)
    TYPE(cm_t_grid_edges), INTENT(IN) :: o
    TYPE(cm_meta) :: m
    m%rank = 3
    m%dims(1) = o%f___f2dace_SA_cell_idx_d_0_s_164
    m%lbs(1) = o%f___f2dace_SOA_cell_idx_d_0_s_164
    m%dims(2) = o%f___f2dace_SA_cell_idx_d_1_s_165
    m%lbs(2) = o%f___f2dace_SOA_cell_idx_d_1_s_165
    m%dims(3) = o%f___f2dace_SA_cell_idx_d_2_s_166
    m%lbs(3) = o%f___f2dace_SOA_cell_idx_d_2_s_166
  END FUNCTION meta_t_grid_edges_cell_idx

  PURE FUNCTION meta_t_grid_edges_end_block(o) RESULT(m)
    TYPE(cm_t_grid_edges), INTENT(IN) :: o
    TYPE(cm_meta) :: m
    m%rank = 1
    m%dims(1) = o%f___f2dace_SA_end_block_d_0_s_199
    m%lbs(1) = o%f___f2dace_SOA_end_block_d_0_s_199
  END FUNCTION meta_t_grid_edges_end_block

  PURE FUNCTION meta_t_grid_edges_end_index(o) RESULT(m)
    TYPE(cm_t_grid_edges), INTENT(IN) :: o
    TYPE(cm_meta) :: m
    m%rank = 1
    m%dims(1) = o%f___f2dace_SA_end_index_d_0_s_197
    m%lbs(1) = o%f___f2dace_SOA_end_index_d_0_s_197
  END FUNCTION meta_t_grid_edges_end_index

  PURE FUNCTION meta_t_grid_edges_f_e(o) RESULT(m)
    TYPE(cm_t_grid_edges), INTENT(IN) :: o
    TYPE(cm_meta) :: m
    m%rank = 2
    m%dims(1) = o%f___f2dace_SA_f_e_d_0_s_190
    m%lbs(1) = o%f___f2dace_SOA_f_e_d_0_s_190
    m%dims(2) = o%f___f2dace_SA_f_e_d_1_s_191
    m%lbs(2) = o%f___f2dace_SOA_f_e_d_1_s_191
  END FUNCTION meta_t_grid_edges_f_e

  PURE FUNCTION meta_t_grid_edges_fn_e(o) RESULT(m)
    TYPE(cm_t_grid_edges), INTENT(IN) :: o
    TYPE(cm_meta) :: m
    m%rank = 2
    m%dims(1) = o%f___f2dace_SA_fn_e_d_0_s_192
    m%lbs(1) = o%f___f2dace_SOA_fn_e_d_0_s_192
    m%dims(2) = o%f___f2dace_SA_fn_e_d_1_s_193
    m%lbs(2) = o%f___f2dace_SOA_fn_e_d_1_s_193
  END FUNCTION meta_t_grid_edges_fn_e

  PURE FUNCTION meta_t_grid_edges_ft_e(o) RESULT(m)
    TYPE(cm_t_grid_edges), INTENT(IN) :: o
    TYPE(cm_meta) :: m
    m%rank = 2
    m%dims(1) = o%f___f2dace_SA_ft_e_d_0_s_194
    m%lbs(1) = o%f___f2dace_SOA_ft_e_d_0_s_194
    m%dims(2) = o%f___f2dace_SA_ft_e_d_1_s_195
    m%lbs(2) = o%f___f2dace_SOA_ft_e_d_1_s_195
  END FUNCTION meta_t_grid_edges_ft_e

  PURE FUNCTION meta_t_grid_edges_inv_dual_edge_length(o) RESULT(m)
    TYPE(cm_t_grid_edges), INTENT(IN) :: o
    TYPE(cm_meta) :: m
    m%rank = 2
    m%dims(1) = o%f___f2dace_SA_inv_dual_edge_length_d_0_s_186
    m%lbs(1) = o%f___f2dace_SOA_inv_dual_edge_length_d_0_s_186
    m%dims(2) = o%f___f2dace_SA_inv_dual_edge_length_d_1_s_187
    m%lbs(2) = o%f___f2dace_SOA_inv_dual_edge_length_d_1_s_187
  END FUNCTION meta_t_grid_edges_inv_dual_edge_length

  PURE FUNCTION meta_t_grid_edges_inv_primal_edge_length(o) RESULT(m)
    TYPE(cm_t_grid_edges), INTENT(IN) :: o
    TYPE(cm_meta) :: m
    m%rank = 2
    m%dims(1) = o%f___f2dace_SA_inv_primal_edge_length_d_0_s_184
    m%lbs(1) = o%f___f2dace_SOA_inv_primal_edge_length_d_0_s_184
    m%dims(2) = o%f___f2dace_SA_inv_primal_edge_length_d_1_s_185
    m%lbs(2) = o%f___f2dace_SOA_inv_primal_edge_length_d_1_s_185
  END FUNCTION meta_t_grid_edges_inv_primal_edge_length

  PURE FUNCTION meta_t_grid_edges_quad_blk(o) RESULT(m)
    TYPE(cm_t_grid_edges), INTENT(IN) :: o
    TYPE(cm_meta) :: m
    m%rank = 3
    m%dims(1) = o%f___f2dace_SA_quad_blk_d_0_s_181
    m%lbs(1) = o%f___f2dace_SOA_quad_blk_d_0_s_181
    m%dims(2) = o%f___f2dace_SA_quad_blk_d_1_s_182
    m%lbs(2) = o%f___f2dace_SOA_quad_blk_d_1_s_182
    m%dims(3) = o%f___f2dace_SA_quad_blk_d_2_s_183
    m%lbs(3) = o%f___f2dace_SOA_quad_blk_d_2_s_183
  END FUNCTION meta_t_grid_edges_quad_blk

  PURE FUNCTION meta_t_grid_edges_quad_idx(o) RESULT(m)
    TYPE(cm_t_grid_edges), INTENT(IN) :: o
    TYPE(cm_meta) :: m
    m%rank = 3
    m%dims(1) = o%f___f2dace_SA_quad_idx_d_0_s_178
    m%lbs(1) = o%f___f2dace_SOA_quad_idx_d_0_s_178
    m%dims(2) = o%f___f2dace_SA_quad_idx_d_1_s_179
    m%lbs(2) = o%f___f2dace_SOA_quad_idx_d_1_s_179
    m%dims(3) = o%f___f2dace_SA_quad_idx_d_2_s_180
    m%lbs(3) = o%f___f2dace_SOA_quad_idx_d_2_s_180
  END FUNCTION meta_t_grid_edges_quad_idx

  PURE FUNCTION meta_t_grid_edges_start_block(o) RESULT(m)
    TYPE(cm_t_grid_edges), INTENT(IN) :: o
    TYPE(cm_meta) :: m
    m%rank = 1
    m%dims(1) = o%f___f2dace_SA_start_block_d_0_s_198
    m%lbs(1) = o%f___f2dace_SOA_start_block_d_0_s_198
  END FUNCTION meta_t_grid_edges_start_block

  PURE FUNCTION meta_t_grid_edges_start_index(o) RESULT(m)
    TYPE(cm_t_grid_edges), INTENT(IN) :: o
    TYPE(cm_meta) :: m
    m%rank = 1
    m%dims(1) = o%f___f2dace_SA_start_index_d_0_s_196
    m%lbs(1) = o%f___f2dace_SOA_start_index_d_0_s_196
  END FUNCTION meta_t_grid_edges_start_index

  PURE FUNCTION meta_t_grid_edges_tangent_orientation(o) RESULT(m)
    TYPE(cm_t_grid_edges), INTENT(IN) :: o
    TYPE(cm_meta) :: m
    m%rank = 2
    m%dims(1) = o%f___f2dace_SA_tangent_orientation_d_0_s_176
    m%lbs(1) = o%f___f2dace_SOA_tangent_orientation_d_0_s_176
    m%dims(2) = o%f___f2dace_SA_tangent_orientation_d_1_s_177
    m%lbs(2) = o%f___f2dace_SOA_tangent_orientation_d_1_s_177
  END FUNCTION meta_t_grid_edges_tangent_orientation

  PURE FUNCTION meta_t_grid_edges_vertex_blk(o) RESULT(m)
    TYPE(cm_t_grid_edges), INTENT(IN) :: o
    TYPE(cm_meta) :: m
    m%rank = 3
    m%dims(1) = o%f___f2dace_SA_vertex_blk_d_0_s_173
    m%lbs(1) = o%f___f2dace_SOA_vertex_blk_d_0_s_173
    m%dims(2) = o%f___f2dace_SA_vertex_blk_d_1_s_174
    m%lbs(2) = o%f___f2dace_SOA_vertex_blk_d_1_s_174
    m%dims(3) = o%f___f2dace_SA_vertex_blk_d_2_s_175
    m%lbs(3) = o%f___f2dace_SOA_vertex_blk_d_2_s_175
  END FUNCTION meta_t_grid_edges_vertex_blk

  PURE FUNCTION meta_t_grid_edges_vertex_idx(o) RESULT(m)
    TYPE(cm_t_grid_edges), INTENT(IN) :: o
    TYPE(cm_meta) :: m
    m%rank = 3
    m%dims(1) = o%f___f2dace_SA_vertex_idx_d_0_s_170
    m%lbs(1) = o%f___f2dace_SOA_vertex_idx_d_0_s_170
    m%dims(2) = o%f___f2dace_SA_vertex_idx_d_1_s_171
    m%lbs(2) = o%f___f2dace_SOA_vertex_idx_d_1_s_171
    m%dims(3) = o%f___f2dace_SA_vertex_idx_d_2_s_172
    m%lbs(3) = o%f___f2dace_SOA_vertex_idx_d_2_s_172
  END FUNCTION meta_t_grid_edges_vertex_idx

  PURE FUNCTION meta_t_int_state_c_lin_e(o) RESULT(m)
    TYPE(cm_t_int_state), INTENT(IN) :: o
    TYPE(cm_meta) :: m
    m%rank = 3
    m%dims(1) = o%f___f2dace_SA_c_lin_e_d_0_s_25
    m%lbs(1) = o%f___f2dace_SOA_c_lin_e_d_0_s_25
    m%dims(2) = o%f___f2dace_SA_c_lin_e_d_1_s_26
    m%lbs(2) = o%f___f2dace_SOA_c_lin_e_d_1_s_26
    m%dims(3) = o%f___f2dace_SA_c_lin_e_d_2_s_27
    m%lbs(3) = o%f___f2dace_SOA_c_lin_e_d_2_s_27
  END FUNCTION meta_t_int_state_c_lin_e

  PURE FUNCTION meta_t_int_state_cells_aw_verts(o) RESULT(m)
    TYPE(cm_t_int_state), INTENT(IN) :: o
    TYPE(cm_meta) :: m
    m%rank = 3
    m%dims(1) = o%f___f2dace_SA_cells_aw_verts_d_0_s_31
    m%lbs(1) = o%f___f2dace_SOA_cells_aw_verts_d_0_s_31
    m%dims(2) = o%f___f2dace_SA_cells_aw_verts_d_1_s_32
    m%lbs(2) = o%f___f2dace_SOA_cells_aw_verts_d_1_s_32
    m%dims(3) = o%f___f2dace_SA_cells_aw_verts_d_2_s_33
    m%lbs(3) = o%f___f2dace_SOA_cells_aw_verts_d_2_s_33
  END FUNCTION meta_t_int_state_cells_aw_verts

  PURE FUNCTION meta_t_int_state_e_bln_c_s(o) RESULT(m)
    TYPE(cm_t_int_state), INTENT(IN) :: o
    TYPE(cm_meta) :: m
    m%rank = 3
    m%dims(1) = o%f___f2dace_SA_e_bln_c_s_d_0_s_28
    m%lbs(1) = o%f___f2dace_SOA_e_bln_c_s_d_0_s_28
    m%dims(2) = o%f___f2dace_SA_e_bln_c_s_d_1_s_29
    m%lbs(2) = o%f___f2dace_SOA_e_bln_c_s_d_1_s_29
    m%dims(3) = o%f___f2dace_SA_e_bln_c_s_d_2_s_30
    m%lbs(3) = o%f___f2dace_SOA_e_bln_c_s_d_2_s_30
  END FUNCTION meta_t_int_state_e_bln_c_s

  PURE FUNCTION meta_t_int_state_geofac_grdiv(o) RESULT(m)
    TYPE(cm_t_int_state), INTENT(IN) :: o
    TYPE(cm_meta) :: m
    m%rank = 3
    m%dims(1) = o%f___f2dace_SA_geofac_grdiv_d_0_s_37
    m%lbs(1) = o%f___f2dace_SOA_geofac_grdiv_d_0_s_37
    m%dims(2) = o%f___f2dace_SA_geofac_grdiv_d_1_s_38
    m%lbs(2) = o%f___f2dace_SOA_geofac_grdiv_d_1_s_38
    m%dims(3) = o%f___f2dace_SA_geofac_grdiv_d_2_s_39
    m%lbs(3) = o%f___f2dace_SOA_geofac_grdiv_d_2_s_39
  END FUNCTION meta_t_int_state_geofac_grdiv

  PURE FUNCTION meta_t_int_state_geofac_n2s(o) RESULT(m)
    TYPE(cm_t_int_state), INTENT(IN) :: o
    TYPE(cm_meta) :: m
    m%rank = 3
    m%dims(1) = o%f___f2dace_SA_geofac_n2s_d_0_s_43
    m%lbs(1) = o%f___f2dace_SOA_geofac_n2s_d_0_s_43
    m%dims(2) = o%f___f2dace_SA_geofac_n2s_d_1_s_44
    m%lbs(2) = o%f___f2dace_SOA_geofac_n2s_d_1_s_44
    m%dims(3) = o%f___f2dace_SA_geofac_n2s_d_2_s_45
    m%lbs(3) = o%f___f2dace_SOA_geofac_n2s_d_2_s_45
  END FUNCTION meta_t_int_state_geofac_n2s

  PURE FUNCTION meta_t_int_state_geofac_rot(o) RESULT(m)
    TYPE(cm_t_int_state), INTENT(IN) :: o
    TYPE(cm_meta) :: m
    m%rank = 3
    m%dims(1) = o%f___f2dace_SA_geofac_rot_d_0_s_40
    m%lbs(1) = o%f___f2dace_SOA_geofac_rot_d_0_s_40
    m%dims(2) = o%f___f2dace_SA_geofac_rot_d_1_s_41
    m%lbs(2) = o%f___f2dace_SOA_geofac_rot_d_1_s_41
    m%dims(3) = o%f___f2dace_SA_geofac_rot_d_2_s_42
    m%lbs(3) = o%f___f2dace_SOA_geofac_rot_d_2_s_42
  END FUNCTION meta_t_int_state_geofac_rot

  PURE FUNCTION meta_t_int_state_rbf_vec_coeff_e(o) RESULT(m)
    TYPE(cm_t_int_state), INTENT(IN) :: o
    TYPE(cm_meta) :: m
    m%rank = 3
    m%dims(1) = o%f___f2dace_SA_rbf_vec_coeff_e_d_0_s_34
    m%lbs(1) = o%f___f2dace_SOA_rbf_vec_coeff_e_d_0_s_34
    m%dims(2) = o%f___f2dace_SA_rbf_vec_coeff_e_d_1_s_35
    m%lbs(2) = o%f___f2dace_SOA_rbf_vec_coeff_e_d_1_s_35
    m%dims(3) = o%f___f2dace_SA_rbf_vec_coeff_e_d_2_s_36
    m%lbs(3) = o%f___f2dace_SOA_rbf_vec_coeff_e_d_2_s_36
  END FUNCTION meta_t_int_state_rbf_vec_coeff_e

  PURE FUNCTION meta_t_nh_prog_vn(o) RESULT(m)
    TYPE(cm_t_nh_prog), INTENT(IN) :: o
    TYPE(cm_meta) :: m
    m%rank = 3
    m%dims(1) = o%f___f2dace_SA_vn_d_0_s_288
    m%lbs(1) = o%f___f2dace_SOA_vn_d_0_s_288
    m%dims(2) = o%f___f2dace_SA_vn_d_1_s_289
    m%lbs(2) = o%f___f2dace_SOA_vn_d_1_s_289
    m%dims(3) = o%f___f2dace_SA_vn_d_2_s_290
    m%lbs(3) = o%f___f2dace_SOA_vn_d_2_s_290
  END FUNCTION meta_t_nh_prog_vn

  PURE FUNCTION meta_t_nh_prog_w(o) RESULT(m)
    TYPE(cm_t_nh_prog), INTENT(IN) :: o
    TYPE(cm_meta) :: m
    m%rank = 3
    m%dims(1) = o%f___f2dace_SA_w_d_0_s_285
    m%lbs(1) = o%f___f2dace_SOA_w_d_0_s_285
    m%dims(2) = o%f___f2dace_SA_w_d_1_s_286
    m%lbs(2) = o%f___f2dace_SOA_w_d_1_s_286
    m%dims(3) = o%f___f2dace_SA_w_d_2_s_287
    m%lbs(3) = o%f___f2dace_SOA_w_d_2_s_287
  END FUNCTION meta_t_nh_prog_w

  PURE FUNCTION meta_t_grid_domain_decomp_info_owner_mask(o) RESULT(m)
    TYPE(cm_t_grid_domain_decomp_info), INTENT(IN) :: o
    TYPE(cm_meta) :: m
    m%rank = 2
    m%dims(1) = o%f___f2dace_SA_owner_mask_d_0_s_2
    m%lbs(1) = o%f___f2dace_SOA_owner_mask_d_0_s_2
    m%dims(2) = o%f___f2dace_SA_owner_mask_d_1_s_3
    m%lbs(2) = o%f___f2dace_SOA_owner_mask_d_1_s_3
  END FUNCTION meta_t_grid_domain_decomp_info_owner_mask

  PURE FUNCTION meta_t_grid_cells_area(o) RESULT(m)
    TYPE(cm_t_grid_cells), INTENT(IN) :: o
    TYPE(cm_meta) :: m
    m%rank = 2
    m%dims(1) = o%f___f2dace_SA_area_d_0_s_158
    m%lbs(1) = o%f___f2dace_SOA_area_d_0_s_158
    m%dims(2) = o%f___f2dace_SA_area_d_1_s_159
    m%lbs(2) = o%f___f2dace_SOA_area_d_1_s_159
  END FUNCTION meta_t_grid_cells_area

  PURE FUNCTION meta_t_grid_cells_edge_blk(o) RESULT(m)
    TYPE(cm_t_grid_cells), INTENT(IN) :: o
    TYPE(cm_meta) :: m
    m%rank = 3
    m%dims(1) = o%f___f2dace_SA_edge_blk_d_0_s_155
    m%lbs(1) = o%f___f2dace_SOA_edge_blk_d_0_s_155
    m%dims(2) = o%f___f2dace_SA_edge_blk_d_1_s_156
    m%lbs(2) = o%f___f2dace_SOA_edge_blk_d_1_s_156
    m%dims(3) = o%f___f2dace_SA_edge_blk_d_2_s_157
    m%lbs(3) = o%f___f2dace_SOA_edge_blk_d_2_s_157
  END FUNCTION meta_t_grid_cells_edge_blk

  PURE FUNCTION meta_t_grid_cells_edge_idx(o) RESULT(m)
    TYPE(cm_t_grid_cells), INTENT(IN) :: o
    TYPE(cm_meta) :: m
    m%rank = 3
    m%dims(1) = o%f___f2dace_SA_edge_idx_d_0_s_152
    m%lbs(1) = o%f___f2dace_SOA_edge_idx_d_0_s_152
    m%dims(2) = o%f___f2dace_SA_edge_idx_d_1_s_153
    m%lbs(2) = o%f___f2dace_SOA_edge_idx_d_1_s_153
    m%dims(3) = o%f___f2dace_SA_edge_idx_d_2_s_154
    m%lbs(3) = o%f___f2dace_SOA_edge_idx_d_2_s_154
  END FUNCTION meta_t_grid_cells_edge_idx

  PURE FUNCTION meta_t_grid_cells_end_block(o) RESULT(m)
    TYPE(cm_t_grid_cells), INTENT(IN) :: o
    TYPE(cm_meta) :: m
    m%rank = 1
    m%dims(1) = o%f___f2dace_SA_end_block_d_0_s_163
    m%lbs(1) = o%f___f2dace_SOA_end_block_d_0_s_163
  END FUNCTION meta_t_grid_cells_end_block

  PURE FUNCTION meta_t_grid_cells_end_index(o) RESULT(m)
    TYPE(cm_t_grid_cells), INTENT(IN) :: o
    TYPE(cm_meta) :: m
    m%rank = 1
    m%dims(1) = o%f___f2dace_SA_end_index_d_0_s_161
    m%lbs(1) = o%f___f2dace_SOA_end_index_d_0_s_161
  END FUNCTION meta_t_grid_cells_end_index

  PURE FUNCTION meta_t_grid_cells_neighbor_blk(o) RESULT(m)
    TYPE(cm_t_grid_cells), INTENT(IN) :: o
    TYPE(cm_meta) :: m
    m%rank = 3
    m%dims(1) = o%f___f2dace_SA_neighbor_blk_d_0_s_149
    m%lbs(1) = o%f___f2dace_SOA_neighbor_blk_d_0_s_149
    m%dims(2) = o%f___f2dace_SA_neighbor_blk_d_1_s_150
    m%lbs(2) = o%f___f2dace_SOA_neighbor_blk_d_1_s_150
    m%dims(3) = o%f___f2dace_SA_neighbor_blk_d_2_s_151
    m%lbs(3) = o%f___f2dace_SOA_neighbor_blk_d_2_s_151
  END FUNCTION meta_t_grid_cells_neighbor_blk

  PURE FUNCTION meta_t_grid_cells_neighbor_idx(o) RESULT(m)
    TYPE(cm_t_grid_cells), INTENT(IN) :: o
    TYPE(cm_meta) :: m
    m%rank = 3
    m%dims(1) = o%f___f2dace_SA_neighbor_idx_d_0_s_146
    m%lbs(1) = o%f___f2dace_SOA_neighbor_idx_d_0_s_146
    m%dims(2) = o%f___f2dace_SA_neighbor_idx_d_1_s_147
    m%lbs(2) = o%f___f2dace_SOA_neighbor_idx_d_1_s_147
    m%dims(3) = o%f___f2dace_SA_neighbor_idx_d_2_s_148
    m%lbs(3) = o%f___f2dace_SOA_neighbor_idx_d_2_s_148
  END FUNCTION meta_t_grid_cells_neighbor_idx

  PURE FUNCTION meta_t_grid_cells_start_block(o) RESULT(m)
    TYPE(cm_t_grid_cells), INTENT(IN) :: o
    TYPE(cm_meta) :: m
    m%rank = 1
    m%dims(1) = o%f___f2dace_SA_start_block_d_0_s_162
    m%lbs(1) = o%f___f2dace_SOA_start_block_d_0_s_162
  END FUNCTION meta_t_grid_cells_start_block

  PURE FUNCTION meta_t_grid_cells_start_index(o) RESULT(m)
    TYPE(cm_t_grid_cells), INTENT(IN) :: o
    TYPE(cm_meta) :: m
    m%rank = 1
    m%dims(1) = o%f___f2dace_SA_start_index_d_0_s_160
    m%lbs(1) = o%f___f2dace_SOA_start_index_d_0_s_160
  END FUNCTION meta_t_grid_cells_start_index

  PURE FUNCTION meta_t_nh_metrics_coeff1_dwdz(o) RESULT(m)
    TYPE(cm_t_nh_metrics), INTENT(IN) :: o
    TYPE(cm_meta) :: m
    m%rank = 3
    m%dims(1) = o%f___f2dace_SA_coeff1_dwdz_d_0_s_332
    m%lbs(1) = o%f___f2dace_SOA_coeff1_dwdz_d_0_s_332
    m%dims(2) = o%f___f2dace_SA_coeff1_dwdz_d_1_s_333
    m%lbs(2) = o%f___f2dace_SOA_coeff1_dwdz_d_1_s_333
    m%dims(3) = o%f___f2dace_SA_coeff1_dwdz_d_2_s_334
    m%lbs(3) = o%f___f2dace_SOA_coeff1_dwdz_d_2_s_334
  END FUNCTION meta_t_nh_metrics_coeff1_dwdz

  PURE FUNCTION meta_t_nh_metrics_coeff2_dwdz(o) RESULT(m)
    TYPE(cm_t_nh_metrics), INTENT(IN) :: o
    TYPE(cm_meta) :: m
    m%rank = 3
    m%dims(1) = o%f___f2dace_SA_coeff2_dwdz_d_0_s_335
    m%lbs(1) = o%f___f2dace_SOA_coeff2_dwdz_d_0_s_335
    m%dims(2) = o%f___f2dace_SA_coeff2_dwdz_d_1_s_336
    m%lbs(2) = o%f___f2dace_SOA_coeff2_dwdz_d_1_s_336
    m%dims(3) = o%f___f2dace_SA_coeff2_dwdz_d_2_s_337
    m%lbs(3) = o%f___f2dace_SOA_coeff2_dwdz_d_2_s_337
  END FUNCTION meta_t_nh_metrics_coeff2_dwdz

  PURE FUNCTION meta_t_nh_metrics_coeff_gradekin(o) RESULT(m)
    TYPE(cm_t_nh_metrics), INTENT(IN) :: o
    TYPE(cm_meta) :: m
    m%rank = 3
    m%dims(1) = o%f___f2dace_SA_coeff_gradekin_d_0_s_329
    m%lbs(1) = o%f___f2dace_SOA_coeff_gradekin_d_0_s_329
    m%dims(2) = o%f___f2dace_SA_coeff_gradekin_d_1_s_330
    m%lbs(2) = o%f___f2dace_SOA_coeff_gradekin_d_1_s_330
    m%dims(3) = o%f___f2dace_SA_coeff_gradekin_d_2_s_331
    m%lbs(3) = o%f___f2dace_SOA_coeff_gradekin_d_2_s_331
  END FUNCTION meta_t_nh_metrics_coeff_gradekin

  PURE FUNCTION meta_t_nh_metrics_ddqz_z_full_e(o) RESULT(m)
    TYPE(cm_t_nh_metrics), INTENT(IN) :: o
    TYPE(cm_meta) :: m
    m%rank = 3
    m%dims(1) = o%f___f2dace_SA_ddqz_z_full_e_d_0_s_314
    m%lbs(1) = o%f___f2dace_SOA_ddqz_z_full_e_d_0_s_314
    m%dims(2) = o%f___f2dace_SA_ddqz_z_full_e_d_1_s_315
    m%lbs(2) = o%f___f2dace_SOA_ddqz_z_full_e_d_1_s_315
    m%dims(3) = o%f___f2dace_SA_ddqz_z_full_e_d_2_s_316
    m%lbs(3) = o%f___f2dace_SOA_ddqz_z_full_e_d_2_s_316
  END FUNCTION meta_t_nh_metrics_ddqz_z_full_e

  PURE FUNCTION meta_t_nh_metrics_ddqz_z_half(o) RESULT(m)
    TYPE(cm_t_nh_metrics), INTENT(IN) :: o
    TYPE(cm_meta) :: m
    m%rank = 3
    m%dims(1) = o%f___f2dace_SA_ddqz_z_half_d_0_s_317
    m%lbs(1) = o%f___f2dace_SOA_ddqz_z_half_d_0_s_317
    m%dims(2) = o%f___f2dace_SA_ddqz_z_half_d_1_s_318
    m%lbs(2) = o%f___f2dace_SOA_ddqz_z_half_d_1_s_318
    m%dims(3) = o%f___f2dace_SA_ddqz_z_half_d_2_s_319
    m%lbs(3) = o%f___f2dace_SOA_ddqz_z_half_d_2_s_319
  END FUNCTION meta_t_nh_metrics_ddqz_z_half

  PURE FUNCTION meta_t_nh_metrics_ddxn_z_full(o) RESULT(m)
    TYPE(cm_t_nh_metrics), INTENT(IN) :: o
    TYPE(cm_meta) :: m
    m%rank = 3
    m%dims(1) = o%f___f2dace_SA_ddxn_z_full_d_0_s_308
    m%lbs(1) = o%f___f2dace_SOA_ddxn_z_full_d_0_s_308
    m%dims(2) = o%f___f2dace_SA_ddxn_z_full_d_1_s_309
    m%lbs(2) = o%f___f2dace_SOA_ddxn_z_full_d_1_s_309
    m%dims(3) = o%f___f2dace_SA_ddxn_z_full_d_2_s_310
    m%lbs(3) = o%f___f2dace_SOA_ddxn_z_full_d_2_s_310
  END FUNCTION meta_t_nh_metrics_ddxn_z_full

  PURE FUNCTION meta_t_nh_metrics_ddxt_z_full(o) RESULT(m)
    TYPE(cm_t_nh_metrics), INTENT(IN) :: o
    TYPE(cm_meta) :: m
    m%rank = 3
    m%dims(1) = o%f___f2dace_SA_ddxt_z_full_d_0_s_311
    m%lbs(1) = o%f___f2dace_SOA_ddxt_z_full_d_0_s_311
    m%dims(2) = o%f___f2dace_SA_ddxt_z_full_d_1_s_312
    m%lbs(2) = o%f___f2dace_SOA_ddxt_z_full_d_1_s_312
    m%dims(3) = o%f___f2dace_SA_ddxt_z_full_d_2_s_313
    m%lbs(3) = o%f___f2dace_SOA_ddxt_z_full_d_2_s_313
  END FUNCTION meta_t_nh_metrics_ddxt_z_full

  PURE FUNCTION meta_t_nh_metrics_deepatmo_gradh_ifc(o) RESULT(m)
    TYPE(cm_t_nh_metrics), INTENT(IN) :: o
    TYPE(cm_meta) :: m
    m%rank = 1
    m%dims(1) = o%f___f2dace_SA_deepatmo_gradh_ifc_d_0_s_340
    m%lbs(1) = o%f___f2dace_SOA_deepatmo_gradh_ifc_d_0_s_340
  END FUNCTION meta_t_nh_metrics_deepatmo_gradh_ifc

  PURE FUNCTION meta_t_nh_metrics_deepatmo_gradh_mc(o) RESULT(m)
    TYPE(cm_t_nh_metrics), INTENT(IN) :: o
    TYPE(cm_meta) :: m
    m%rank = 1
    m%dims(1) = o%f___f2dace_SA_deepatmo_gradh_mc_d_0_s_338
    m%lbs(1) = o%f___f2dace_SOA_deepatmo_gradh_mc_d_0_s_338
  END FUNCTION meta_t_nh_metrics_deepatmo_gradh_mc

  PURE FUNCTION meta_t_nh_metrics_deepatmo_invr_ifc(o) RESULT(m)
    TYPE(cm_t_nh_metrics), INTENT(IN) :: o
    TYPE(cm_meta) :: m
    m%rank = 1
    m%dims(1) = o%f___f2dace_SA_deepatmo_invr_ifc_d_0_s_341
    m%lbs(1) = o%f___f2dace_SOA_deepatmo_invr_ifc_d_0_s_341
  END FUNCTION meta_t_nh_metrics_deepatmo_invr_ifc

  PURE FUNCTION meta_t_nh_metrics_deepatmo_invr_mc(o) RESULT(m)
    TYPE(cm_t_nh_metrics), INTENT(IN) :: o
    TYPE(cm_meta) :: m
    m%rank = 1
    m%dims(1) = o%f___f2dace_SA_deepatmo_invr_mc_d_0_s_339
    m%lbs(1) = o%f___f2dace_SOA_deepatmo_invr_mc_d_0_s_339
  END FUNCTION meta_t_nh_metrics_deepatmo_invr_mc

  PURE FUNCTION meta_t_nh_metrics_wgtfac_c(o) RESULT(m)
    TYPE(cm_t_nh_metrics), INTENT(IN) :: o
    TYPE(cm_meta) :: m
    m%rank = 3
    m%dims(1) = o%f___f2dace_SA_wgtfac_c_d_0_s_320
    m%lbs(1) = o%f___f2dace_SOA_wgtfac_c_d_0_s_320
    m%dims(2) = o%f___f2dace_SA_wgtfac_c_d_1_s_321
    m%lbs(2) = o%f___f2dace_SOA_wgtfac_c_d_1_s_321
    m%dims(3) = o%f___f2dace_SA_wgtfac_c_d_2_s_322
    m%lbs(3) = o%f___f2dace_SOA_wgtfac_c_d_2_s_322
  END FUNCTION meta_t_nh_metrics_wgtfac_c

  PURE FUNCTION meta_t_nh_metrics_wgtfac_e(o) RESULT(m)
    TYPE(cm_t_nh_metrics), INTENT(IN) :: o
    TYPE(cm_meta) :: m
    m%rank = 3
    m%dims(1) = o%f___f2dace_SA_wgtfac_e_d_0_s_323
    m%lbs(1) = o%f___f2dace_SOA_wgtfac_e_d_0_s_323
    m%dims(2) = o%f___f2dace_SA_wgtfac_e_d_1_s_324
    m%lbs(2) = o%f___f2dace_SOA_wgtfac_e_d_1_s_324
    m%dims(3) = o%f___f2dace_SA_wgtfac_e_d_2_s_325
    m%lbs(3) = o%f___f2dace_SOA_wgtfac_e_d_2_s_325
  END FUNCTION meta_t_nh_metrics_wgtfac_e

  PURE FUNCTION meta_t_nh_metrics_wgtfacq_e(o) RESULT(m)
    TYPE(cm_t_nh_metrics), INTENT(IN) :: o
    TYPE(cm_meta) :: m
    m%rank = 3
    m%dims(1) = o%f___f2dace_SA_wgtfacq_e_d_0_s_326
    m%lbs(1) = o%f___f2dace_SOA_wgtfacq_e_d_0_s_326
    m%dims(2) = o%f___f2dace_SA_wgtfacq_e_d_1_s_327
    m%lbs(2) = o%f___f2dace_SOA_wgtfacq_e_d_1_s_327
    m%dims(3) = o%f___f2dace_SA_wgtfacq_e_d_2_s_328
    m%lbs(3) = o%f___f2dace_SOA_wgtfacq_e_d_2_s_328
  END FUNCTION meta_t_nh_metrics_wgtfacq_e

  PURE FUNCTION meta_t_grid_vertices_cell_blk(o) RESULT(m)
    TYPE(cm_t_grid_vertices), INTENT(IN) :: o
    TYPE(cm_meta) :: m
    m%rank = 3
    m%dims(1) = o%f___f2dace_SA_cell_blk_d_0_s_203
    m%lbs(1) = o%f___f2dace_SOA_cell_blk_d_0_s_203
    m%dims(2) = o%f___f2dace_SA_cell_blk_d_1_s_204
    m%lbs(2) = o%f___f2dace_SOA_cell_blk_d_1_s_204
    m%dims(3) = o%f___f2dace_SA_cell_blk_d_2_s_205
    m%lbs(3) = o%f___f2dace_SOA_cell_blk_d_2_s_205
  END FUNCTION meta_t_grid_vertices_cell_blk

  PURE FUNCTION meta_t_grid_vertices_cell_idx(o) RESULT(m)
    TYPE(cm_t_grid_vertices), INTENT(IN) :: o
    TYPE(cm_meta) :: m
    m%rank = 3
    m%dims(1) = o%f___f2dace_SA_cell_idx_d_0_s_200
    m%lbs(1) = o%f___f2dace_SOA_cell_idx_d_0_s_200
    m%dims(2) = o%f___f2dace_SA_cell_idx_d_1_s_201
    m%lbs(2) = o%f___f2dace_SOA_cell_idx_d_1_s_201
    m%dims(3) = o%f___f2dace_SA_cell_idx_d_2_s_202
    m%lbs(3) = o%f___f2dace_SOA_cell_idx_d_2_s_202
  END FUNCTION meta_t_grid_vertices_cell_idx

  PURE FUNCTION meta_t_grid_vertices_edge_blk(o) RESULT(m)
    TYPE(cm_t_grid_vertices), INTENT(IN) :: o
    TYPE(cm_meta) :: m
    m%rank = 3
    m%dims(1) = o%f___f2dace_SA_edge_blk_d_0_s_209
    m%lbs(1) = o%f___f2dace_SOA_edge_blk_d_0_s_209
    m%dims(2) = o%f___f2dace_SA_edge_blk_d_1_s_210
    m%lbs(2) = o%f___f2dace_SOA_edge_blk_d_1_s_210
    m%dims(3) = o%f___f2dace_SA_edge_blk_d_2_s_211
    m%lbs(3) = o%f___f2dace_SOA_edge_blk_d_2_s_211
  END FUNCTION meta_t_grid_vertices_edge_blk

  PURE FUNCTION meta_t_grid_vertices_edge_idx(o) RESULT(m)
    TYPE(cm_t_grid_vertices), INTENT(IN) :: o
    TYPE(cm_meta) :: m
    m%rank = 3
    m%dims(1) = o%f___f2dace_SA_edge_idx_d_0_s_206
    m%lbs(1) = o%f___f2dace_SOA_edge_idx_d_0_s_206
    m%dims(2) = o%f___f2dace_SA_edge_idx_d_1_s_207
    m%lbs(2) = o%f___f2dace_SOA_edge_idx_d_1_s_207
    m%dims(3) = o%f___f2dace_SA_edge_idx_d_2_s_208
    m%lbs(3) = o%f___f2dace_SOA_edge_idx_d_2_s_208
  END FUNCTION meta_t_grid_vertices_edge_idx

  PURE FUNCTION meta_t_grid_vertices_end_block(o) RESULT(m)
    TYPE(cm_t_grid_vertices), INTENT(IN) :: o
    TYPE(cm_meta) :: m
    m%rank = 1
    m%dims(1) = o%f___f2dace_SA_end_block_d_0_s_215
    m%lbs(1) = o%f___f2dace_SOA_end_block_d_0_s_215
  END FUNCTION meta_t_grid_vertices_end_block

  PURE FUNCTION meta_t_grid_vertices_end_index(o) RESULT(m)
    TYPE(cm_t_grid_vertices), INTENT(IN) :: o
    TYPE(cm_meta) :: m
    m%rank = 1
    m%dims(1) = o%f___f2dace_SA_end_index_d_0_s_213
    m%lbs(1) = o%f___f2dace_SOA_end_index_d_0_s_213
  END FUNCTION meta_t_grid_vertices_end_index

  PURE FUNCTION meta_t_grid_vertices_start_block(o) RESULT(m)
    TYPE(cm_t_grid_vertices), INTENT(IN) :: o
    TYPE(cm_meta) :: m
    m%rank = 1
    m%dims(1) = o%f___f2dace_SA_start_block_d_0_s_214
    m%lbs(1) = o%f___f2dace_SOA_start_block_d_0_s_214
  END FUNCTION meta_t_grid_vertices_start_block

  PURE FUNCTION meta_t_grid_vertices_start_index(o) RESULT(m)
    TYPE(cm_t_grid_vertices), INTENT(IN) :: o
    TYPE(cm_meta) :: m
    m%rank = 1
    m%dims(1) = o%f___f2dace_SA_start_index_d_0_s_212
    m%lbs(1) = o%f___f2dace_SOA_start_index_d_0_s_212
  END FUNCTION meta_t_grid_vertices_start_index

  PURE FUNCTION meta_t_nh_diag_ddt_vn_apc_pc(o) RESULT(m)
    TYPE(cm_t_nh_diag), INTENT(IN) :: o
    TYPE(cm_meta) :: m
    m%rank = 4
    m%dims(1) = o%f___f2dace_SA_ddt_vn_apc_pc_d_0_s_300
    m%lbs(1) = o%f___f2dace_SOA_ddt_vn_apc_pc_d_0_s_300
    m%dims(2) = o%f___f2dace_SA_ddt_vn_apc_pc_d_1_s_301
    m%lbs(2) = o%f___f2dace_SOA_ddt_vn_apc_pc_d_1_s_301
    m%dims(3) = o%f___f2dace_SA_ddt_vn_apc_pc_d_2_s_302
    m%lbs(3) = o%f___f2dace_SOA_ddt_vn_apc_pc_d_2_s_302
    m%dims(4) = o%f___f2dace_SA_ddt_vn_apc_pc_d_3_s_303
    m%lbs(4) = o%f___f2dace_SOA_ddt_vn_apc_pc_d_3_s_303
  END FUNCTION meta_t_nh_diag_ddt_vn_apc_pc

  PURE FUNCTION meta_t_nh_diag_ddt_w_adv_pc(o) RESULT(m)
    TYPE(cm_t_nh_diag), INTENT(IN) :: o
    TYPE(cm_meta) :: m
    m%rank = 4
    m%dims(1) = o%f___f2dace_SA_ddt_w_adv_pc_d_0_s_304
    m%lbs(1) = o%f___f2dace_SOA_ddt_w_adv_pc_d_0_s_304
    m%dims(2) = o%f___f2dace_SA_ddt_w_adv_pc_d_1_s_305
    m%lbs(2) = o%f___f2dace_SOA_ddt_w_adv_pc_d_1_s_305
    m%dims(3) = o%f___f2dace_SA_ddt_w_adv_pc_d_2_s_306
    m%lbs(3) = o%f___f2dace_SOA_ddt_w_adv_pc_d_2_s_306
    m%dims(4) = o%f___f2dace_SA_ddt_w_adv_pc_d_3_s_307
    m%lbs(4) = o%f___f2dace_SOA_ddt_w_adv_pc_d_3_s_307
  END FUNCTION meta_t_nh_diag_ddt_w_adv_pc

  PURE FUNCTION meta_t_nh_diag_vn_ie(o) RESULT(m)
    TYPE(cm_t_nh_diag), INTENT(IN) :: o
    TYPE(cm_meta) :: m
    m%rank = 3
    m%dims(1) = o%f___f2dace_SA_vn_ie_d_0_s_294
    m%lbs(1) = o%f___f2dace_SOA_vn_ie_d_0_s_294
    m%dims(2) = o%f___f2dace_SA_vn_ie_d_1_s_295
    m%lbs(2) = o%f___f2dace_SOA_vn_ie_d_1_s_295
    m%dims(3) = o%f___f2dace_SA_vn_ie_d_2_s_296
    m%lbs(3) = o%f___f2dace_SOA_vn_ie_d_2_s_296
  END FUNCTION meta_t_nh_diag_vn_ie

  PURE FUNCTION meta_t_nh_diag_vt(o) RESULT(m)
    TYPE(cm_t_nh_diag), INTENT(IN) :: o
    TYPE(cm_meta) :: m
    m%rank = 3
    m%dims(1) = o%f___f2dace_SA_vt_d_0_s_291
    m%lbs(1) = o%f___f2dace_SOA_vt_d_0_s_291
    m%dims(2) = o%f___f2dace_SA_vt_d_1_s_292
    m%lbs(2) = o%f___f2dace_SOA_vt_d_1_s_292
    m%dims(3) = o%f___f2dace_SA_vt_d_2_s_293
    m%lbs(3) = o%f___f2dace_SOA_vt_d_2_s_293
  END FUNCTION meta_t_nh_diag_vt

  PURE FUNCTION meta_t_nh_diag_w_concorr_c(o) RESULT(m)
    TYPE(cm_t_nh_diag), INTENT(IN) :: o
    TYPE(cm_meta) :: m
    m%rank = 3
    m%dims(1) = o%f___f2dace_SA_w_concorr_c_d_0_s_297
    m%lbs(1) = o%f___f2dace_SOA_w_concorr_c_d_0_s_297
    m%dims(2) = o%f___f2dace_SA_w_concorr_c_d_1_s_298
    m%lbs(2) = o%f___f2dace_SOA_w_concorr_c_d_1_s_298
    m%dims(3) = o%f___f2dace_SA_w_concorr_c_d_2_s_299
    m%lbs(3) = o%f___f2dace_SOA_w_concorr_c_d_2_s_299
  END FUNCTION meta_t_nh_diag_w_concorr_c

  !> Aborts unless every C++ sizeof matches its mirror; a shifted field would otherwise
  !> be read as silently wrong data rather than as a link or compile error.
  SUBROUTINE velocity_acc_check_sizes(n, sizes) BIND(C, name='velocity_acc_check_sizes')
    USE iso_fortran_env, ONLY: error_unit
    INTEGER(c_int), VALUE :: n
    INTEGER(c_size_t), INTENT(IN) :: sizes(n)
    INTEGER(c_size_t) :: mine(10)
    INTEGER :: i
    TYPE(cm_t_grid_edges) :: probe_t_grid_edges
    TYPE(cm_t_int_state) :: probe_t_int_state
    TYPE(cm_t_nh_prog) :: probe_t_nh_prog
    TYPE(cm_global_data_type) :: probe_global_data_type
    TYPE(cm_t_grid_domain_decomp_info) :: probe_t_grid_domain_decomp_info
    TYPE(cm_t_grid_cells) :: probe_t_grid_cells
    TYPE(cm_t_nh_metrics) :: probe_t_nh_metrics
    TYPE(cm_t_grid_vertices) :: probe_t_grid_vertices
    TYPE(cm_t_patch) :: probe_t_patch
    TYPE(cm_t_nh_diag) :: probe_t_nh_diag

    mine(1) = c_sizeof(probe_t_grid_edges)
    mine(2) = c_sizeof(probe_t_int_state)
    mine(3) = c_sizeof(probe_t_nh_prog)
    mine(4) = c_sizeof(probe_global_data_type)
    mine(5) = c_sizeof(probe_t_grid_domain_decomp_info)
    mine(6) = c_sizeof(probe_t_grid_cells)
    mine(7) = c_sizeof(probe_t_nh_metrics)
    mine(8) = c_sizeof(probe_t_grid_vertices)
    mine(9) = c_sizeof(probe_t_patch)
    mine(10) = c_sizeof(probe_t_nh_diag)

    IF (n /= SIZE(mine)) THEN
      WRITE (error_unit, '(A,I0,A,I0)') 'velocity_acc: struct count mismatch, C++ ', n, &
        ' vs Fortran ', SIZE(mine)
      STOP 1
    END IF
    DO i = 1, n
      IF (sizes(i) /= mine(i)) THEN
        WRITE (error_unit, '(A,I0,A,I0,A,I0)') 'velocity_acc: struct ', i, ' sizeof mismatch, C++ ', &
          sizes(i), ' vs Fortran ', mine(i)
        STOP 1
      END IF
    END DO
  END SUBROUTINE velocity_acc_check_sizes

END MODULE velocity_acc_mirror
