"""Minimal typing stub for the parts of ``fparser.two.utils`` that dace-fortran uses.

fparser ships neither annotations nor a ``py.typed`` marker, and its parse tree is built dynamically: ``parent``
and ``children`` are filled in by the parser and hold nodes, strings or ``None`` depending on the production, so
they are declared ``Any`` here, at the third-party boundary.
"""
from typing import Any, Iterable, Self, TypeVar, overload

T = TypeVar("T")

class FparserException(Exception): ...
class FortranSyntaxError(FparserException): ...
class NoMatchError(FparserException): ...
class InternalError(FparserException): ...

class Base:
    parent: Any
    children: Any
    string: Any
    item: Any
    items: Any
    content: Any
    def __new__(cls, *args: Any, **kwargs: Any) -> Self: ...
    def __init__(self, string: Any, parent_cls: Any = ...) -> None: ...
    def tofortran(self, tab: str = ..., isfix: bool | None = ...) -> str: ...
    def tostr(self) -> str: ...
    def torepr(self) -> str: ...
    def get_root(self) -> Base: ...
    def init(self, *args: Any) -> None: ...
    @classmethod
    def match(cls, string: Any) -> Any: ...

class BlockBase(Base): ...
class StmtBase(Base): ...
class NumberBase(Base): ...
class BinaryOpBase(Base): ...
class UnaryOpBase(Base): ...

@overload
def walk(node_list: Any, types: type[T], indent: int = ..., debug: bool = ...) -> list[T]: ...
@overload
def walk(node_list: Any, types: tuple[type[T], ...], indent: int = ..., debug: bool = ...) -> list[T]: ...
@overload
def walk(node_list: Any, types: Any = ..., indent: int = ..., debug: bool = ...) -> list[Any]: ...
