! AUTO-GENERATED by tests/icon/ocean/_monomorphize_solver.py -- do not edit.
! De-polymorphised ICON-O surface solver: the t_ocean_solve_backend factory
! lowered to a static type-tag if-ladder over its 7 concrete arms, and the
! t_transfer / t_lhs_agen axes retyped to their pinned concrete types.
! ZERO fir.dispatch remains -- static dataflow an SDFG can lower.
MODULE mo_ocean_solve
  USE mo_exception, ONLY: finish
  USE mo_kind, ONLY: wp
  USE mo_ocean_solve_lhs_type, ONLY: t_lhs_agen
  USE mo_ocean_solve_transfer, ONLY: t_transfer
  USE mo_ocean_solve_trivial_transfer, ONLY: t_trivial_transfer
  USE mo_ocean_solve_backend, ONLY: t_ocean_solve_backend
  USE mo_ocean_solve_gmres, ONLY: t_ocean_solve_gmres
  USE mo_ocean_solve_cg, ONLY: t_ocean_solve_cg
  USE mo_ocean_solve_cgo, ONLY: t_ocean_solve_cgo
  USE mo_ocean_solve_cgj, ONLY: t_ocean_solve_cgj
  USE mo_ocean_solve_bicgStab, ONLY: t_ocean_solve_bicgStab
  USE mo_ocean_solve_legacy_gmres, ONLY: t_ocean_solve_legacy_gmres
  USE mo_ocean_solve_mres, ONLY: t_ocean_solve_mres
  USE mo_ocean_solve_aux, ONLY: solve_gmres, solve_cg, solve_mres, solve_precon_jac, solve_cg_opt, solve_bcgs, solve_legacy_gmres, t_ocean_solve_parm
  USE mo_run_config, ONLY: ltimer
  USE mo_timer, ONLY: new_timer, timer_start, timer_stop
  USE mo_fortran_tools, ONLY: set_acc_host_or_device
  IMPLICIT NONE
  PRIVATE
  PUBLIC :: t_ocean_solve
  CHARACTER(LEN = *), PARAMETER :: this_mod_name = 'mo_ocean_solve'
  TYPE :: t_ocean_solve
    PRIVATE
    INTEGER :: act__tag = 0
    TYPE(t_ocean_solve_gmres), ALLOCATABLE :: act__t_ocean_solve_gmres
    TYPE(t_ocean_solve_cg), ALLOCATABLE :: act__t_ocean_solve_cg
    TYPE(t_ocean_solve_cgj), ALLOCATABLE :: act__t_ocean_solve_cgj
    TYPE(t_ocean_solve_cgo), ALLOCATABLE :: act__t_ocean_solve_cgo
    TYPE(t_ocean_solve_bicgstab), ALLOCATABLE :: act__t_ocean_solve_bicgstab
    TYPE(t_ocean_solve_mres), ALLOCATABLE :: act__t_ocean_solve_mres
    TYPE(t_ocean_solve_legacy_gmres), ALLOCATABLE :: act__t_ocean_solve_legacy_gmres
    REAL(KIND = wp), ALLOCATABLE, DIMENSION(:, :), PUBLIC :: x_loc_wp
    REAL(KIND = wp), POINTER, DIMENSION(:, :), PUBLIC :: b_loc_wp
    REAL(KIND = wp), ALLOCATABLE, DIMENSION(:), PUBLIC :: res_loc_wp
    INTEGER :: sol_type, timer, timer_init
    CHARACTER(LEN = 64), PUBLIC :: sol_type_name
    LOGICAL, PUBLIC :: is_init = .FALSE.
    CONTAINS
    PROCEDURE :: dump_matrix => ocean_solve_dump_matrix
    PROCEDURE :: construct => ocean_solve_construct
    PROCEDURE :: solve => ocean_solve_solve
  END TYPE t_ocean_solve
  CONTAINS
  SUBROUTINE ocean_solve_dump_matrix(this, id, lprecon_in, lacc)
    USE mo_ocean_solve_backend, ONLY: ocean_solve_backend_dump_matrix__t_ocean_solve_legacy_gmres
    USE mo_ocean_solve_backend, ONLY: ocean_solve_backend_dump_matrix__t_ocean_solve_mres
    USE mo_ocean_solve_backend, ONLY: ocean_solve_backend_dump_matrix__t_ocean_solve_bicgstab
    USE mo_ocean_solve_backend, ONLY: ocean_solve_backend_dump_matrix__t_ocean_solve_cgo
    USE mo_ocean_solve_backend, ONLY: ocean_solve_backend_dump_matrix__t_ocean_solve_cgj
    USE mo_ocean_solve_backend, ONLY: ocean_solve_backend_dump_matrix__t_ocean_solve_cg
    USE mo_ocean_solve_backend, ONLY: ocean_solve_backend_dump_matrix__t_ocean_solve_gmres
    CLASS(t_ocean_solve), INTENT(INOUT) :: this
    INTEGER, INTENT(IN) :: id
    LOGICAL, INTENT(IN), OPTIONAL :: lprecon_in
    LOGICAL, INTENT(IN), OPTIONAL :: lacc
    LOGICAL :: lprecon
    CHARACTER(LEN = *), PARAMETER :: routine = this_mod_name // "::t_ocean_solve::ocean_solve_dump_matrix()"
    LOGICAL :: lzacc
    CALL set_acc_host_or_device(lzacc, lacc)
    lprecon = .FALSE.
    IF (PRESENT(lprecon_in)) lprecon = lprecon_in
    IF (this % act__tag == 1) THEN
      CALL ocean_solve_backend_dump_matrix__t_ocean_solve_gmres(this % act__t_ocean_solve_gmres, id, lprecon, lacc = lzacc)
    ELSE IF (this % act__tag == 2) THEN
      CALL ocean_solve_backend_dump_matrix__t_ocean_solve_cg(this % act__t_ocean_solve_cg, id, lprecon, lacc = lzacc)
    ELSE IF (this % act__tag == 3) THEN
      CALL ocean_solve_backend_dump_matrix__t_ocean_solve_cgj(this % act__t_ocean_solve_cgj, id, lprecon, lacc = lzacc)
    ELSE IF (this % act__tag == 4) THEN
      CALL ocean_solve_backend_dump_matrix__t_ocean_solve_cgo(this % act__t_ocean_solve_cgo, id, lprecon, lacc = lzacc)
    ELSE IF (this % act__tag == 5) THEN
      CALL ocean_solve_backend_dump_matrix__t_ocean_solve_bicgstab(this % act__t_ocean_solve_bicgstab, id, lprecon, lacc = lzacc)
    ELSE IF (this % act__tag == 6) THEN
      CALL ocean_solve_backend_dump_matrix__t_ocean_solve_mres(this % act__t_ocean_solve_mres, id, lprecon, lacc = lzacc)
    ELSE IF (this % act__tag == 7) THEN
      CALL ocean_solve_backend_dump_matrix__t_ocean_solve_legacy_gmres(this % act__t_ocean_solve_legacy_gmres, id, lprecon, lacc = lzacc)
    END IF
  END SUBROUTINE ocean_solve_dump_matrix
  SUBROUTINE ocean_solve_construct(this, st, par, par_sp, lhs_agen, trans, lacc)
    USE mo_ocean_solve_backend, ONLY: ocean_solve_backend_construct__t_ocean_solve_legacy_gmres
    USE mo_ocean_solve_backend, ONLY: ocean_solve_backend_construct__t_ocean_solve_mres
    USE mo_ocean_solve_backend, ONLY: ocean_solve_backend_construct__t_ocean_solve_bicgstab
    USE mo_ocean_solve_backend, ONLY: ocean_solve_backend_construct__t_ocean_solve_cgo
    USE mo_ocean_solve_backend, ONLY: ocean_solve_backend_construct__t_ocean_solve_cgj
    USE mo_ocean_solve_backend, ONLY: ocean_solve_backend_construct__t_ocean_solve_cg
    USE mo_ocean_solve_backend, ONLY: ocean_solve_backend_construct__t_ocean_solve_gmres
    CLASS(t_ocean_solve), TARGET, INTENT(INOUT) :: this
    INTEGER, INTENT(IN) :: st
    TYPE(t_ocean_solve_parm), INTENT(IN) :: par, par_sp
    TYPE(t_primal_flip_flop_lhs), TARGET, INTENT(IN) :: lhs_agen
    TYPE(t_trivial_transfer), TARGET, INTENT(IN) :: trans
    LOGICAL, INTENT(IN), OPTIONAL :: lacc
    LOGICAL :: lzacc
    CHARACTER(LEN = *), PARAMETER :: routine = this_mod_name // "::t_ocean_solve::ocean_solve_construct()"
    CALL set_acc_host_or_device(lzacc, lacc)
    IF (this % act__tag /= 0) CALL finish(routine, "already initialized!")
    IF (ltimer) THEN
      this % timer_init = new_timer("solver init")
      CALL timer_start(this % timer_init)
    END IF
    IF (lzacc) THEN
      IF ((st /= solve_cg) .OR. (par % pt == solve_precon_jac)) THEN
        CALL finish(routine, "OpenACC version only implemented for CG solver without preconditioning")
      END IF
    END IF
    SELECT CASE (st)
    CASE (solve_gmres)
      this % timer = new_timer("gmres_solve")
      WRITE(this % sol_type_name, "(a)") "GMRES"
      this % act__tag = 1
      ALLOCATE(this % act__t_ocean_solve_gmres)
    CASE (solve_cg)
      SELECT CASE (par % pt)
      CASE (solve_precon_jac)
        this % timer = new_timer("cgj_solve")
        WRITE(this % sol_type_name, "(a)") "CG+JAC"
        this % act__tag = 3
        ALLOCATE(this % act__t_ocean_solve_cgj)
      CASE (solve_cg_opt)
        this % timer = new_timer("cg_solve")
        WRITE(this % sol_type_name, "(a)") "CG-OPT"
        this % act__tag = 4
        ALLOCATE(this % act__t_ocean_solve_cgo)
      CASE DEFAULT
        this % timer = new_timer("cg_solve")
        WRITE(this % sol_type_name, "(a)") "CG"
        this % act__tag = 2
        ALLOCATE(this % act__t_ocean_solve_cg)
      END SELECT
    CASE (solve_bcgs)
      this % timer = new_timer("bcgs_solve")
      WRITE(this % sol_type_name, "(a)") "BCGS"
      this % act__tag = 5
      ALLOCATE(this % act__t_ocean_solve_bicgstab)
    CASE (solve_legacy_gmres)
      this % timer = new_timer("leg_gmres_solve")
      SELECT TYPE(trans)
        CLASS IS (t_trivial_transfer)
        CLASS DEFAULT
        CALL finish(routine, "legacy_gmres must use trivial transfer infrastructure")
      END SELECT
      WRITE(this % sol_type_name, "(a)") "GMRES(legacy)"
      this % act__tag = 7
      ALLOCATE(this % act__t_ocean_solve_legacy_gmres)
    CASE (solve_mres)
      this % timer = new_timer("mres_solve")
      WRITE(this % sol_type_name, "(a)") "MINRES"
      this % act__tag = 6
      ALLOCATE(this % act__t_ocean_solve_mres)
    CASE DEFAULT
      CALL finish(routine, "unrecognized solver_type")
    END SELECT
    this % sol_type = st
    IF (this % act__tag == 1) THEN
      CALL ocean_solve_backend_construct__t_ocean_solve_gmres(this % act__t_ocean_solve_gmres, par, par_sp, lhs_agen, trans, lacc = lzacc)
    ELSE IF (this % act__tag == 2) THEN
      CALL ocean_solve_backend_construct__t_ocean_solve_cg(this % act__t_ocean_solve_cg, par, par_sp, lhs_agen, trans, lacc = lzacc)
    ELSE IF (this % act__tag == 3) THEN
      CALL ocean_solve_backend_construct__t_ocean_solve_cgj(this % act__t_ocean_solve_cgj, par, par_sp, lhs_agen, trans, lacc = lzacc)
    ELSE IF (this % act__tag == 4) THEN
      CALL ocean_solve_backend_construct__t_ocean_solve_cgo(this % act__t_ocean_solve_cgo, par, par_sp, lhs_agen, trans, lacc = lzacc)
    ELSE IF (this % act__tag == 5) THEN
      CALL ocean_solve_backend_construct__t_ocean_solve_bicgstab(this % act__t_ocean_solve_bicgstab, par, par_sp, lhs_agen, trans, lacc = lzacc)
    ELSE IF (this % act__tag == 6) THEN
      CALL ocean_solve_backend_construct__t_ocean_solve_mres(this % act__t_ocean_solve_mres, par, par_sp, lhs_agen, trans, lacc = lzacc)
    ELSE IF (this % act__tag == 7) THEN
      CALL ocean_solve_backend_construct__t_ocean_solve_legacy_gmres(this % act__t_ocean_solve_legacy_gmres, par, par_sp, lhs_agen, trans, lacc = lzacc)
    END IF
    NULLIFY(this % b_loc_wp)
    ALLOCATE(this % x_loc_wp(par % nidx, par % nblk_a), this % res_loc_wp(2))
    this % x_loc_wp(:, par % nblk_a) = 0._wp
    IF (this % act__tag == 1) THEN
      this % act__t_ocean_solve_gmres % res_loc_wp => this % res_loc_wp
    ELSE IF (this % act__tag == 2) THEN
      this % act__t_ocean_solve_cg % res_loc_wp => this % res_loc_wp
    ELSE IF (this % act__tag == 3) THEN
      this % act__t_ocean_solve_cgj % res_loc_wp => this % res_loc_wp
    ELSE IF (this % act__tag == 4) THEN
      this % act__t_ocean_solve_cgo % res_loc_wp => this % res_loc_wp
    ELSE IF (this % act__tag == 5) THEN
      this % act__t_ocean_solve_bicgstab % res_loc_wp => this % res_loc_wp
    ELSE IF (this % act__tag == 6) THEN
      this % act__t_ocean_solve_mres % res_loc_wp => this % res_loc_wp
    ELSE IF (this % act__tag == 7) THEN
      this % act__t_ocean_solve_legacy_gmres % res_loc_wp => this % res_loc_wp
    END IF
    IF (this % act__tag == 1) THEN
      this % act__t_ocean_solve_gmres % x_loc_wp => this % x_loc_wp
    ELSE IF (this % act__tag == 2) THEN
      this % act__t_ocean_solve_cg % x_loc_wp => this % x_loc_wp
    ELSE IF (this % act__tag == 3) THEN
      this % act__t_ocean_solve_cgj % x_loc_wp => this % x_loc_wp
    ELSE IF (this % act__tag == 4) THEN
      this % act__t_ocean_solve_cgo % x_loc_wp => this % x_loc_wp
    ELSE IF (this % act__tag == 5) THEN
      this % act__t_ocean_solve_bicgstab % x_loc_wp => this % x_loc_wp
    ELSE IF (this % act__tag == 6) THEN
      this % act__t_ocean_solve_mres % x_loc_wp => this % x_loc_wp
    ELSE IF (this % act__tag == 7) THEN
      this % act__t_ocean_solve_legacy_gmres % x_loc_wp => this % x_loc_wp
    END IF
    IF (ltimer) THEN
      CALL timer_stop(this % timer_init)
      IF (.NOT. trans % is_solver_pe) THEN
        CALL timer_start(this % timer)
        IF (this % act__tag == 1) THEN
          CALL timer_start(this % act__t_ocean_solve_gmres % lhs % timer)
        ELSE IF (this % act__tag == 2) THEN
          CALL timer_start(this % act__t_ocean_solve_cg % lhs % timer)
        ELSE IF (this % act__tag == 3) THEN
          CALL timer_start(this % act__t_ocean_solve_cgj % lhs % timer)
        ELSE IF (this % act__tag == 4) THEN
          CALL timer_start(this % act__t_ocean_solve_cgo % lhs % timer)
        ELSE IF (this % act__tag == 5) THEN
          CALL timer_start(this % act__t_ocean_solve_bicgstab % lhs % timer)
        ELSE IF (this % act__tag == 6) THEN
          CALL timer_start(this % act__t_ocean_solve_mres % lhs % timer)
        ELSE IF (this % act__tag == 7) THEN
          CALL timer_start(this % act__t_ocean_solve_legacy_gmres % lhs % timer)
        END IF
        IF (this % act__tag == 1) THEN
          CALL timer_stop(this % act__t_ocean_solve_gmres % lhs % timer)
        ELSE IF (this % act__tag == 2) THEN
          CALL timer_stop(this % act__t_ocean_solve_cg % lhs % timer)
        ELSE IF (this % act__tag == 3) THEN
          CALL timer_stop(this % act__t_ocean_solve_cgj % lhs % timer)
        ELSE IF (this % act__tag == 4) THEN
          CALL timer_stop(this % act__t_ocean_solve_cgo % lhs % timer)
        ELSE IF (this % act__tag == 5) THEN
          CALL timer_stop(this % act__t_ocean_solve_bicgstab % lhs % timer)
        ELSE IF (this % act__tag == 6) THEN
          CALL timer_stop(this % act__t_ocean_solve_mres % lhs % timer)
        ELSE IF (this % act__tag == 7) THEN
          CALL timer_stop(this % act__t_ocean_solve_legacy_gmres % lhs % timer)
        END IF
        CALL timer_start(trans % timer_glob_sum)
        CALL timer_stop(trans % timer_glob_sum)
        CALL timer_start(trans % timer_sync)
        CALL timer_stop(trans % timer_sync)
        CALL timer_stop(this % timer)
      END IF
    END IF
    this % is_init = .TRUE.
  END SUBROUTINE ocean_solve_construct
  SUBROUTINE ocean_solve_solve(this, niter, niter_sp, lacc)
    USE mo_ocean_solve_backend, ONLY: ocean_solve_backend_solve__t_ocean_solve_legacy_gmres
    USE mo_ocean_solve_backend, ONLY: ocean_solve_backend_solve__t_ocean_solve_mres
    USE mo_ocean_solve_backend, ONLY: ocean_solve_backend_solve__t_ocean_solve_bicgstab
    USE mo_ocean_solve_backend, ONLY: ocean_solve_backend_solve__t_ocean_solve_cgo
    USE mo_ocean_solve_backend, ONLY: ocean_solve_backend_solve__t_ocean_solve_cgj
    USE mo_ocean_solve_backend, ONLY: ocean_solve_backend_solve__t_ocean_solve_cg
    USE mo_ocean_solve_backend, ONLY: ocean_solve_backend_solve__t_ocean_solve_gmres
    CLASS(t_ocean_solve), INTENT(INOUT) :: this
    INTEGER, INTENT(OUT) :: niter, niter_sp
    LOGICAL, INTENT(IN), OPTIONAL :: lacc
    LOGICAL :: lzacc
    CHARACTER(LEN = *), PARAMETER :: routine = this_mod_name // '::t_ocean_solve::ocean_solve'
    CALL set_acc_host_or_device(lzacc, lacc)
    IF (.NOT. this % act__tag /= 0) CALL finish(routine, "solve needs to be initialized")
    IF (ltimer) CALL timer_start(this % timer)
    IF (this % act__tag == 1) THEN
      this % act__t_ocean_solve_gmres % b_loc_wp => this % b_loc_wp
    ELSE IF (this % act__tag == 2) THEN
      this % act__t_ocean_solve_cg % b_loc_wp => this % b_loc_wp
    ELSE IF (this % act__tag == 3) THEN
      this % act__t_ocean_solve_cgj % b_loc_wp => this % b_loc_wp
    ELSE IF (this % act__tag == 4) THEN
      this % act__t_ocean_solve_cgo % b_loc_wp => this % b_loc_wp
    ELSE IF (this % act__tag == 5) THEN
      this % act__t_ocean_solve_bicgstab % b_loc_wp => this % b_loc_wp
    ELSE IF (this % act__tag == 6) THEN
      this % act__t_ocean_solve_mres % b_loc_wp => this % b_loc_wp
    ELSE IF (this % act__tag == 7) THEN
      this % act__t_ocean_solve_legacy_gmres % b_loc_wp => this % b_loc_wp
    END IF
    IF (this % act__tag == 1) THEN
      CALL ocean_solve_backend_solve__t_ocean_solve_gmres(this % act__t_ocean_solve_gmres, niter, niter_sp, MERGE(1, 0, this % sol_type .NE. solve_legacy_gmres), lacc = lzacc)
    ELSE IF (this % act__tag == 2) THEN
      CALL ocean_solve_backend_solve__t_ocean_solve_cg(this % act__t_ocean_solve_cg, niter, niter_sp, MERGE(1, 0, this % sol_type .NE. solve_legacy_gmres), lacc = lzacc)
    ELSE IF (this % act__tag == 3) THEN
      CALL ocean_solve_backend_solve__t_ocean_solve_cgj(this % act__t_ocean_solve_cgj, niter, niter_sp, MERGE(1, 0, this % sol_type .NE. solve_legacy_gmres), lacc = lzacc)
    ELSE IF (this % act__tag == 4) THEN
      CALL ocean_solve_backend_solve__t_ocean_solve_cgo(this % act__t_ocean_solve_cgo, niter, niter_sp, MERGE(1, 0, this % sol_type .NE. solve_legacy_gmres), lacc = lzacc)
    ELSE IF (this % act__tag == 5) THEN
      CALL ocean_solve_backend_solve__t_ocean_solve_bicgstab(this % act__t_ocean_solve_bicgstab, niter, niter_sp, MERGE(1, 0, this % sol_type .NE. solve_legacy_gmres), lacc = lzacc)
    ELSE IF (this % act__tag == 6) THEN
      CALL ocean_solve_backend_solve__t_ocean_solve_mres(this % act__t_ocean_solve_mres, niter, niter_sp, MERGE(1, 0, this % sol_type .NE. solve_legacy_gmres), lacc = lzacc)
    ELSE IF (this % act__tag == 7) THEN
      CALL ocean_solve_backend_solve__t_ocean_solve_legacy_gmres(this % act__t_ocean_solve_legacy_gmres, niter, niter_sp, MERGE(1, 0, this % sol_type .NE. solve_legacy_gmres), lacc = lzacc)
    END IF
    IF (ltimer) CALL timer_stop(this % timer)
  END SUBROUTINE ocean_solve_solve
END MODULE mo_ocean_solve
MODULE mo_ocean_solve_backend
  USE mo_exception, ONLY: finish
  USE mo_kind, ONLY: sp, wp
  USE mo_mpi, ONLY: p_barrier, p_comm_work
  USE mo_ocean_solve_lhs, ONLY: t_lhs
  USE mo_ocean_solve_lhs_type, ONLY: t_lhs_agen
  USE mo_ocean_solve_transfer, ONLY: t_transfer
  USE mo_ocean_solve_aux, ONLY: t_ocean_solve_parm
  USE mo_timer, ONLY: timer_start, timer_stop, new_timer
  USE mo_run_config, ONLY: ltimer
  USE mo_fortran_tools, ONLY: set_acc_host_or_device
  IMPLICIT NONE
  PRIVATE
  PUBLIC :: t_ocean_solve_backend
  CHARACTER(LEN = *), PARAMETER :: this_mod_name = 'mo_ocean_solve_backend'
  TYPE, ABSTRACT :: t_ocean_solve_backend
    INTEGER :: timer_wait
    TYPE(t_ocean_solve_parm) :: par, par_sp
    TYPE(t_lhs) :: lhs
    TYPE(t_trivial_transfer), POINTER :: trans => NULL()
    REAL(KIND = wp) :: abs_tol_wp, abs_tol_sp
    REAL(KIND = sp), ALLOCATABLE, DIMENSION(:, :) :: x_sp, b_sp
    REAL(KIND = wp), ALLOCATABLE, DIMENSION(:, :) :: x_wp, b_wp
    REAL(KIND = wp), ALLOCATABLE, DIMENSION(:) :: res_wp
    REAL(KIND = wp), POINTER, DIMENSION(:, :) :: x_loc_wp, b_loc_wp
    REAL(KIND = wp), POINTER, DIMENSION(:) :: res_loc_wp
    INTEGER, ALLOCATABLE, DIMENSION(:) :: niter
    INTEGER, ALLOCATABLE, DIMENSION(:) :: niter_cal
    CONTAINS
    PROCEDURE :: dump_matrix => ocean_solve_backend_dump_matrix
    PROCEDURE :: construct => ocean_solve_backend_construct
    PROCEDURE(a_solve_backend_wp), DEFERRED :: doit_wp
    PROCEDURE(a_solve_backend_sp), DEFERRED :: doit_sp
  END TYPE t_ocean_solve_backend
  ABSTRACT INTERFACE
    SUBROUTINE a_solve_backend_wp(this, lacc)
      IMPORT :: t_ocean_solve_backend
      CLASS(t_ocean_solve_backend), INTENT(INOUT) :: this
      LOGICAL, INTENT(IN), OPTIONAL :: lacc
    END SUBROUTINE a_solve_backend_wp
    SUBROUTINE a_solve_backend_sp(this)
      IMPORT :: t_ocean_solve_backend
      CLASS(t_ocean_solve_backend), INTENT(INOUT) :: this
    END SUBROUTINE a_solve_backend_sp
  END INTERFACE
  CONTAINS
  SUBROUTINE ocean_solve_backend_dump_matrix(this, id, lprecon, lacc)
    CLASS(t_ocean_solve_backend), INTENT(INOUT) :: this
    INTEGER, INTENT(IN) :: id
    LOGICAL, INTENT(IN) :: lprecon
    LOGICAL, INTENT(IN), OPTIONAL :: lacc
    CHARACTER(LEN = *), PARAMETER :: routine = this_mod_name // "::ocean_solve_t::ocean_solve_dump_matrix()"
    LOGICAL :: lzacc
    CALL set_acc_host_or_device(lzacc, lacc)
    IF (.NOT. ASSOCIATED(this % trans)) CALL finish(routine, "ocean_solve_t was not initialized")
    IF (lprecon) THEN
      CALL this % lhs % dump_matrix(id, "ocean_matrix_precon_", .TRUE., lacc = lzacc)
    ELSE
      CALL this % lhs % dump_matrix(id, "ocean_matrix_lhs_", .FALSE., lacc = lzacc)
    END IF
  END SUBROUTINE ocean_solve_backend_dump_matrix
  SUBROUTINE ocean_solve_backend_construct(this, par, par_sp, lhs_agen, trans, lacc)
    CLASS(t_ocean_solve_backend), INTENT(INOUT) :: this
    TYPE(t_ocean_solve_parm), INTENT(IN) :: par, par_sp
    TYPE(t_primal_flip_flop_lhs), TARGET, INTENT(IN) :: lhs_agen
    TYPE(t_trivial_transfer), TARGET, INTENT(IN) :: trans
    LOGICAL, INTENT(IN), OPTIONAL :: lacc
    LOGICAL :: lzacc
    CHARACTER(LEN = *), PARAMETER :: routine = this_mod_name // "::ocean_solve_t::ocean_solve_backend_construct()"
    CALL set_acc_host_or_device(lzacc, lacc)
    IF (ASSOCIATED(this % trans)) CALL finish(routine, "already initialized!")
    this % par = par
    this % par_sp = par_sp
    this % abs_tol_wp = par % tol
    IF (par_sp % nidx .NE. - 1) this % abs_tol_sp = REAL(par_sp % tol, sp)
    NULLIFY(this % b_loc_wp)
    ALLOCATE(this % niter(2), this % niter_cal(2), this % res_wp(2))
    this % trans => trans
    CALL this % lhs % construct(par_sp % nidx .EQ. par % nidx, par, lhs_agen, trans, lacc = lzacc)
    this % timer_wait = new_timer("solve_wait")
  END SUBROUTINE ocean_solve_backend_construct
  SUBROUTINE ocean_solve_backend_dump_matrix__t_ocean_solve_gmres(this, id, lprecon, lacc)
    TYPE(t_ocean_solve_gmres), INTENT(INOUT) :: this
    INTEGER, INTENT(IN) :: id
    LOGICAL, INTENT(IN) :: lprecon
    LOGICAL, INTENT(IN), OPTIONAL :: lacc
    CHARACTER(LEN = *), PARAMETER :: routine = this_mod_name // "::ocean_solve_t::ocean_solve_dump_matrix()"
    LOGICAL :: lzacc
    CALL set_acc_host_or_device(lzacc, lacc)
    IF (.NOT. ASSOCIATED(this % trans)) CALL finish(routine, "ocean_solve_t was not initialized")
    IF (lprecon) THEN
      CALL this % lhs % dump_matrix(id, "ocean_matrix_precon_", .TRUE., lacc = lzacc)
    ELSE
      CALL this % lhs % dump_matrix(id, "ocean_matrix_lhs_", .FALSE., lacc = lzacc)
    END IF
  END SUBROUTINE ocean_solve_backend_dump_matrix__t_ocean_solve_gmres
  SUBROUTINE ocean_solve_backend_dump_matrix__t_ocean_solve_cg(this, id, lprecon, lacc)
    TYPE(t_ocean_solve_cg), INTENT(INOUT) :: this
    INTEGER, INTENT(IN) :: id
    LOGICAL, INTENT(IN) :: lprecon
    LOGICAL, INTENT(IN), OPTIONAL :: lacc
    CHARACTER(LEN = *), PARAMETER :: routine = this_mod_name // "::ocean_solve_t::ocean_solve_dump_matrix()"
    LOGICAL :: lzacc
    CALL set_acc_host_or_device(lzacc, lacc)
    IF (.NOT. ASSOCIATED(this % trans)) CALL finish(routine, "ocean_solve_t was not initialized")
    IF (lprecon) THEN
      CALL this % lhs % dump_matrix(id, "ocean_matrix_precon_", .TRUE., lacc = lzacc)
    ELSE
      CALL this % lhs % dump_matrix(id, "ocean_matrix_lhs_", .FALSE., lacc = lzacc)
    END IF
  END SUBROUTINE ocean_solve_backend_dump_matrix__t_ocean_solve_cg
  SUBROUTINE ocean_solve_backend_dump_matrix__t_ocean_solve_cgj(this, id, lprecon, lacc)
    TYPE(t_ocean_solve_cgj), INTENT(INOUT) :: this
    INTEGER, INTENT(IN) :: id
    LOGICAL, INTENT(IN) :: lprecon
    LOGICAL, INTENT(IN), OPTIONAL :: lacc
    CHARACTER(LEN = *), PARAMETER :: routine = this_mod_name // "::ocean_solve_t::ocean_solve_dump_matrix()"
    LOGICAL :: lzacc
    CALL set_acc_host_or_device(lzacc, lacc)
    IF (.NOT. ASSOCIATED(this % trans)) CALL finish(routine, "ocean_solve_t was not initialized")
    IF (lprecon) THEN
      CALL this % lhs % dump_matrix(id, "ocean_matrix_precon_", .TRUE., lacc = lzacc)
    ELSE
      CALL this % lhs % dump_matrix(id, "ocean_matrix_lhs_", .FALSE., lacc = lzacc)
    END IF
  END SUBROUTINE ocean_solve_backend_dump_matrix__t_ocean_solve_cgj
  SUBROUTINE ocean_solve_backend_dump_matrix__t_ocean_solve_cgo(this, id, lprecon, lacc)
    TYPE(t_ocean_solve_cgo), INTENT(INOUT) :: this
    INTEGER, INTENT(IN) :: id
    LOGICAL, INTENT(IN) :: lprecon
    LOGICAL, INTENT(IN), OPTIONAL :: lacc
    CHARACTER(LEN = *), PARAMETER :: routine = this_mod_name // "::ocean_solve_t::ocean_solve_dump_matrix()"
    LOGICAL :: lzacc
    CALL set_acc_host_or_device(lzacc, lacc)
    IF (.NOT. ASSOCIATED(this % trans)) CALL finish(routine, "ocean_solve_t was not initialized")
    IF (lprecon) THEN
      CALL this % lhs % dump_matrix(id, "ocean_matrix_precon_", .TRUE., lacc = lzacc)
    ELSE
      CALL this % lhs % dump_matrix(id, "ocean_matrix_lhs_", .FALSE., lacc = lzacc)
    END IF
  END SUBROUTINE ocean_solve_backend_dump_matrix__t_ocean_solve_cgo
  SUBROUTINE ocean_solve_backend_dump_matrix__t_ocean_solve_bicgstab(this, id, lprecon, lacc)
    TYPE(t_ocean_solve_bicgstab), INTENT(INOUT) :: this
    INTEGER, INTENT(IN) :: id
    LOGICAL, INTENT(IN) :: lprecon
    LOGICAL, INTENT(IN), OPTIONAL :: lacc
    CHARACTER(LEN = *), PARAMETER :: routine = this_mod_name // "::ocean_solve_t::ocean_solve_dump_matrix()"
    LOGICAL :: lzacc
    CALL set_acc_host_or_device(lzacc, lacc)
    IF (.NOT. ASSOCIATED(this % trans)) CALL finish(routine, "ocean_solve_t was not initialized")
    IF (lprecon) THEN
      CALL this % lhs % dump_matrix(id, "ocean_matrix_precon_", .TRUE., lacc = lzacc)
    ELSE
      CALL this % lhs % dump_matrix(id, "ocean_matrix_lhs_", .FALSE., lacc = lzacc)
    END IF
  END SUBROUTINE ocean_solve_backend_dump_matrix__t_ocean_solve_bicgstab
  SUBROUTINE ocean_solve_backend_dump_matrix__t_ocean_solve_mres(this, id, lprecon, lacc)
    TYPE(t_ocean_solve_mres), INTENT(INOUT) :: this
    INTEGER, INTENT(IN) :: id
    LOGICAL, INTENT(IN) :: lprecon
    LOGICAL, INTENT(IN), OPTIONAL :: lacc
    CHARACTER(LEN = *), PARAMETER :: routine = this_mod_name // "::ocean_solve_t::ocean_solve_dump_matrix()"
    LOGICAL :: lzacc
    CALL set_acc_host_or_device(lzacc, lacc)
    IF (.NOT. ASSOCIATED(this % trans)) CALL finish(routine, "ocean_solve_t was not initialized")
    IF (lprecon) THEN
      CALL this % lhs % dump_matrix(id, "ocean_matrix_precon_", .TRUE., lacc = lzacc)
    ELSE
      CALL this % lhs % dump_matrix(id, "ocean_matrix_lhs_", .FALSE., lacc = lzacc)
    END IF
  END SUBROUTINE ocean_solve_backend_dump_matrix__t_ocean_solve_mres
  SUBROUTINE ocean_solve_backend_dump_matrix__t_ocean_solve_legacy_gmres(this, id, lprecon, lacc)
    TYPE(t_ocean_solve_legacy_gmres), INTENT(INOUT) :: this
    INTEGER, INTENT(IN) :: id
    LOGICAL, INTENT(IN) :: lprecon
    LOGICAL, INTENT(IN), OPTIONAL :: lacc
    CHARACTER(LEN = *), PARAMETER :: routine = this_mod_name // "::ocean_solve_t::ocean_solve_dump_matrix()"
    LOGICAL :: lzacc
    CALL set_acc_host_or_device(lzacc, lacc)
    IF (.NOT. ASSOCIATED(this % trans)) CALL finish(routine, "ocean_solve_t was not initialized")
    IF (lprecon) THEN
      CALL this % lhs % dump_matrix(id, "ocean_matrix_precon_", .TRUE., lacc = lzacc)
    ELSE
      CALL this % lhs % dump_matrix(id, "ocean_matrix_lhs_", .FALSE., lacc = lzacc)
    END IF
  END SUBROUTINE ocean_solve_backend_dump_matrix__t_ocean_solve_legacy_gmres
  SUBROUTINE ocean_solve_backend_construct__t_ocean_solve_gmres(this, par, par_sp, lhs_agen, trans, lacc)
    TYPE(t_ocean_solve_gmres), INTENT(INOUT) :: this
    TYPE(t_ocean_solve_parm), INTENT(IN) :: par, par_sp
    TYPE(t_primal_flip_flop_lhs), TARGET, INTENT(IN) :: lhs_agen
    TYPE(t_trivial_transfer), TARGET, INTENT(IN) :: trans
    LOGICAL, INTENT(IN), OPTIONAL :: lacc
    LOGICAL :: lzacc
    CHARACTER(LEN = *), PARAMETER :: routine = this_mod_name // "::ocean_solve_t::ocean_solve_backend_construct__t_ocean_solve_gmres()"
    CALL set_acc_host_or_device(lzacc, lacc)
    IF (ASSOCIATED(this % trans)) CALL finish(routine, "already initialized!")
    this % par = par
    this % par_sp = par_sp
    this % abs_tol_wp = par % tol
    IF (par_sp % nidx .NE. - 1) this % abs_tol_sp = REAL(par_sp % tol, sp)
    NULLIFY(this % b_loc_wp)
    ALLOCATE(this % niter(2), this % niter_cal(2), this % res_wp(2))
    this % trans => trans
    CALL this % lhs % construct(par_sp % nidx .EQ. par % nidx, par, lhs_agen, trans, lacc = lzacc)
    this % timer_wait = new_timer("solve_wait")
  END SUBROUTINE ocean_solve_backend_construct__t_ocean_solve_gmres
  SUBROUTINE ocean_solve_backend_construct__t_ocean_solve_cg(this, par, par_sp, lhs_agen, trans, lacc)
    TYPE(t_ocean_solve_cg), INTENT(INOUT) :: this
    TYPE(t_ocean_solve_parm), INTENT(IN) :: par, par_sp
    TYPE(t_primal_flip_flop_lhs), TARGET, INTENT(IN) :: lhs_agen
    TYPE(t_trivial_transfer), TARGET, INTENT(IN) :: trans
    LOGICAL, INTENT(IN), OPTIONAL :: lacc
    LOGICAL :: lzacc
    CHARACTER(LEN = *), PARAMETER :: routine = this_mod_name // "::ocean_solve_t::ocean_solve_backend_construct__t_ocean_solve_cg()"
    CALL set_acc_host_or_device(lzacc, lacc)
    IF (ASSOCIATED(this % trans)) CALL finish(routine, "already initialized!")
    this % par = par
    this % par_sp = par_sp
    this % abs_tol_wp = par % tol
    IF (par_sp % nidx .NE. - 1) this % abs_tol_sp = REAL(par_sp % tol, sp)
    NULLIFY(this % b_loc_wp)
    ALLOCATE(this % niter(2), this % niter_cal(2), this % res_wp(2))
    this % trans => trans
    CALL this % lhs % construct(par_sp % nidx .EQ. par % nidx, par, lhs_agen, trans, lacc = lzacc)
    this % timer_wait = new_timer("solve_wait")
  END SUBROUTINE ocean_solve_backend_construct__t_ocean_solve_cg
  SUBROUTINE ocean_solve_backend_construct__t_ocean_solve_cgj(this, par, par_sp, lhs_agen, trans, lacc)
    TYPE(t_ocean_solve_cgj), INTENT(INOUT) :: this
    TYPE(t_ocean_solve_parm), INTENT(IN) :: par, par_sp
    TYPE(t_primal_flip_flop_lhs), TARGET, INTENT(IN) :: lhs_agen
    TYPE(t_trivial_transfer), TARGET, INTENT(IN) :: trans
    LOGICAL, INTENT(IN), OPTIONAL :: lacc
    LOGICAL :: lzacc
    CHARACTER(LEN = *), PARAMETER :: routine = this_mod_name // "::ocean_solve_t::ocean_solve_backend_construct__t_ocean_solve_cgj()"
    CALL set_acc_host_or_device(lzacc, lacc)
    IF (ASSOCIATED(this % trans)) CALL finish(routine, "already initialized!")
    this % par = par
    this % par_sp = par_sp
    this % abs_tol_wp = par % tol
    IF (par_sp % nidx .NE. - 1) this % abs_tol_sp = REAL(par_sp % tol, sp)
    NULLIFY(this % b_loc_wp)
    ALLOCATE(this % niter(2), this % niter_cal(2), this % res_wp(2))
    this % trans => trans
    CALL this % lhs % construct(par_sp % nidx .EQ. par % nidx, par, lhs_agen, trans, lacc = lzacc)
    this % timer_wait = new_timer("solve_wait")
  END SUBROUTINE ocean_solve_backend_construct__t_ocean_solve_cgj
  SUBROUTINE ocean_solve_backend_construct__t_ocean_solve_cgo(this, par, par_sp, lhs_agen, trans, lacc)
    TYPE(t_ocean_solve_cgo), INTENT(INOUT) :: this
    TYPE(t_ocean_solve_parm), INTENT(IN) :: par, par_sp
    TYPE(t_primal_flip_flop_lhs), TARGET, INTENT(IN) :: lhs_agen
    TYPE(t_trivial_transfer), TARGET, INTENT(IN) :: trans
    LOGICAL, INTENT(IN), OPTIONAL :: lacc
    LOGICAL :: lzacc
    CHARACTER(LEN = *), PARAMETER :: routine = this_mod_name // "::ocean_solve_t::ocean_solve_backend_construct__t_ocean_solve_cgo()"
    CALL set_acc_host_or_device(lzacc, lacc)
    IF (ASSOCIATED(this % trans)) CALL finish(routine, "already initialized!")
    this % par = par
    this % par_sp = par_sp
    this % abs_tol_wp = par % tol
    IF (par_sp % nidx .NE. - 1) this % abs_tol_sp = REAL(par_sp % tol, sp)
    NULLIFY(this % b_loc_wp)
    ALLOCATE(this % niter(2), this % niter_cal(2), this % res_wp(2))
    this % trans => trans
    CALL this % lhs % construct(par_sp % nidx .EQ. par % nidx, par, lhs_agen, trans, lacc = lzacc)
    this % timer_wait = new_timer("solve_wait")
  END SUBROUTINE ocean_solve_backend_construct__t_ocean_solve_cgo
  SUBROUTINE ocean_solve_backend_construct__t_ocean_solve_bicgstab(this, par, par_sp, lhs_agen, trans, lacc)
    TYPE(t_ocean_solve_bicgstab), INTENT(INOUT) :: this
    TYPE(t_ocean_solve_parm), INTENT(IN) :: par, par_sp
    TYPE(t_primal_flip_flop_lhs), TARGET, INTENT(IN) :: lhs_agen
    TYPE(t_trivial_transfer), TARGET, INTENT(IN) :: trans
    LOGICAL, INTENT(IN), OPTIONAL :: lacc
    LOGICAL :: lzacc
    CHARACTER(LEN = *), PARAMETER :: routine = this_mod_name // "::ocean_solve_t::ocean_solve_backend_construct__t_ocean_solve_bicgstab()"
    CALL set_acc_host_or_device(lzacc, lacc)
    IF (ASSOCIATED(this % trans)) CALL finish(routine, "already initialized!")
    this % par = par
    this % par_sp = par_sp
    this % abs_tol_wp = par % tol
    IF (par_sp % nidx .NE. - 1) this % abs_tol_sp = REAL(par_sp % tol, sp)
    NULLIFY(this % b_loc_wp)
    ALLOCATE(this % niter(2), this % niter_cal(2), this % res_wp(2))
    this % trans => trans
    CALL this % lhs % construct(par_sp % nidx .EQ. par % nidx, par, lhs_agen, trans, lacc = lzacc)
    this % timer_wait = new_timer("solve_wait")
  END SUBROUTINE ocean_solve_backend_construct__t_ocean_solve_bicgstab
  SUBROUTINE ocean_solve_backend_construct__t_ocean_solve_mres(this, par, par_sp, lhs_agen, trans, lacc)
    TYPE(t_ocean_solve_mres), INTENT(INOUT) :: this
    TYPE(t_ocean_solve_parm), INTENT(IN) :: par, par_sp
    TYPE(t_primal_flip_flop_lhs), TARGET, INTENT(IN) :: lhs_agen
    TYPE(t_trivial_transfer), TARGET, INTENT(IN) :: trans
    LOGICAL, INTENT(IN), OPTIONAL :: lacc
    LOGICAL :: lzacc
    CHARACTER(LEN = *), PARAMETER :: routine = this_mod_name // "::ocean_solve_t::ocean_solve_backend_construct__t_ocean_solve_mres()"
    CALL set_acc_host_or_device(lzacc, lacc)
    IF (ASSOCIATED(this % trans)) CALL finish(routine, "already initialized!")
    this % par = par
    this % par_sp = par_sp
    this % abs_tol_wp = par % tol
    IF (par_sp % nidx .NE. - 1) this % abs_tol_sp = REAL(par_sp % tol, sp)
    NULLIFY(this % b_loc_wp)
    ALLOCATE(this % niter(2), this % niter_cal(2), this % res_wp(2))
    this % trans => trans
    CALL this % lhs % construct(par_sp % nidx .EQ. par % nidx, par, lhs_agen, trans, lacc = lzacc)
    this % timer_wait = new_timer("solve_wait")
  END SUBROUTINE ocean_solve_backend_construct__t_ocean_solve_mres
  SUBROUTINE ocean_solve_backend_construct__t_ocean_solve_legacy_gmres(this, par, par_sp, lhs_agen, trans, lacc)
    TYPE(t_ocean_solve_legacy_gmres), INTENT(INOUT) :: this
    TYPE(t_ocean_solve_parm), INTENT(IN) :: par, par_sp
    TYPE(t_primal_flip_flop_lhs), TARGET, INTENT(IN) :: lhs_agen
    TYPE(t_trivial_transfer), TARGET, INTENT(IN) :: trans
    LOGICAL, INTENT(IN), OPTIONAL :: lacc
    LOGICAL :: lzacc
    CHARACTER(LEN = *), PARAMETER :: routine = this_mod_name // "::ocean_solve_t::ocean_solve_backend_construct__t_ocean_solve_legacy_gmres()"
    CALL set_acc_host_or_device(lzacc, lacc)
    IF (ASSOCIATED(this % trans)) CALL finish(routine, "already initialized!")
    this % par = par
    this % par_sp = par_sp
    this % abs_tol_wp = par % tol
    IF (par_sp % nidx .NE. - 1) this % abs_tol_sp = REAL(par_sp % tol, sp)
    NULLIFY(this % b_loc_wp)
    ALLOCATE(this % niter(2), this % niter_cal(2), this % res_wp(2))
    this % trans => trans
    CALL this % lhs % construct(par_sp % nidx .EQ. par % nidx, par, lhs_agen, trans, lacc = lzacc)
    this % timer_wait = new_timer("solve_wait")
  END SUBROUTINE ocean_solve_backend_construct__t_ocean_solve_legacy_gmres
  SUBROUTINE ocean_solve_backend_solve__t_ocean_solve_gmres(this, niter, niter_sp, upd, lacc)
    TYPE(t_ocean_solve_gmres), INTENT(INOUT) :: this
    INTEGER, INTENT(OUT) :: niter, niter_sp
    INTEGER, INTENT(IN) :: upd
    LOGICAL, INTENT(IN), OPTIONAL :: lacc
    CHARACTER(LEN = *), PARAMETER :: routine = this_mod_name // '::ocean_solve_t::ocean_solve'
    INTEGER :: sum_it, n_re, n_it
    LOGICAL :: lzacc
    CALL set_acc_host_or_device(lzacc, lacc)
    IF (.NOT. ASSOCIATED(this % trans)) CALL finish(routine, "solve needs to be initialized")
    IF (upd .EQ. 1) CALL this % lhs % update(lacc = lzacc)
    IF (.NOT. ALLOCATED(this % x_wp)) THEN
      CALL this % trans % into_once(this % x_loc_wp, this % x_wp, 1, lacc = lzacc)
      CALL this % trans % into_once(this % b_loc_wp, this % b_wp, 1, lacc = lzacc)
    ELSE
      CALL this % trans % into(this % x_loc_wp, this % x_wp, this % b_loc_wp, this % b_wp, 1, lacc = lzacc)
    END IF
    this % niter_cal(2) = - 2
    IF (this % par_sp % nidx .EQ. this % par % nidx .AND. this % trans % is_solver_pe) THEN
      IF (lzacc) CALL finish(routine, "Single precision variant not ported to GPU")
      IF (.NOT. ALLOCATED(this % x_sp)) ALLOCATE(this % x_sp(this % trans % nidx, this % trans % nblk_a), this % b_sp(this % trans % nidx, this % trans % nblk_a))
      this % x_sp(:, :) = REAL(this % x_wp(:, :), sp)
      this % b_sp(:, :) = REAL(this % b_wp(:, :), sp)
      sum_it = 0
      n_re = 0
      n_it = - 1
      DO WHILE (n_it .EQ. - 1 .AND. n_re .LT. this % par_sp % nr)
        CALL this % doit_sp
        n_it = this % niter_cal(2)
        sum_it = sum_it + MERGE(n_it, this % par_sp % m, n_it .GT. - 1)
        IF (this % abs_tol_sp .LT. this % res_wp(2)) n_it = - 1
        n_re = n_re + 1
      END DO
      this % niter_cal(2) = sum_it
      this % x_wp(:, :) = REAL(this % x_sp(:, :), wp)
    END IF
    IF (this % trans % is_solver_pe) THEN
      sum_it = 0
      n_re = 0
      n_it = - 1
      DO WHILE (n_it .EQ. - 1 .AND. n_re .LT. this % par % nr)
        CALL this % doit_wp(lacc = lzacc)
        n_it = this % niter_cal(1)
        sum_it = sum_it + MERGE(n_it, this % par % m, n_it .GT. - 1)
        IF (this % abs_tol_wp .LT. this % res_wp(1)) n_it = - 1
        n_re = n_re + 1
      END DO
      this % niter_cal(1) = sum_it
    END IF
    IF (ltimer) CALL timer_start(this % timer_wait)
    IF (ltimer) CALL p_barrier(p_comm_work)
    IF (ltimer) CALL timer_stop(this % timer_wait)
    CALL this % trans % sctr(this % x_wp, this % x_loc_wp, lacc = lzacc)
    CALL this % trans % bcst(this % res_wp, this % res_loc_wp, lacc = .FALSE.)
    CALL this % trans % bcst(this % niter_cal, this % niter, lacc = .FALSE.)
    niter = this % niter(1)
    niter_sp = this % niter(2)
  END SUBROUTINE ocean_solve_backend_solve__t_ocean_solve_gmres
  SUBROUTINE ocean_solve_backend_solve__t_ocean_solve_cg(this, niter, niter_sp, upd, lacc)
    TYPE(t_ocean_solve_cg), INTENT(INOUT) :: this
    INTEGER, INTENT(OUT) :: niter, niter_sp
    INTEGER, INTENT(IN) :: upd
    LOGICAL, INTENT(IN), OPTIONAL :: lacc
    CHARACTER(LEN = *), PARAMETER :: routine = this_mod_name // '::ocean_solve_t::ocean_solve'
    INTEGER :: sum_it, n_re, n_it
    LOGICAL :: lzacc
    CALL set_acc_host_or_device(lzacc, lacc)
    IF (.NOT. ASSOCIATED(this % trans)) CALL finish(routine, "solve needs to be initialized")
    IF (upd .EQ. 1) CALL this % lhs % update(lacc = lzacc)
    IF (.NOT. ALLOCATED(this % x_wp)) THEN
      CALL this % trans % into_once(this % x_loc_wp, this % x_wp, 1, lacc = lzacc)
      CALL this % trans % into_once(this % b_loc_wp, this % b_wp, 1, lacc = lzacc)
    ELSE
      CALL this % trans % into(this % x_loc_wp, this % x_wp, this % b_loc_wp, this % b_wp, 1, lacc = lzacc)
    END IF
    this % niter_cal(2) = - 2
    IF (this % par_sp % nidx .EQ. this % par % nidx .AND. this % trans % is_solver_pe) THEN
      IF (lzacc) CALL finish(routine, "Single precision variant not ported to GPU")
      IF (.NOT. ALLOCATED(this % x_sp)) ALLOCATE(this % x_sp(this % trans % nidx, this % trans % nblk_a), this % b_sp(this % trans % nidx, this % trans % nblk_a))
      this % x_sp(:, :) = REAL(this % x_wp(:, :), sp)
      this % b_sp(:, :) = REAL(this % b_wp(:, :), sp)
      sum_it = 0
      n_re = 0
      n_it = - 1
      DO WHILE (n_it .EQ. - 1 .AND. n_re .LT. this % par_sp % nr)
        CALL this % doit_sp
        n_it = this % niter_cal(2)
        sum_it = sum_it + MERGE(n_it, this % par_sp % m, n_it .GT. - 1)
        IF (this % abs_tol_sp .LT. this % res_wp(2)) n_it = - 1
        n_re = n_re + 1
      END DO
      this % niter_cal(2) = sum_it
      this % x_wp(:, :) = REAL(this % x_sp(:, :), wp)
    END IF
    IF (this % trans % is_solver_pe) THEN
      sum_it = 0
      n_re = 0
      n_it = - 1
      DO WHILE (n_it .EQ. - 1 .AND. n_re .LT. this % par % nr)
        CALL this % doit_wp(lacc = lzacc)
        n_it = this % niter_cal(1)
        sum_it = sum_it + MERGE(n_it, this % par % m, n_it .GT. - 1)
        IF (this % abs_tol_wp .LT. this % res_wp(1)) n_it = - 1
        n_re = n_re + 1
      END DO
      this % niter_cal(1) = sum_it
    END IF
    IF (ltimer) CALL timer_start(this % timer_wait)
    IF (ltimer) CALL p_barrier(p_comm_work)
    IF (ltimer) CALL timer_stop(this % timer_wait)
    CALL this % trans % sctr(this % x_wp, this % x_loc_wp, lacc = lzacc)
    CALL this % trans % bcst(this % res_wp, this % res_loc_wp, lacc = .FALSE.)
    CALL this % trans % bcst(this % niter_cal, this % niter, lacc = .FALSE.)
    niter = this % niter(1)
    niter_sp = this % niter(2)
  END SUBROUTINE ocean_solve_backend_solve__t_ocean_solve_cg
  SUBROUTINE ocean_solve_backend_solve__t_ocean_solve_cgj(this, niter, niter_sp, upd, lacc)
    TYPE(t_ocean_solve_cgj), INTENT(INOUT) :: this
    INTEGER, INTENT(OUT) :: niter, niter_sp
    INTEGER, INTENT(IN) :: upd
    LOGICAL, INTENT(IN), OPTIONAL :: lacc
    CHARACTER(LEN = *), PARAMETER :: routine = this_mod_name // '::ocean_solve_t::ocean_solve'
    INTEGER :: sum_it, n_re, n_it
    LOGICAL :: lzacc
    CALL set_acc_host_or_device(lzacc, lacc)
    IF (.NOT. ASSOCIATED(this % trans)) CALL finish(routine, "solve needs to be initialized")
    IF (upd .EQ. 1) CALL this % lhs % update(lacc = lzacc)
    IF (.NOT. ALLOCATED(this % x_wp)) THEN
      CALL this % trans % into_once(this % x_loc_wp, this % x_wp, 1, lacc = lzacc)
      CALL this % trans % into_once(this % b_loc_wp, this % b_wp, 1, lacc = lzacc)
    ELSE
      CALL this % trans % into(this % x_loc_wp, this % x_wp, this % b_loc_wp, this % b_wp, 1, lacc = lzacc)
    END IF
    this % niter_cal(2) = - 2
    IF (this % par_sp % nidx .EQ. this % par % nidx .AND. this % trans % is_solver_pe) THEN
      IF (lzacc) CALL finish(routine, "Single precision variant not ported to GPU")
      IF (.NOT. ALLOCATED(this % x_sp)) ALLOCATE(this % x_sp(this % trans % nidx, this % trans % nblk_a), this % b_sp(this % trans % nidx, this % trans % nblk_a))
      this % x_sp(:, :) = REAL(this % x_wp(:, :), sp)
      this % b_sp(:, :) = REAL(this % b_wp(:, :), sp)
      sum_it = 0
      n_re = 0
      n_it = - 1
      DO WHILE (n_it .EQ. - 1 .AND. n_re .LT. this % par_sp % nr)
        CALL this % doit_sp
        n_it = this % niter_cal(2)
        sum_it = sum_it + MERGE(n_it, this % par_sp % m, n_it .GT. - 1)
        IF (this % abs_tol_sp .LT. this % res_wp(2)) n_it = - 1
        n_re = n_re + 1
      END DO
      this % niter_cal(2) = sum_it
      this % x_wp(:, :) = REAL(this % x_sp(:, :), wp)
    END IF
    IF (this % trans % is_solver_pe) THEN
      sum_it = 0
      n_re = 0
      n_it = - 1
      DO WHILE (n_it .EQ. - 1 .AND. n_re .LT. this % par % nr)
        CALL this % doit_wp(lacc = lzacc)
        n_it = this % niter_cal(1)
        sum_it = sum_it + MERGE(n_it, this % par % m, n_it .GT. - 1)
        IF (this % abs_tol_wp .LT. this % res_wp(1)) n_it = - 1
        n_re = n_re + 1
      END DO
      this % niter_cal(1) = sum_it
    END IF
    IF (ltimer) CALL timer_start(this % timer_wait)
    IF (ltimer) CALL p_barrier(p_comm_work)
    IF (ltimer) CALL timer_stop(this % timer_wait)
    CALL this % trans % sctr(this % x_wp, this % x_loc_wp, lacc = lzacc)
    CALL this % trans % bcst(this % res_wp, this % res_loc_wp, lacc = .FALSE.)
    CALL this % trans % bcst(this % niter_cal, this % niter, lacc = .FALSE.)
    niter = this % niter(1)
    niter_sp = this % niter(2)
  END SUBROUTINE ocean_solve_backend_solve__t_ocean_solve_cgj
  SUBROUTINE ocean_solve_backend_solve__t_ocean_solve_cgo(this, niter, niter_sp, upd, lacc)
    TYPE(t_ocean_solve_cgo), INTENT(INOUT) :: this
    INTEGER, INTENT(OUT) :: niter, niter_sp
    INTEGER, INTENT(IN) :: upd
    LOGICAL, INTENT(IN), OPTIONAL :: lacc
    CHARACTER(LEN = *), PARAMETER :: routine = this_mod_name // '::ocean_solve_t::ocean_solve'
    INTEGER :: sum_it, n_re, n_it
    LOGICAL :: lzacc
    CALL set_acc_host_or_device(lzacc, lacc)
    IF (.NOT. ASSOCIATED(this % trans)) CALL finish(routine, "solve needs to be initialized")
    IF (upd .EQ. 1) CALL this % lhs % update(lacc = lzacc)
    IF (.NOT. ALLOCATED(this % x_wp)) THEN
      CALL this % trans % into_once(this % x_loc_wp, this % x_wp, 1, lacc = lzacc)
      CALL this % trans % into_once(this % b_loc_wp, this % b_wp, 1, lacc = lzacc)
    ELSE
      CALL this % trans % into(this % x_loc_wp, this % x_wp, this % b_loc_wp, this % b_wp, 1, lacc = lzacc)
    END IF
    this % niter_cal(2) = - 2
    IF (this % par_sp % nidx .EQ. this % par % nidx .AND. this % trans % is_solver_pe) THEN
      IF (lzacc) CALL finish(routine, "Single precision variant not ported to GPU")
      IF (.NOT. ALLOCATED(this % x_sp)) ALLOCATE(this % x_sp(this % trans % nidx, this % trans % nblk_a), this % b_sp(this % trans % nidx, this % trans % nblk_a))
      this % x_sp(:, :) = REAL(this % x_wp(:, :), sp)
      this % b_sp(:, :) = REAL(this % b_wp(:, :), sp)
      sum_it = 0
      n_re = 0
      n_it = - 1
      DO WHILE (n_it .EQ. - 1 .AND. n_re .LT. this % par_sp % nr)
        CALL this % doit_sp
        n_it = this % niter_cal(2)
        sum_it = sum_it + MERGE(n_it, this % par_sp % m, n_it .GT. - 1)
        IF (this % abs_tol_sp .LT. this % res_wp(2)) n_it = - 1
        n_re = n_re + 1
      END DO
      this % niter_cal(2) = sum_it
      this % x_wp(:, :) = REAL(this % x_sp(:, :), wp)
    END IF
    IF (this % trans % is_solver_pe) THEN
      sum_it = 0
      n_re = 0
      n_it = - 1
      DO WHILE (n_it .EQ. - 1 .AND. n_re .LT. this % par % nr)
        CALL this % doit_wp(lacc = lzacc)
        n_it = this % niter_cal(1)
        sum_it = sum_it + MERGE(n_it, this % par % m, n_it .GT. - 1)
        IF (this % abs_tol_wp .LT. this % res_wp(1)) n_it = - 1
        n_re = n_re + 1
      END DO
      this % niter_cal(1) = sum_it
    END IF
    IF (ltimer) CALL timer_start(this % timer_wait)
    IF (ltimer) CALL p_barrier(p_comm_work)
    IF (ltimer) CALL timer_stop(this % timer_wait)
    CALL this % trans % sctr(this % x_wp, this % x_loc_wp, lacc = lzacc)
    CALL this % trans % bcst(this % res_wp, this % res_loc_wp, lacc = .FALSE.)
    CALL this % trans % bcst(this % niter_cal, this % niter, lacc = .FALSE.)
    niter = this % niter(1)
    niter_sp = this % niter(2)
  END SUBROUTINE ocean_solve_backend_solve__t_ocean_solve_cgo
  SUBROUTINE ocean_solve_backend_solve__t_ocean_solve_bicgstab(this, niter, niter_sp, upd, lacc)
    TYPE(t_ocean_solve_bicgstab), INTENT(INOUT) :: this
    INTEGER, INTENT(OUT) :: niter, niter_sp
    INTEGER, INTENT(IN) :: upd
    LOGICAL, INTENT(IN), OPTIONAL :: lacc
    CHARACTER(LEN = *), PARAMETER :: routine = this_mod_name // '::ocean_solve_t::ocean_solve'
    INTEGER :: sum_it, n_re, n_it
    LOGICAL :: lzacc
    CALL set_acc_host_or_device(lzacc, lacc)
    IF (.NOT. ASSOCIATED(this % trans)) CALL finish(routine, "solve needs to be initialized")
    IF (upd .EQ. 1) CALL this % lhs % update(lacc = lzacc)
    IF (.NOT. ALLOCATED(this % x_wp)) THEN
      CALL this % trans % into_once(this % x_loc_wp, this % x_wp, 1, lacc = lzacc)
      CALL this % trans % into_once(this % b_loc_wp, this % b_wp, 1, lacc = lzacc)
    ELSE
      CALL this % trans % into(this % x_loc_wp, this % x_wp, this % b_loc_wp, this % b_wp, 1, lacc = lzacc)
    END IF
    this % niter_cal(2) = - 2
    IF (this % par_sp % nidx .EQ. this % par % nidx .AND. this % trans % is_solver_pe) THEN
      IF (lzacc) CALL finish(routine, "Single precision variant not ported to GPU")
      IF (.NOT. ALLOCATED(this % x_sp)) ALLOCATE(this % x_sp(this % trans % nidx, this % trans % nblk_a), this % b_sp(this % trans % nidx, this % trans % nblk_a))
      this % x_sp(:, :) = REAL(this % x_wp(:, :), sp)
      this % b_sp(:, :) = REAL(this % b_wp(:, :), sp)
      sum_it = 0
      n_re = 0
      n_it = - 1
      DO WHILE (n_it .EQ. - 1 .AND. n_re .LT. this % par_sp % nr)
        CALL this % doit_sp
        n_it = this % niter_cal(2)
        sum_it = sum_it + MERGE(n_it, this % par_sp % m, n_it .GT. - 1)
        IF (this % abs_tol_sp .LT. this % res_wp(2)) n_it = - 1
        n_re = n_re + 1
      END DO
      this % niter_cal(2) = sum_it
      this % x_wp(:, :) = REAL(this % x_sp(:, :), wp)
    END IF
    IF (this % trans % is_solver_pe) THEN
      sum_it = 0
      n_re = 0
      n_it = - 1
      DO WHILE (n_it .EQ. - 1 .AND. n_re .LT. this % par % nr)
        CALL this % doit_wp(lacc = lzacc)
        n_it = this % niter_cal(1)
        sum_it = sum_it + MERGE(n_it, this % par % m, n_it .GT. - 1)
        IF (this % abs_tol_wp .LT. this % res_wp(1)) n_it = - 1
        n_re = n_re + 1
      END DO
      this % niter_cal(1) = sum_it
    END IF
    IF (ltimer) CALL timer_start(this % timer_wait)
    IF (ltimer) CALL p_barrier(p_comm_work)
    IF (ltimer) CALL timer_stop(this % timer_wait)
    CALL this % trans % sctr(this % x_wp, this % x_loc_wp, lacc = lzacc)
    CALL this % trans % bcst(this % res_wp, this % res_loc_wp, lacc = .FALSE.)
    CALL this % trans % bcst(this % niter_cal, this % niter, lacc = .FALSE.)
    niter = this % niter(1)
    niter_sp = this % niter(2)
  END SUBROUTINE ocean_solve_backend_solve__t_ocean_solve_bicgstab
  SUBROUTINE ocean_solve_backend_solve__t_ocean_solve_mres(this, niter, niter_sp, upd, lacc)
    TYPE(t_ocean_solve_mres), INTENT(INOUT) :: this
    INTEGER, INTENT(OUT) :: niter, niter_sp
    INTEGER, INTENT(IN) :: upd
    LOGICAL, INTENT(IN), OPTIONAL :: lacc
    CHARACTER(LEN = *), PARAMETER :: routine = this_mod_name // '::ocean_solve_t::ocean_solve'
    INTEGER :: sum_it, n_re, n_it
    LOGICAL :: lzacc
    CALL set_acc_host_or_device(lzacc, lacc)
    IF (.NOT. ASSOCIATED(this % trans)) CALL finish(routine, "solve needs to be initialized")
    IF (upd .EQ. 1) CALL this % lhs % update(lacc = lzacc)
    IF (.NOT. ALLOCATED(this % x_wp)) THEN
      CALL this % trans % into_once(this % x_loc_wp, this % x_wp, 1, lacc = lzacc)
      CALL this % trans % into_once(this % b_loc_wp, this % b_wp, 1, lacc = lzacc)
    ELSE
      CALL this % trans % into(this % x_loc_wp, this % x_wp, this % b_loc_wp, this % b_wp, 1, lacc = lzacc)
    END IF
    this % niter_cal(2) = - 2
    IF (this % par_sp % nidx .EQ. this % par % nidx .AND. this % trans % is_solver_pe) THEN
      IF (lzacc) CALL finish(routine, "Single precision variant not ported to GPU")
      IF (.NOT. ALLOCATED(this % x_sp)) ALLOCATE(this % x_sp(this % trans % nidx, this % trans % nblk_a), this % b_sp(this % trans % nidx, this % trans % nblk_a))
      this % x_sp(:, :) = REAL(this % x_wp(:, :), sp)
      this % b_sp(:, :) = REAL(this % b_wp(:, :), sp)
      sum_it = 0
      n_re = 0
      n_it = - 1
      DO WHILE (n_it .EQ. - 1 .AND. n_re .LT. this % par_sp % nr)
        CALL this % doit_sp
        n_it = this % niter_cal(2)
        sum_it = sum_it + MERGE(n_it, this % par_sp % m, n_it .GT. - 1)
        IF (this % abs_tol_sp .LT. this % res_wp(2)) n_it = - 1
        n_re = n_re + 1
      END DO
      this % niter_cal(2) = sum_it
      this % x_wp(:, :) = REAL(this % x_sp(:, :), wp)
    END IF
    IF (this % trans % is_solver_pe) THEN
      sum_it = 0
      n_re = 0
      n_it = - 1
      DO WHILE (n_it .EQ. - 1 .AND. n_re .LT. this % par % nr)
        CALL this % doit_wp(lacc = lzacc)
        n_it = this % niter_cal(1)
        sum_it = sum_it + MERGE(n_it, this % par % m, n_it .GT. - 1)
        IF (this % abs_tol_wp .LT. this % res_wp(1)) n_it = - 1
        n_re = n_re + 1
      END DO
      this % niter_cal(1) = sum_it
    END IF
    IF (ltimer) CALL timer_start(this % timer_wait)
    IF (ltimer) CALL p_barrier(p_comm_work)
    IF (ltimer) CALL timer_stop(this % timer_wait)
    CALL this % trans % sctr(this % x_wp, this % x_loc_wp, lacc = lzacc)
    CALL this % trans % bcst(this % res_wp, this % res_loc_wp, lacc = .FALSE.)
    CALL this % trans % bcst(this % niter_cal, this % niter, lacc = .FALSE.)
    niter = this % niter(1)
    niter_sp = this % niter(2)
  END SUBROUTINE ocean_solve_backend_solve__t_ocean_solve_mres
  SUBROUTINE ocean_solve_backend_solve__t_ocean_solve_legacy_gmres(this, niter, niter_sp, upd, lacc)
    TYPE(t_ocean_solve_legacy_gmres), INTENT(INOUT) :: this
    INTEGER, INTENT(OUT) :: niter, niter_sp
    INTEGER, INTENT(IN) :: upd
    LOGICAL, INTENT(IN), OPTIONAL :: lacc
    CHARACTER(LEN = *), PARAMETER :: routine = this_mod_name // '::ocean_solve_t::ocean_solve'
    INTEGER :: sum_it, n_re, n_it
    LOGICAL :: lzacc
    CALL set_acc_host_or_device(lzacc, lacc)
    IF (.NOT. ASSOCIATED(this % trans)) CALL finish(routine, "solve needs to be initialized")
    IF (upd .EQ. 1) CALL this % lhs % update(lacc = lzacc)
    IF (.NOT. ALLOCATED(this % x_wp)) THEN
      CALL this % trans % into_once(this % x_loc_wp, this % x_wp, 1, lacc = lzacc)
      CALL this % trans % into_once(this % b_loc_wp, this % b_wp, 1, lacc = lzacc)
    ELSE
      CALL this % trans % into(this % x_loc_wp, this % x_wp, this % b_loc_wp, this % b_wp, 1, lacc = lzacc)
    END IF
    this % niter_cal(2) = - 2
    IF (this % par_sp % nidx .EQ. this % par % nidx .AND. this % trans % is_solver_pe) THEN
      IF (lzacc) CALL finish(routine, "Single precision variant not ported to GPU")
      IF (.NOT. ALLOCATED(this % x_sp)) ALLOCATE(this % x_sp(this % trans % nidx, this % trans % nblk_a), this % b_sp(this % trans % nidx, this % trans % nblk_a))
      this % x_sp(:, :) = REAL(this % x_wp(:, :), sp)
      this % b_sp(:, :) = REAL(this % b_wp(:, :), sp)
      sum_it = 0
      n_re = 0
      n_it = - 1
      DO WHILE (n_it .EQ. - 1 .AND. n_re .LT. this % par_sp % nr)
        CALL this % doit_sp
        n_it = this % niter_cal(2)
        sum_it = sum_it + MERGE(n_it, this % par_sp % m, n_it .GT. - 1)
        IF (this % abs_tol_sp .LT. this % res_wp(2)) n_it = - 1
        n_re = n_re + 1
      END DO
      this % niter_cal(2) = sum_it
      this % x_wp(:, :) = REAL(this % x_sp(:, :), wp)
    END IF
    IF (this % trans % is_solver_pe) THEN
      sum_it = 0
      n_re = 0
      n_it = - 1
      DO WHILE (n_it .EQ. - 1 .AND. n_re .LT. this % par % nr)
        CALL this % doit_wp(lacc = lzacc)
        n_it = this % niter_cal(1)
        sum_it = sum_it + MERGE(n_it, this % par % m, n_it .GT. - 1)
        IF (this % abs_tol_wp .LT. this % res_wp(1)) n_it = - 1
        n_re = n_re + 1
      END DO
      this % niter_cal(1) = sum_it
    END IF
    IF (ltimer) CALL timer_start(this % timer_wait)
    IF (ltimer) CALL p_barrier(p_comm_work)
    IF (ltimer) CALL timer_stop(this % timer_wait)
    CALL this % trans % sctr(this % x_wp, this % x_loc_wp, lacc = lzacc)
    CALL this % trans % bcst(this % res_wp, this % res_loc_wp, lacc = .FALSE.)
    CALL this % trans % bcst(this % niter_cal, this % niter, lacc = .FALSE.)
    niter = this % niter(1)
    niter_sp = this % niter(2)
  END SUBROUTINE ocean_solve_backend_solve__t_ocean_solve_legacy_gmres
END MODULE mo_ocean_solve_backend
MODULE zz_icon_typedefs
  TYPE, EXTENDS(t_ocean_solve_backend) :: t_ocean_solve_gmres
    PRIVATE
    REAL(KIND = sp), ALLOCATABLE, DIMENSION(:, :, :) :: v_sp
    REAL(KIND = sp), ALLOCATABLE, DIMENSION(:, :) :: w_sp, z_sp, h_sp
    REAL(KIND = sp), ALLOCATABLE, DIMENSION(:) :: s_sp, c_sp, res_t_sp
    REAL(KIND = wp), ALLOCATABLE, DIMENSION(:, :, :) :: v_wp
    REAL(KIND = wp), ALLOCATABLE, DIMENSION(:, :) :: w_wp, z_wp, h_wp
    REAL(KIND = wp), ALLOCATABLE, DIMENSION(:) :: s_wp, c_wp, res_t_wp
    CONTAINS
    PROCEDURE :: doit_wp => ocean_solve_gmres_cal_wp
    PROCEDURE :: doit_sp => ocean_solve_gmres_cal_sp
    PROCEDURE, PRIVATE :: recover_arrays_wp => ocean_solve_gmres_recover_arrays_wp
    PROCEDURE, PRIVATE :: recover_arrays_sp => ocean_solve_gmres_recover_arrays_sp
    GENERIC, PRIVATE :: recover_arrays => recover_arrays_wp, recover_arrays_sp
  END TYPE t_ocean_solve_gmres
  TYPE, EXTENDS(t_ocean_solve_backend) :: t_ocean_solve_cg
    PRIVATE
    REAL(KIND = wp), ALLOCATABLE, DIMENSION(:, :) :: z_wp, d_wp, r_wp, rsq_wp
    REAL(KIND = sp), ALLOCATABLE, DIMENSION(:, :) :: z_sp, d_sp, r_sp, rsq_sp
    CONTAINS
    PROCEDURE :: doit_wp => ocean_solve_cg_cal_wp
    PROCEDURE :: doit_sp => ocean_solve_cg_cal_sp
    PROCEDURE, PRIVATE :: recover_arrays_wp => ocean_solve_cg_recover_arrays_wp
    PROCEDURE, PRIVATE :: recover_arrays_sp => ocean_solve_cg_recover_arrays_sp
    GENERIC, PRIVATE :: recover_arrays => recover_arrays_wp, recover_arrays_sp
  END TYPE t_ocean_solve_cg
  TYPE, EXTENDS(t_ocean_solve_backend) :: t_ocean_solve_cgj
    PRIVATE
    REAL(KIND = wp), ALLOCATABLE, DIMENSION(:, :) :: z_wp, d_wp, r1_wp, rsq_wp, h_wp
    CONTAINS
    PROCEDURE :: doit_wp => ocean_solve_cgj_cal_wp
    PROCEDURE :: doit_sp => ocean_solve_cgj_cal_sp
    PROCEDURE, PRIVATE :: recover_arrays_wp => ocean_solve_cgj_recover_arrays_wp
    GENERIC, PRIVATE :: recover_arrays => recover_arrays_wp
  END TYPE t_ocean_solve_cgj
  TYPE, EXTENDS(t_ocean_solve_backend) :: t_ocean_solve_cgo
    PRIVATE
    REAL(KIND = wp), ALLOCATABLE, DIMENSION(:, :) :: z_wp, d_wp, r_wp, rsq_wp
    REAL(KIND = sp), ALLOCATABLE, DIMENSION(:, :) :: z_sp, d_sp, r_sp, rsq_sp
    REAL(KIND = wp), ALLOCATABLE, DIMENSION(:, :) :: s_wp, rs_wp
    REAL(KIND = sp), ALLOCATABLE, DIMENSION(:, :) :: s_sp, rs_sp
    CONTAINS
    PROCEDURE :: doit_wp => ocean_solve_cgo_cal_wp
    PROCEDURE :: doit_sp => ocean_solve_cgo_cal_sp
    PROCEDURE, PRIVATE :: recover_arrays_wp => ocean_solve_cgo_recover_arrays_wp
    PROCEDURE, PRIVATE :: recover_arrays_sp => ocean_solve_cgo_recover_arrays_sp
    GENERIC, PRIVATE :: recover_arrays => recover_arrays_wp, recover_arrays_sp
  END TYPE t_ocean_solve_cgo
  TYPE, EXTENDS(t_ocean_solve_backend) :: t_ocean_solve_bicgStab
    PRIVATE
    REAL(KIND = wp), ALLOCATABLE, DIMENSION(:, :) :: r0_wp, r_wp, v_wp, p_wp, ta1_wp, s_wp, ta2_wp
    CONTAINS
    PROCEDURE :: doit_wp => ocean_solve_bicgStab_cal_wp
    PROCEDURE :: doit_sp => ocean_solve_bicgStab_cal_sp
    PROCEDURE, PRIVATE :: recover_arrays_wp => ocean_solve_bicgStab_recover_arrays_wp
    GENERIC, PRIVATE :: recover_arrays => recover_arrays_wp
  END TYPE t_ocean_solve_bicgStab
  TYPE, EXTENDS(t_ocean_solve_backend) :: t_ocean_solve_mres
    PRIVATE
    REAL(KIND = wp), ALLOCATABLE, DIMENSION(:, :) :: p0_wp, p1_wp, p2_wp, s0_wp, s1_wp, s2_wp, r_wp, ss_wp, rs_wp
    CONTAINS
    PROCEDURE :: doit_wp => ocean_solve_mres_cal_wp
    PROCEDURE :: doit_sp => ocean_solve_mres_cal_sp
    PROCEDURE, PRIVATE :: recover_arrays_wp => ocean_solve_mres_recover_arrays_wp
    GENERIC, PRIVATE :: recover_arrays => recover_arrays_wp
  END TYPE t_ocean_solve_mres
  TYPE, EXTENDS(t_ocean_solve_backend) :: t_ocean_solve_legacy_gmres
    PRIVATE
    CONTAINS
    PROCEDURE :: doit_wp => ocean_solve_legacy_gmres_cal_wp
    PROCEDURE :: doit_sp => ocean_solve_legacy_gmres_cal_sp
  END TYPE t_ocean_solve_legacy_gmres
  TYPE, ABSTRACT :: t_transfer
    PRIVATE
    INTEGER, PUBLIC :: comm, nblk_a, nblk, nidx, nidx_e, nidx_l, ngid_a_l
    INTEGER, PUBLIC :: timer_sync, timer_in(4), timer_out, timer_glob_sum, timer_init
    LOGICAL, PUBLIC :: is_solver_pe, is_leader_pe
    LOGICAL, PUBLIC :: is_init = .FALSE.
    INTEGER, POINTER, DIMENSION(:), PUBLIC :: glb_idx_loc => NULL(), glb_idx_cal => NULL()
    CONTAINS
    PROCEDURE(a_trans_into_2d_wp), DEFERRED :: into_2d_wp
    PROCEDURE(a_trans_into_2d_wp_2), DEFERRED :: into_2d_wp_2
    PROCEDURE(a_trans_into_3d_wp), DEFERRED :: into_3d_wp
    PROCEDURE(a_trans_into_idx), DEFERRED :: into_idx
    GENERIC, PUBLIC :: into => into_2d_wp, into_2d_wp_2, into_3d_wp, into_idx
    PROCEDURE(a_trans_into_once_2d_wp), DEFERRED :: into_once_2d_wp
    PROCEDURE(a_trans_into_once_3d_wp), DEFERRED :: into_once_3d_wp
    PROCEDURE(a_trans_into_once_idx), DEFERRED :: into_once_idx
    GENERIC, PUBLIC :: into_once => into_once_2d_wp, into_once_3d_wp, into_once_idx
    PROCEDURE(a_trans_out_2d_wp), DEFERRED :: out_2d_wp
    GENERIC, PUBLIC :: sctr => out_2d_wp
    PROCEDURE(a_trans_bcst_1d_wp), DEFERRED :: bcst_1d_wp
    PROCEDURE(a_trans_bcst_1d_i), DEFERRED :: bcst_1d_i
    GENERIC, PUBLIC :: bcst => bcst_1d_wp, bcst_1d_i
    PROCEDURE(a_trans_sync_2d_wp), DEFERRED :: sync_2d_wp
    PROCEDURE(a_trans_sync_2d_sp), DEFERRED :: sync_2d_sp
    GENERIC, PUBLIC :: sync => sync_2d_wp, sync_2d_sp
    PROCEDURE, PRIVATE :: gs_2d_1dp => ocean_solve_transfer_global_sum_2d_dp_1
    PROCEDURE, PRIVATE :: gs_2d_2dp => ocean_solve_transfer_global_sum_2d_dp_2
    PROCEDURE, PRIVATE :: gs_2d_3dp => ocean_solve_transfer_global_sum_2d_dp_3
    PROCEDURE, PRIVATE :: gs_2d_1sp => ocean_solve_transfer_global_sum_2d_sp_1
    PROCEDURE, PRIVATE :: gs_2d_2sp => ocean_solve_transfer_global_sum_2d_sp_2
    PROCEDURE, PRIVATE :: gs_2d_3sp => ocean_solve_transfer_global_sum_2d_sp_3
    GENERIC, PUBLIC :: global_sum => gs_2d_1dp, gs_2d_1sp, gs_2d_2dp, gs_2d_2sp, gs_2d_3dp, gs_2d_3sp
    PROCEDURE, PRIVATE :: gs_2d_ndp => ocean_solve_transfer_global_sum_2d_dp
    PROCEDURE, PRIVATE :: gs_2d_nsp => ocean_solve_transfer_global_sum_2d_sp
    GENERIC, PRIVATE :: global_sum_internal => gs_2d_ndp, gs_2d_nsp
    PROCEDURE :: globalID_loc => ocean_solve_transfer_globalID_loc
    PROCEDURE :: globalID_cal => ocean_solve_transfer_globalID_cal
    PROCEDURE(a_trans_destruct), DEFERRED :: destruct
  END TYPE t_transfer
  TYPE, EXTENDS(t_transfer) :: t_trivial_transfer
    PRIVATE
    CLASS(t_comm_pattern), POINTER :: comm_pat_sync
    CONTAINS
    PROCEDURE, PUBLIC :: construct => trivial_transfer_construct
    PROCEDURE, PUBLIC :: destruct => trivial_transfer_destruct
    PROCEDURE :: into_2d_wp => trivial_transfer_into_2d_wp
    PROCEDURE :: into_2d_wp_2 => trivial_transfer_into_2d_wp_2
    PROCEDURE :: into_3d_wp => trivial_transfer_into_3d_wp
    PROCEDURE :: into_idx => trivial_transfer_into_idx
    PROCEDURE :: into_once_2d_wp => trivial_transfer_into_once_2d_wp
    PROCEDURE :: into_once_3d_wp => trivial_transfer_into_once_3d_wp
    PROCEDURE :: into_once_idx => trivial_transfer_into_once_idx
    PROCEDURE :: out_2d_wp => trivial_transfer_out_2d_wp
    PROCEDURE :: bcst_1d_wp => trivial_transfer_bcst_1d_wp
    PROCEDURE :: bcst_1d_i => trivial_transfer_bcst_1d_i
    PROCEDURE :: sync_2d_wp => trivial_transfer_sync_2d_wp
    PROCEDURE :: sync_2d_sp => trivial_transfer_sync_2d_sp
  END TYPE t_trivial_transfer
  TYPE, EXTENDS(t_transfer) :: t_subset_transfer
    PRIVATE
    INTEGER :: solve_buddy, nblk_l, nblk_a_l, nidx_e_l, ngid_a
    CLASS(t_comm_pattern), POINTER :: cpat_in => NULL(), cpat_in2 => NULL(), cpat_out => NULL(), cpat_sync => NULL()
    CONTAINS
    PROCEDURE, PUBLIC :: construct => subset_transfer_construct
    PROCEDURE, PUBLIC :: destruct => subset_transfer_destruct
    PROCEDURE :: into_2d_wp => subset_transfer_into_2d_wp
    PROCEDURE :: into_2d_wp_2 => subset_transfer_into_2d_wp_2
    PROCEDURE :: into_3d_wp => subset_transfer_into_3d_wp
    PROCEDURE :: into_idx => subset_transfer_into_idx
    PROCEDURE :: into_once_2d_wp => subset_transfer_into_once_2d_wp
    PROCEDURE :: into_once_3d_wp => subset_transfer_into_once_3d_wp
    PROCEDURE :: into_once_idx => subset_transfer_into_once_idx
    PROCEDURE :: out_2d_wp => subset_transfer_out_2d_wp
    PROCEDURE :: bcst_1d_wp => subset_transfer_bcst_1d_wp
    PROCEDURE :: bcst_1d_i => subset_transfer_bcst_1d_i
    PROCEDURE :: sync_2d_wp => subset_transfer_sync_2d_wp
    PROCEDURE :: sync_2d_sp => subset_transfer_sync_2d_sp
  END TYPE t_subset_transfer
  TYPE, ABSTRACT :: t_lhs_agen
    LOGICAL :: is_const, use_shortcut
    LOGICAL :: is_init = .FALSE.
    CONTAINS
    PROCEDURE(a_lhs_agen_wp), DEFERRED :: lhs_wp
    PROCEDURE(a_lhs_matrix_shortcut), DEFERRED :: lhs_matrix_shortcut
    GENERIC :: apply => lhs_wp
    GENERIC :: matrix_shortcut => lhs_matrix_shortcut
  END TYPE t_lhs_agen
  TYPE, EXTENDS(t_lhs_agen) :: t_surface_height_lhs
    PRIVATE
    TYPE(t_patch_3d), POINTER :: patch_3d => NULL()
    TYPE(t_patch), POINTER :: patch_2d => NULL()
    REAL(KIND = wp), POINTER :: thickness_e_wp(:, :) => NULL()
    TYPE(t_operator_coeff), POINTER :: op_coeffs_wp => NULL()
    TYPE(t_solverCoeff_singlePrecision), POINTER :: op_coeffs_sp => NULL()
    REAL(KIND = wp), ALLOCATABLE, DIMENSION(:, :), PRIVATE :: z_grad_h_wp, z_e_wp
    CONTAINS
    PROCEDURE :: lhs_wp => lhs_surface_height_wp
    PROCEDURE :: construct => lhs_surface_height_construct
    PROCEDURE, PRIVATE :: internal_matrix_wp => lhs_surface_height_ab_mim_matrix_wp
    PROCEDURE, PRIVATE :: internal_wp => lhs_surface_height_ab_mim_wp
    PROCEDURE :: lhs_matrix_shortcut => lhs_surface_height_ab_mim_matrix_shortcut
  END TYPE t_surface_height_lhs
  TYPE, EXTENDS(t_lhs_agen) :: t_lhs_zstar
    PRIVATE
    TYPE(t_patch_3d), POINTER :: patch_3d => NULL()
    TYPE(t_patch), POINTER :: patch_2d => NULL()
    REAL(KIND = wp), POINTER :: thickness_e_wp(:, :) => NULL()
    REAL(KIND = wp), POINTER, PUBLIC :: stretch_e(:, :) => NULL()
    TYPE(t_operator_coeff), POINTER :: op_coeffs_wp => NULL()
    TYPE(t_solverCoeff_singlePrecision), POINTER :: op_coeffs_sp => NULL()
    REAL(KIND = wp), ALLOCATABLE, DIMENSION(:, :), PRIVATE :: z_grad_h_wp, z_e_wp
    CONTAINS
    PROCEDURE :: lhs_wp => lhs_zstar
    PROCEDURE :: construct => lhs_zstar_construct
    PROCEDURE, PRIVATE :: internal_matrix_wp => lhs_zstar_matrix_wp
    PROCEDURE, PRIVATE :: internal_wp => lhs_zstar_wp
    PROCEDURE :: lhs_matrix_shortcut => lhs_zstar_matrix_shortcut
  END TYPE t_lhs_zstar
  TYPE, EXTENDS(t_lhs_agen) :: t_primal_flip_flop_lhs
    PRIVATE
    TYPE(t_patch_3d), POINTER :: patch_3d => NULL()
    TYPE(t_patch), POINTER :: patch_2d => NULL()
    TYPE(t_operator_coeff), POINTER :: op_coeffs
    INTEGER :: jk
    CONTAINS
    PROCEDURE :: lhs_wp => lhs_primal_flip_flop_wp
    PROCEDURE :: construct => lhs_primal_flip_flop_construct
    PROCEDURE :: lhs_matrix_shortcut => lhs_primal_flip_flop_matrix_shortcut
  END TYPE t_primal_flip_flop_lhs
  TYPE :: t_lhs
    PRIVATE
    INTEGER :: nblk_loc, nblk_a_loc, nidx_loc, nidx_e_loc, nnzero_loc, nnzero_cal, nextra, nnzs, timer_upd, nindep_grp, timer_init, grp_nelem(64), grp_nelem_max
    INTEGER, PUBLIC :: timer
    LOGICAL :: is_const, have_sp
    TYPE(t_primal_flip_flop_lhs), POINTER :: agen => NULL()
    TYPE(t_trivial_transfer), POINTER :: trans => NULL()
    LOGICAL, PUBLIC :: is_init = .FALSE.
    REAL(KIND = wp), ALLOCATABLE, DIMENSION(:, :) :: x_t, ax_t, dcoef_c_wp
    REAL(KIND = sp), ALLOCATABLE, DIMENSION(:, :, :) :: coef_c_sp
    REAL(KIND = wp), ALLOCATABLE, DIMENSION(:, :, :) :: coef_l_wp, coef_c_wp
    REAL(KIND = sp), ALLOCATABLE, DIMENSION(:, :) :: dcoef_c_sp
    INTEGER, ALLOCATABLE, DIMENSION(:, :, :) :: blk_loc, idx_loc, blk_cal, idx_cal, grp_smap_blk, grp_smap_idx, grp_smap_inz
    INTEGER, ALLOCATABLE, DIMENSION(:, :) :: grp_map_idx, grp_map_blk, inz_t, dnz_cal
    CONTAINS
    PROCEDURE, PRIVATE :: apply_wp => lhs_apply_wp
    PROCEDURE, PRIVATE :: apply_sp => lhs_apply_sp
    GENERIC, PUBLIC :: apply => apply_wp, apply_sp
    PROCEDURE, PRIVATE :: apply_noaii_wp => lhs_apply_noaii_wp
    PROCEDURE, PRIVATE :: apply_noaii_sp => lhs_apply_noaii_sp
    GENERIC, PUBLIC :: apply_noaii => apply_noaii_wp, apply_noaii_sp
    PROCEDURE, PRIVATE :: get_invaii_wp => lhs_get_invaii_wp
    PROCEDURE, PRIVATE :: get_invaii_sp => lhs_get_invaii_sp
    GENERIC, PUBLIC :: get_invaii => get_invaii_wp, get_invaii_sp
    PROCEDURE, PUBLIC :: update => lhs_update
    PROCEDURE, PUBLIC :: construct => lhs_construct
    PROCEDURE, PUBLIC :: dump_matrix => lhs_dump_matrix
    PROCEDURE, PUBLIC :: dump_ax => lhs_dump_ax
    PROCEDURE, PRIVATE :: find_nnzero => lhs_find_nnzero
    PROCEDURE, PRIVATE :: create_matrix_init => lhs_create_matrix_init
    PROCEDURE, PRIVATE :: create_matrix_redo => lhs_create_matrix_redo
    PROCEDURE, PRIVATE :: create_matrix => lhs_create_matrix
    PROCEDURE, PRIVATE :: doit_wp => lhs_doit_wp
    PROCEDURE, PRIVATE :: doit_sp => lhs_doit_sp
    GENERIC, PRIVATE :: doit => doit_wp, doit_sp
    PROCEDURE, PRIVATE :: noaii_doit_wp => lhs_noaii_doit_wp
    PROCEDURE, PRIVATE :: noaii_doit_sp => lhs_noaii_doit_sp
    GENERIC, PRIVATE :: noaii_doit => noaii_doit_wp, noaii_doit_sp
  END TYPE t_lhs
END MODULE
