! cloudsc_outer wrapper for the CLOUDSC-GPU scc_k_caching variant: publishes physical
! constants into the YOMCST/YOETHF/YRECLDP globals the verbatim kernel+driver read, packs
! tendencies into the driver's 4-D buffer, and runs one driver call over all NPROMA blocks.
! Arg list matches full-CLOUDSC CLOUDSCOUTER; NCLV/NCLDQ* stay PARAMETERs so the inliner
! bakes them to literals instead of runtime arguments.
SUBROUTINE CLOUDSCOUTER &
  & (NBLOCKS, NGPBLKS, NUMOMP, NGPTOT, NGPTOTG, NPROMA, KLON, KLEV, PTSPHY, PT, PQ, &
  & tendency_tmp_T, tendency_tmp_q, tendency_tmp_a, tendency_tmp_cld, &
  & tendency_loc_T, tendency_loc_q, tendency_loc_a, tendency_loc_cld, PVFA, PVFL, &
  & PVFI, PDYNA, PDYNL, PDYNI, PHRSW, PHRLW, PVERVEL, PAP, PAPH, PLSM, LDCUM, KTYPE, PLU, PLUDE, &
  & PSNDE, PMFU, PMFD, PA, PCLV, PSUPSAT, PLCRIT_AER, PICRIT_AER, PRE_ICE, &
  & PCCN, PNICE, PCOVPTOT, PRAINFRAC_TOPRFZ, PFSQLF, PFSQIF, PFCQNNG, PFCQLNG, PFSQRF, PFSQSF, &
  & PFCQRNG, PFCQSNG, PFSQLTUR, PFSQITUR, PFPLSL, PFPLSN, PFHPSL, PFHPSN, KFLDX, RG, RD, &
  & RCPD, RETV, RLVTT, RLSTT, RLMLT, RTT, RV, R2ES, R3LES, R3IES, R4LES, R4IES, R5LES, R5IES, &
  & R5ALVCP, R5ALSCP, RALVDCP, RALSDCP, RALFDCP, RTWAT, RTICE, RTICECU, RTWAT_RTICE_R, &
  & RTWAT_RTICECU_R, RKOOP1, RKOOP2, RAMID, RCLDIFF, &
  & RCLDIFF_CONVI, RCLCRIT, RCLCRIT_SEA, RCLCRIT_LAND, RKCONV, RPRC1, RPRC2, RCLDMAX, RPECONS, &
  & RVRFACTOR, RPRECRHMAX, RTAUMEL, RAMIN, RLMIN, RKOOPTAU, RCLDTOPP, RLCRITSNOW, RSNOWLIN1, &
  & RSNOWLIN2, RICEHI1, RICEHI2, RICEINIT, RVICE, RVRAIN, RVSNOW, RTHOMO, RCOVPMIN, RCCN, RNICE, &
  & RCCNOM, RCCNSS, RCCNSU, RCLDTOPCF, RDEPLIQREFRATE, RDEPLIQREFDEPTH, RCL_KKAac, RCL_KKBac, &
  & RCL_KKAau, RCL_KKBauq, RCL_KKBaun, RCL_KK_cloud_num_sea, RCL_KK_cloud_num_land, RCL_AI, RCL_BI, &
  & RCL_CI, RCL_DI, RCL_X1I, RCL_X2I, RCL_X3I, RCL_X4I, RCL_CONST1I, RCL_CONST2I, RCL_CONST3I, &
  & RCL_CONST4I, RCL_CONST5I, RCL_CONST6I, RCL_APB1, RCL_APB2, RCL_APB3, RCL_AS, RCL_BS, RCL_CS, &
  & RCL_DS, RCL_X1S, RCL_X2S, RCL_X3S, RCL_X4S, RCL_CONST1S, RCL_CONST2S, RCL_CONST3S, RCL_CONST4S, &
  & RCL_CONST5S, RCL_CONST6S, RCL_CONST7S, RCL_CONST8S, RDENSWAT, RDENSREF, RCL_AR, RCL_BR, RCL_CR, &
  & RCL_DR, RCL_X1R, RCL_X2R, RCL_X4R, RCL_KA273, RCL_CDENOM1, RCL_CDENOM2, RCL_CDENOM3, &
  & RCL_SCHMIDT, RCL_DYNVISC, RCL_CONST1R, RCL_CONST2R, RCL_CONST3R, RCL_CONST4R, RCL_FAC1, &
  & RCL_FAC2, RCL_CONST5R, RCL_CONST6R, RCL_FZRAB, RCL_FZRBB, LCLDEXTRA, LCLDBUDGET, &
  & LAERLIQAUTOLSP, LAERLIQAUTOCP, LAERLIQAUTOCPB, LAERLIQCOLL, LAERICESED, LAERICEAUTO, NSSOPT, &
  & NCLDTOP, NAECLBC, NAECLDU, NAECLOM, NAECLSS, NAECLSU, NCLDDIAG, NAERCLD)

  USE PARKIND1, ONLY: JPIM, JPRB
  USE YOMCST, ONLY: G_RG => RG, G_RD => RD, G_RCPD => RCPD, G_RETV => RETV, G_RLVTT => RLVTT, &
    & G_RLSTT => RLSTT, G_RLMLT => RLMLT, G_RTT => RTT, G_RV => RV
  USE YOETHF, ONLY: G_R2ES => R2ES, G_R3LES => R3LES, G_R3IES => R3IES, G_R4LES => R4LES, &
    & G_R4IES => R4IES, G_R5LES => R5LES, G_R5IES => R5IES, G_R5ALVCP => R5ALVCP, &
    & G_R5ALSCP => R5ALSCP, G_RALVDCP => RALVDCP, G_RALSDCP => RALSDCP, G_RALFDCP => RALFDCP, &
    & G_RTWAT => RTWAT, G_RTICE => RTICE, G_RTICECU => RTICECU, G_RTWAT_RTICE_R => RTWAT_RTICE_R, &
    & G_RTWAT_RTICECU_R => RTWAT_RTICECU_R, G_RKOOP1 => RKOOP1, G_RKOOP2 => RKOOP2
  USE YOECLDP, ONLY: YRECLDP, NCLV
  USE CLOUDSC_DRIVER_GPU_SCC_K_CACHING_MOD, ONLY: CLOUDSC_DRIVER_GPU_SCC_K_CACHING
  IMPLICIT NONE

  INTEGER(KIND=JPIM) :: NBLOCKS
  INTEGER(KIND=JPIM) :: NGPBLKS
  INTEGER(KIND=JPIM) :: NUMOMP
  INTEGER(KIND=JPIM) :: NGPTOT
  INTEGER(KIND=JPIM) :: NGPTOTG
  INTEGER(KIND=JPIM) :: NPROMA
  INTEGER(KIND=JPIM) :: KLON
  INTEGER(KIND=JPIM) :: KLEV
  REAL(KIND=JPRB) :: PTSPHY
  REAL(KIND=JPRB) :: PT(KLON,KLEV,NBLOCKS)
  REAL(KIND=JPRB) :: PQ(KLON,KLEV,NBLOCKS)
  REAL(KIND=JPRB) :: tendency_tmp_T(KLON,KLEV,NBLOCKS)
  REAL(KIND=JPRB) :: tendency_tmp_q(KLON,KLEV,NBLOCKS)
  REAL(KIND=JPRB) :: tendency_tmp_a(KLON,KLEV,NBLOCKS)
  REAL(KIND=JPRB) :: tendency_tmp_cld(KLON,KLEV,NCLV,NBLOCKS)
  REAL(KIND=JPRB) :: tendency_loc_T(KLON,KLEV,NBLOCKS)
  REAL(KIND=JPRB) :: tendency_loc_q(KLON,KLEV,NBLOCKS)
  REAL(KIND=JPRB) :: tendency_loc_a(KLON,KLEV,NBLOCKS)
  REAL(KIND=JPRB) :: tendency_loc_cld(KLON,KLEV,NCLV,NBLOCKS)
  REAL(KIND=JPRB) :: PVFA(KLON,KLEV,NBLOCKS)
  REAL(KIND=JPRB) :: PVFL(KLON,KLEV,NBLOCKS)
  REAL(KIND=JPRB) :: PVFI(KLON,KLEV,NBLOCKS)
  REAL(KIND=JPRB) :: PDYNA(KLON,KLEV,NBLOCKS)
  REAL(KIND=JPRB) :: PDYNL(KLON,KLEV,NBLOCKS)
  REAL(KIND=JPRB) :: PDYNI(KLON,KLEV,NBLOCKS)
  REAL(KIND=JPRB) :: PHRSW(KLON,KLEV,NBLOCKS)
  REAL(KIND=JPRB) :: PHRLW(KLON,KLEV,NBLOCKS)
  REAL(KIND=JPRB) :: PVERVEL(KLON,KLEV,NBLOCKS)
  REAL(KIND=JPRB) :: PAP(KLON,KLEV,NBLOCKS)
  REAL(KIND=JPRB) :: PAPH(KLON,KLEV+1,NBLOCKS)
  REAL(KIND=JPRB) :: PLSM(KLON,NBLOCKS)
  LOGICAL :: LDCUM(KLON,NBLOCKS)
  INTEGER(KIND=JPIM) :: KTYPE(KLON,NBLOCKS)
  REAL(KIND=JPRB) :: PLU(KLON,KLEV,NBLOCKS)
  REAL(KIND=JPRB) :: PLUDE(KLON,KLEV,NBLOCKS)
  REAL(KIND=JPRB) :: PSNDE(KLON,KLEV,NBLOCKS)
  REAL(KIND=JPRB) :: PMFU(KLON,KLEV,NBLOCKS)
  REAL(KIND=JPRB) :: PMFD(KLON,KLEV,NBLOCKS)
  REAL(KIND=JPRB) :: PA(KLON,KLEV,NBLOCKS)
  REAL(KIND=JPRB) :: PCLV(KLON,KLEV,NCLV,NBLOCKS)
  REAL(KIND=JPRB) :: PSUPSAT(KLON,KLEV,NBLOCKS)
  REAL(KIND=JPRB) :: PLCRIT_AER(KLON,KLEV,NBLOCKS)
  REAL(KIND=JPRB) :: PICRIT_AER(KLON,KLEV,NBLOCKS)
  REAL(KIND=JPRB) :: PRE_ICE(KLON,KLEV,NBLOCKS)
  REAL(KIND=JPRB) :: PCCN(KLON,KLEV,NBLOCKS)
  REAL(KIND=JPRB) :: PNICE(KLON,KLEV,NBLOCKS)
  REAL(KIND=JPRB) :: PCOVPTOT(KLON,KLEV,NBLOCKS)
  REAL(KIND=JPRB) :: PRAINFRAC_TOPRFZ(KLON,NBLOCKS)
  REAL(KIND=JPRB) :: PFSQLF(KLON,KLEV+1,NBLOCKS)
  REAL(KIND=JPRB) :: PFSQIF(KLON,KLEV+1,NBLOCKS)
  REAL(KIND=JPRB) :: PFCQNNG(KLON,KLEV+1,NBLOCKS)
  REAL(KIND=JPRB) :: PFCQLNG(KLON,KLEV+1,NBLOCKS)
  REAL(KIND=JPRB) :: PFSQRF(KLON,KLEV+1,NBLOCKS)
  REAL(KIND=JPRB) :: PFSQSF(KLON,KLEV+1,NBLOCKS)
  REAL(KIND=JPRB) :: PFCQRNG(KLON,KLEV+1,NBLOCKS)
  REAL(KIND=JPRB) :: PFCQSNG(KLON,KLEV+1,NBLOCKS)
  REAL(KIND=JPRB) :: PFSQLTUR(KLON,KLEV+1,NBLOCKS)
  REAL(KIND=JPRB) :: PFSQITUR(KLON,KLEV+1,NBLOCKS)
  REAL(KIND=JPRB) :: PFPLSL(KLON,KLEV+1,NBLOCKS)
  REAL(KIND=JPRB) :: PFPLSN(KLON,KLEV+1,NBLOCKS)
  REAL(KIND=JPRB) :: PFHPSL(KLON,KLEV+1,NBLOCKS)
  REAL(KIND=JPRB) :: PFHPSN(KLON,KLEV+1,NBLOCKS)
  INTEGER(KIND=JPIM) :: KFLDX
  REAL(KIND=JPRB) :: RG, RD, RCPD, RETV, RLVTT, RLSTT, RLMLT, RTT, RV
  REAL(KIND=JPRB) :: R2ES, R3LES, R3IES, R4LES, R4IES, R5LES, R5IES
  REAL(KIND=JPRB) :: R5ALVCP, R5ALSCP, RALVDCP, RALSDCP, RALFDCP, RTWAT, RTICE, RTICECU
  REAL(KIND=JPRB) :: RTWAT_RTICE_R, RTWAT_RTICECU_R, RKOOP1, RKOOP2
  REAL(KIND=JPRB) :: RAMID, RCLDIFF, RCLDIFF_CONVI, RCLCRIT, RCLCRIT_SEA, RCLCRIT_LAND
  REAL(KIND=JPRB) :: RKCONV, RPRC1, RPRC2, RCLDMAX, RPECONS, RVRFACTOR, RPRECRHMAX
  REAL(KIND=JPRB) :: RTAUMEL, RAMIN, RLMIN, RKOOPTAU, RCLDTOPP, RLCRITSNOW, RSNOWLIN1
  REAL(KIND=JPRB) :: RSNOWLIN2, RICEHI1, RICEHI2, RICEINIT, RVICE, RVRAIN, RVSNOW, RTHOMO
  REAL(KIND=JPRB) :: RCOVPMIN, RCCN, RNICE, RCCNOM, RCCNSS, RCCNSU, RCLDTOPCF
  REAL(KIND=JPRB) :: RDEPLIQREFRATE, RDEPLIQREFDEPTH
  REAL(KIND=JPRB) :: RCL_KKAac, RCL_KKBac, RCL_KKAau, RCL_KKBauq, RCL_KKBaun
  REAL(KIND=JPRB) :: RCL_KK_cloud_num_sea, RCL_KK_cloud_num_land
  REAL(KIND=JPRB) :: RCL_AI, RCL_BI, RCL_CI, RCL_DI, RCL_X1I, RCL_X2I, RCL_X3I, RCL_X4I
  REAL(KIND=JPRB) :: RCL_CONST1I, RCL_CONST2I, RCL_CONST3I, RCL_CONST4I, RCL_CONST5I, RCL_CONST6I
  REAL(KIND=JPRB) :: RCL_APB1, RCL_APB2, RCL_APB3
  REAL(KIND=JPRB) :: RCL_AS, RCL_BS, RCL_CS, RCL_DS, RCL_X1S, RCL_X2S, RCL_X3S, RCL_X4S
  REAL(KIND=JPRB) :: RCL_CONST1S, RCL_CONST2S, RCL_CONST3S, RCL_CONST4S, RCL_CONST5S
  REAL(KIND=JPRB) :: RCL_CONST6S, RCL_CONST7S, RCL_CONST8S
  REAL(KIND=JPRB) :: RDENSWAT, RDENSREF
  REAL(KIND=JPRB) :: RCL_AR, RCL_BR, RCL_CR, RCL_DR, RCL_X1R, RCL_X2R, RCL_X4R
  REAL(KIND=JPRB) :: RCL_KA273, RCL_CDENOM1, RCL_CDENOM2, RCL_CDENOM3
  REAL(KIND=JPRB) :: RCL_SCHMIDT, RCL_DYNVISC
  REAL(KIND=JPRB) :: RCL_CONST1R, RCL_CONST2R, RCL_CONST3R, RCL_CONST4R, RCL_FAC1, RCL_FAC2
  REAL(KIND=JPRB) :: RCL_CONST5R, RCL_CONST6R, RCL_FZRAB, RCL_FZRBB
  LOGICAL :: LCLDEXTRA, LCLDBUDGET
  LOGICAL :: LAERLIQAUTOLSP, LAERLIQAUTOCP, LAERLIQAUTOCPB, LAERLIQCOLL, LAERICESED, LAERICEAUTO
  INTEGER(KIND=JPIM) :: NSSOPT, NCLDTOP, NAECLBC, NAECLDU, NAECLOM, NAECLSS, NAECLSU
  INTEGER(KIND=JPIM) :: NCLDDIAG, NAERCLD

  REAL(KIND=JPRB), ALLOCATABLE :: BUFFER_CML(:,:,:,:)
  REAL(KIND=JPRB), ALLOCATABLE :: BUFFER_TMP(:,:,:,:)
  REAL(KIND=JPRB), ALLOCATABLE :: BUFFER_LOC(:,:,:,:)

  ! ----- Publish physical constants into module globals (dwarf's *_LOAD_PARAMETERS role) -----
  G_RG = RG
  G_RD = RD
  G_RCPD = RCPD
  G_RETV = RETV
  G_RLVTT = RLVTT
  G_RLSTT = RLSTT
  G_RLMLT = RLMLT
  G_RTT = RTT
  G_RV = RV
  G_R2ES = R2ES
  G_R3LES = R3LES
  G_R3IES = R3IES
  G_R4LES = R4LES
  G_R4IES = R4IES
  G_R5LES = R5LES
  G_R5IES = R5IES
  G_R5ALVCP = R5ALVCP
  G_R5ALSCP = R5ALSCP
  G_RALVDCP = RALVDCP
  G_RALSDCP = RALSDCP
  G_RALFDCP = RALFDCP
  G_RTWAT = RTWAT
  G_RTICE = RTICE
  G_RTICECU = RTICECU
  G_RTWAT_RTICE_R = RTWAT_RTICE_R
  G_RTWAT_RTICECU_R = RTWAT_RTICECU_R
  G_RKOOP1 = RKOOP1
  G_RKOOP2 = RKOOP2

  YRECLDP%RAMID = RAMID
  YRECLDP%RCLDIFF = RCLDIFF
  YRECLDP%RCLDIFF_CONVI = RCLDIFF_CONVI
  YRECLDP%RCLCRIT = RCLCRIT
  YRECLDP%RCLCRIT_SEA = RCLCRIT_SEA
  YRECLDP%RCLCRIT_LAND = RCLCRIT_LAND
  YRECLDP%RKCONV = RKCONV
  YRECLDP%RPRC1 = RPRC1
  YRECLDP%RPRC2 = RPRC2
  YRECLDP%RCLDMAX = RCLDMAX
  YRECLDP%RPECONS = RPECONS
  YRECLDP%RVRFACTOR = RVRFACTOR
  YRECLDP%RPRECRHMAX = RPRECRHMAX
  YRECLDP%RTAUMEL = RTAUMEL
  YRECLDP%RAMIN = RAMIN
  YRECLDP%RLMIN = RLMIN
  YRECLDP%RKOOPTAU = RKOOPTAU
  YRECLDP%RCLDTOPP = RCLDTOPP
  YRECLDP%RLCRITSNOW = RLCRITSNOW
  YRECLDP%RSNOWLIN1 = RSNOWLIN1
  YRECLDP%RSNOWLIN2 = RSNOWLIN2
  YRECLDP%RICEHI1 = RICEHI1
  YRECLDP%RICEHI2 = RICEHI2
  YRECLDP%RICEINIT = RICEINIT
  YRECLDP%RVICE = RVICE
  YRECLDP%RVRAIN = RVRAIN
  YRECLDP%RVSNOW = RVSNOW
  YRECLDP%RTHOMO = RTHOMO
  YRECLDP%RCOVPMIN = RCOVPMIN
  YRECLDP%RCCN = RCCN
  YRECLDP%RNICE = RNICE
  YRECLDP%RCCNOM = RCCNOM
  YRECLDP%RCCNSS = RCCNSS
  YRECLDP%RCCNSU = RCCNSU
  YRECLDP%RCLDTOPCF = RCLDTOPCF
  YRECLDP%RDEPLIQREFRATE = RDEPLIQREFRATE
  YRECLDP%RDEPLIQREFDEPTH = RDEPLIQREFDEPTH
  YRECLDP%RCL_KKAac = RCL_KKAac
  YRECLDP%RCL_KKBac = RCL_KKBac
  YRECLDP%RCL_KKAau = RCL_KKAau
  YRECLDP%RCL_KKBauq = RCL_KKBauq
  YRECLDP%RCL_KKBaun = RCL_KKBaun
  YRECLDP%RCL_KK_cloud_num_sea = RCL_KK_cloud_num_sea
  YRECLDP%RCL_KK_cloud_num_land = RCL_KK_cloud_num_land
  YRECLDP%RCL_AI = RCL_AI
  YRECLDP%RCL_BI = RCL_BI
  YRECLDP%RCL_CI = RCL_CI
  YRECLDP%RCL_DI = RCL_DI
  YRECLDP%RCL_X1I = RCL_X1I
  YRECLDP%RCL_X2I = RCL_X2I
  YRECLDP%RCL_X3I = RCL_X3I
  YRECLDP%RCL_X4I = RCL_X4I
  YRECLDP%RCL_CONST1I = RCL_CONST1I
  YRECLDP%RCL_CONST2I = RCL_CONST2I
  YRECLDP%RCL_CONST3I = RCL_CONST3I
  YRECLDP%RCL_CONST4I = RCL_CONST4I
  YRECLDP%RCL_CONST5I = RCL_CONST5I
  YRECLDP%RCL_CONST6I = RCL_CONST6I
  YRECLDP%RCL_APB1 = RCL_APB1
  YRECLDP%RCL_APB2 = RCL_APB2
  YRECLDP%RCL_APB3 = RCL_APB3
  YRECLDP%RCL_AS = RCL_AS
  YRECLDP%RCL_BS = RCL_BS
  YRECLDP%RCL_CS = RCL_CS
  YRECLDP%RCL_DS = RCL_DS
  YRECLDP%RCL_X1S = RCL_X1S
  YRECLDP%RCL_X2S = RCL_X2S
  YRECLDP%RCL_X3S = RCL_X3S
  YRECLDP%RCL_X4S = RCL_X4S
  YRECLDP%RCL_CONST1S = RCL_CONST1S
  YRECLDP%RCL_CONST2S = RCL_CONST2S
  YRECLDP%RCL_CONST3S = RCL_CONST3S
  YRECLDP%RCL_CONST4S = RCL_CONST4S
  YRECLDP%RCL_CONST5S = RCL_CONST5S
  YRECLDP%RCL_CONST6S = RCL_CONST6S
  YRECLDP%RCL_CONST7S = RCL_CONST7S
  YRECLDP%RCL_CONST8S = RCL_CONST8S
  YRECLDP%RDENSWAT = RDENSWAT
  YRECLDP%RDENSREF = RDENSREF
  YRECLDP%RCL_AR = RCL_AR
  YRECLDP%RCL_BR = RCL_BR
  YRECLDP%RCL_CR = RCL_CR
  YRECLDP%RCL_DR = RCL_DR
  YRECLDP%RCL_X1R = RCL_X1R
  YRECLDP%RCL_X2R = RCL_X2R
  YRECLDP%RCL_X4R = RCL_X4R
  YRECLDP%RCL_KA273 = RCL_KA273
  YRECLDP%RCL_CDENOM1 = RCL_CDENOM1
  YRECLDP%RCL_CDENOM2 = RCL_CDENOM2
  YRECLDP%RCL_CDENOM3 = RCL_CDENOM3
  YRECLDP%RCL_SCHMIDT = RCL_SCHMIDT
  YRECLDP%RCL_DYNVISC = RCL_DYNVISC
  YRECLDP%RCL_CONST1R = RCL_CONST1R
  YRECLDP%RCL_CONST2R = RCL_CONST2R
  YRECLDP%RCL_CONST3R = RCL_CONST3R
  YRECLDP%RCL_CONST4R = RCL_CONST4R
  YRECLDP%RCL_FAC1 = RCL_FAC1
  YRECLDP%RCL_FAC2 = RCL_FAC2
  YRECLDP%RCL_CONST5R = RCL_CONST5R
  YRECLDP%RCL_CONST6R = RCL_CONST6R
  YRECLDP%RCL_FZRAB = RCL_FZRAB
  YRECLDP%RCL_FZRBB = RCL_FZRBB
  YRECLDP%LCLDEXTRA = LCLDEXTRA
  YRECLDP%LCLDBUDGET = LCLDBUDGET
  YRECLDP%LAERLIQAUTOLSP = LAERLIQAUTOLSP
  YRECLDP%LAERLIQAUTOCP = LAERLIQAUTOCP
  YRECLDP%LAERLIQAUTOCPB = LAERLIQAUTOCPB
  YRECLDP%LAERLIQCOLL = LAERLIQCOLL
  YRECLDP%LAERICESED = LAERICESED
  YRECLDP%LAERICEAUTO = LAERICEAUTO
  YRECLDP%NSSOPT = NSSOPT
  YRECLDP%NCLDTOP = NCLDTOP
  YRECLDP%NAECLBC = NAECLBC
  YRECLDP%NAECLDU = NAECLDU
  YRECLDP%NAECLOM = NAECLOM
  YRECLDP%NAECLSS = NAECLSS
  YRECLDP%NAECLSU = NAECLSU
  YRECLDP%NCLDDIAG = NCLDDIAG
  YRECLDP%NAERCLD = NAERCLD

  ! ----- Pack tendencies into driver's 4-D buffer: slot 1=T, 2=a, 3=q, 4:3+NCLV=cld.
  ! BUFFER_CML is driver-ABI-only, unused by this kernel. -----
  ALLOCATE(BUFFER_CML(KLON,KLEV,3+NCLV,NBLOCKS))
  ALLOCATE(BUFFER_TMP(KLON,KLEV,3+NCLV,NBLOCKS))
  ALLOCATE(BUFFER_LOC(KLON,KLEV,3+NCLV,NBLOCKS))
  BUFFER_CML = 0.0_JPRB
  BUFFER_TMP(:,:,1,:) = tendency_tmp_T
  BUFFER_TMP(:,:,2,:) = tendency_tmp_a
  BUFFER_TMP(:,:,3,:) = tendency_tmp_q
  BUFFER_TMP(:,:,4:3+NCLV,:) = tendency_tmp_cld
  BUFFER_LOC = 0.0_JPRB

  CALL CLOUDSC_DRIVER_GPU_SCC_K_CACHING( &
    & NUMOMP, NPROMA, KLEV, NGPTOT, NGPBLKS, NGPTOTG, KFLDX, PTSPHY, &
    & PT, PQ, &
    & BUFFER_CML, BUFFER_TMP, BUFFER_LOC, &
    & PVFA, PVFL, PVFI, PDYNA, PDYNL, PDYNI, &
    & PHRSW, PHRLW, &
    & PVERVEL, PAP, PAPH, &
    & PLSM, LDCUM, KTYPE, &
    & PLU, PLUDE, PSNDE, PMFU, PMFD, &
    & PA, &
    & PCLV, PSUPSAT, &
    & PLCRIT_AER, PICRIT_AER, PRE_ICE, &
    & PCCN, PNICE, &
    & PCOVPTOT, PRAINFRAC_TOPRFZ, &
    & PFSQLF, PFSQIF, PFCQNNG, PFCQLNG, &
    & PFSQRF, PFSQSF, PFCQRNG, PFCQSNG, &
    & PFSQLTUR, PFSQITUR, &
    & PFPLSL, PFPLSN, PFHPSL, PFHPSN)

  ! ----- Unpack the computed local tendency back to the split arrays -----
  tendency_loc_T = BUFFER_LOC(:,:,1,:)
  tendency_loc_a = BUFFER_LOC(:,:,2,:)
  tendency_loc_q = BUFFER_LOC(:,:,3,:)
  tendency_loc_cld = BUFFER_LOC(:,:,4:3+NCLV,:)

  DEALLOCATE(BUFFER_CML)
  DEALLOCATE(BUFFER_TMP)
  DEALLOCATE(BUFFER_LOC)

END SUBROUTINE CLOUDSCOUTER
