! AUTO-GENERATED by dace.frontend.hlfir.bindings -- do not edit.
! Source: dolu @ frozen signature version 1
module dolu_dace_bindings
  use iso_c_binding
  use lu, only: a__mod => a, b__mod => b, c__mod => c, ce__mod => ce, d__mod => d, deta__mod => deta, dssp__mod => dssp, dt__mod => dt, dx1__mod => dx1, dx2__mod => dx2, dx3__mod => dx3, dx4__mod => dx4, dx5__mod => dx5, dxi__mod => dxi, dy1__mod => dy1, dy2__mod => dy2, dy3__mod => dy3, dy4__mod => dy4, dy5__mod => dy5, dz1__mod => dz1, dz2__mod => dz2, dz3__mod => dz3, dz4__mod => dz4, dz5__mod => dz5, dzeta__mod => dzeta, errnm__mod => errnm, flux__mod => flux, frc__mod => frc, frct__mod => frct, iend__mod => iend, ii1__mod => ii1, ii2__mod => ii2, inorm__mod => inorm, invert__mod => invert, ipr__mod => ipr, ist__mod => ist, itmax__mod => itmax, jend__mod => jend, ji1__mod => ji1, ji2__mod => ji2, jst__mod => jst, ki1__mod => ki1, ki2__mod => ki2, nx0__mod => nx0, nx__mod => nx, ny0__mod => ny0, ny__mod => ny, nz0__mod => nz0, nz__mod => nz, omega__mod => omega, qs__mod => qs, rho_i__mod => rho_i, rsd__mod => rsd, rsdnm__mod => rsdnm, tolrsd__mod => tolrsd, ttotal__mod => ttotal, tx1__mod => tx1, tx2__mod => tx2, tx3__mod => tx3, ty1__mod => ty1, ty2__mod => ty2, ty3__mod => ty3, tz1__mod => tz1, tz2__mod => tz2, tz3__mod => tz3, u__mod => u
  implicit none
  private
  public :: dolu_dace, dolu_dace_finalize

  ! ---------------- C ABI interface to the compiled SDFG ----------------
  interface
    function dace_init_dolu(inorm) bind(c, name='__dace_init_dolu') result(h)
      import :: c_ptr, c_int, c_long_long
      integer(c_int), value :: inorm
      type(c_ptr) :: h
    end function

    subroutine dace_program_dolu(h,  &
      a,  &
      b,  &
      c,  &
      ce,  &
      d,  &
      deta,  &
      dssp,  &
      dt,  &
      dx1,  &
      dx2,  &
      dx3,  &
      dx4,  &
      dx5,  &
      dxi,  &
      dy1,  &
      dy2,  &
      dy3,  &
      dy4,  &
      dy5,  &
      dz1,  &
      dz2,  &
      dz3,  &
      dz4,  &
      dz5,  &
      dzeta,  &
      errnm,  &
      flux,  &
      frc,  &
      frct,  &
      ii1,  &
      ii2,  &
      invert,  &
      ipr,  &
      itmax,  &
      ji1,  &
      ji2,  &
      ki1,  &
      ki2,  &
      nx0,  &
      ny0,  &
      nz0,  &
      omega,  &
      qs,  &
      rho_i,  &
      rsd,  &
      rsdnm,  &
      tolrsd,  &
      ttotal,  &
      tx1,  &
      tx2,  &
      tx3,  &
      ty1,  &
      ty2,  &
      ty3,  &
      tz1,  &
      tz2,  &
      tz3,  &
      u,  &
      inorm) bind(c, name='__program_dolu')
      import
      type(c_ptr), value :: h
      type(c_ptr), value :: a
      type(c_ptr), value :: b
      type(c_ptr), value :: c
      type(c_ptr), value :: ce
      type(c_ptr), value :: d
      type(c_ptr), value :: deta
      type(c_ptr), value :: dssp
      type(c_ptr), value :: dt
      type(c_ptr), value :: dx1
      type(c_ptr), value :: dx2
      type(c_ptr), value :: dx3
      type(c_ptr), value :: dx4
      type(c_ptr), value :: dx5
      type(c_ptr), value :: dxi
      type(c_ptr), value :: dy1
      type(c_ptr), value :: dy2
      type(c_ptr), value :: dy3
      type(c_ptr), value :: dy4
      type(c_ptr), value :: dy5
      type(c_ptr), value :: dz1
      type(c_ptr), value :: dz2
      type(c_ptr), value :: dz3
      type(c_ptr), value :: dz4
      type(c_ptr), value :: dz5
      type(c_ptr), value :: dzeta
      type(c_ptr), value :: errnm
      type(c_ptr), value :: flux
      type(c_ptr), value :: frc
      type(c_ptr), value :: frct
      type(c_ptr), value :: ii1
      type(c_ptr), value :: ii2
      type(c_ptr), value :: invert
      type(c_ptr), value :: ipr
      type(c_ptr), value :: itmax
      type(c_ptr), value :: ji1
      type(c_ptr), value :: ji2
      type(c_ptr), value :: ki1
      type(c_ptr), value :: ki2
      type(c_ptr), value :: nx0
      type(c_ptr), value :: ny0
      type(c_ptr), value :: nz0
      type(c_ptr), value :: omega
      type(c_ptr), value :: qs
      type(c_ptr), value :: rho_i
      type(c_ptr), value :: rsd
      type(c_ptr), value :: rsdnm
      type(c_ptr), value :: tolrsd
      type(c_ptr), value :: ttotal
      type(c_ptr), value :: tx1
      type(c_ptr), value :: tx2
      type(c_ptr), value :: tx3
      type(c_ptr), value :: ty1
      type(c_ptr), value :: ty2
      type(c_ptr), value :: ty3
      type(c_ptr), value :: tz1
      type(c_ptr), value :: tz2
      type(c_ptr), value :: tz3
      type(c_ptr), value :: u
      integer(c_int), value :: inorm
    end subroutine

    function dace_exit_dolu(h) bind(c, name='__dace_exit_dolu') result(err)
      import :: c_ptr, c_int
      type(c_ptr), value :: h
      integer(c_int) :: err
    end function
  end interface


  ! ----------------- Reference-counted handle state --------------------
  ! First call to dolu_dace allocates the DaCe state via
  ! __dace_init_dolu; further calls increment the ref counter.
  ! dolu_dace_finalize decrements; the counter reaching zero calls
  ! __dace_exit_dolu and nulls the handle.  This keeps one DaCe
  ! state per entry-point per process, shared across all call sites.
  type(c_ptr), save :: dace_handle = c_null_ptr
  integer,     save :: init_count  = 0


contains

  subroutine dolu_dace()
    ! (no dummies)

    ! Flat pointers aliased onto struct members (c_loc / c_f_pointer).
    ! (no flat pointers)

    ! Scratch arrays for deep-copy members (complex-split etc.).
    real(c_double), allocatable, target :: a(:, :, :, :)
    real(c_double), allocatable, target :: b(:, :, :, :)
    real(c_double), allocatable, target :: c(:, :, :, :)
    real(c_double), allocatable, target :: ce(:, :)
    real(c_double), allocatable, target :: d(:, :, :, :)
    real(c_double), allocatable, target :: deta(:)
    real(c_double), allocatable, target :: dssp(:)
    real(c_double), allocatable, target :: dt(:)
    real(c_double), allocatable, target :: dx1(:)
    real(c_double), allocatable, target :: dx2(:)
    real(c_double), allocatable, target :: dx3(:)
    real(c_double), allocatable, target :: dx4(:)
    real(c_double), allocatable, target :: dx5(:)
    real(c_double), allocatable, target :: dxi(:)
    real(c_double), allocatable, target :: dy1(:)
    real(c_double), allocatable, target :: dy2(:)
    real(c_double), allocatable, target :: dy3(:)
    real(c_double), allocatable, target :: dy4(:)
    real(c_double), allocatable, target :: dy5(:)
    real(c_double), allocatable, target :: dz1(:)
    real(c_double), allocatable, target :: dz2(:)
    real(c_double), allocatable, target :: dz3(:)
    real(c_double), allocatable, target :: dz4(:)
    real(c_double), allocatable, target :: dz5(:)
    real(c_double), allocatable, target :: dzeta(:)
    real(c_double), allocatable, target :: errnm(:)
    real(c_double), allocatable, target :: flux(:, :)
    real(c_double), allocatable, target :: frc(:)
    real(c_double), allocatable, target :: frct(:, :, :, :)
    integer(c_int), allocatable, target :: ii1(:)
    integer(c_int), allocatable, target :: ii2(:)
    integer(c_int), allocatable, target :: invert(:)
    integer(c_int), allocatable, target :: ipr(:)
    integer(c_int), allocatable, target :: itmax(:)
    integer(c_int), allocatable, target :: ji1(:)
    integer(c_int), allocatable, target :: ji2(:)
    integer(c_int), allocatable, target :: ki1(:)
    integer(c_int), allocatable, target :: ki2(:)
    integer(c_int), allocatable, target :: nx0(:)
    integer(c_int), allocatable, target :: ny0(:)
    integer(c_int), allocatable, target :: nz0(:)
    real(c_double), allocatable, target :: omega(:)
    real(c_double), allocatable, target :: qs(:, :, :)
    real(c_double), allocatable, target :: rho_i(:, :, :)
    real(c_double), allocatable, target :: rsd(:, :, :, :)
    real(c_double), allocatable, target :: rsdnm(:)
    real(c_double), allocatable, target :: tolrsd(:)
    real(c_double), allocatable, target :: ttotal(:)
    real(c_double), allocatable, target :: tx1(:)
    real(c_double), allocatable, target :: tx2(:)
    real(c_double), allocatable, target :: tx3(:)
    real(c_double), allocatable, target :: ty1(:)
    real(c_double), allocatable, target :: ty2(:)
    real(c_double), allocatable, target :: ty3(:)
    real(c_double), allocatable, target :: tz1(:)
    real(c_double), allocatable, target :: tz2(:)
    real(c_double), allocatable, target :: tz3(:)
    real(c_double), allocatable, target :: u(:, :, :, :)

    ! Local scalars for SDFG free-symbol values.
    integer(c_int) :: inorm

    integer(c_int) :: dace_err

    ! ----- Copy-in / alias per flatten entry -----

    ! ----- Module-global args sourced from use-imports -----
    allocate(a(5, 5, 33, 33))
    a = a__mod
    allocate(b(5, 5, 33, 33))
    b = b__mod
    allocate(c(5, 5, 33, 33))
    c = c__mod
    allocate(ce(5, 13))
    ce = ce__mod
    allocate(d(5, 5, 33, 33))
    d = d__mod
    allocate(deta(1))
    deta = deta__mod
    allocate(dssp(1))
    dssp = dssp__mod
    allocate(dt(1))
    dt = dt__mod
    allocate(dx1(1))
    dx1 = dx1__mod
    allocate(dx2(1))
    dx2 = dx2__mod
    allocate(dx3(1))
    dx3 = dx3__mod
    allocate(dx4(1))
    dx4 = dx4__mod
    allocate(dx5(1))
    dx5 = dx5__mod
    allocate(dxi(1))
    dxi = dxi__mod
    allocate(dy1(1))
    dy1 = dy1__mod
    allocate(dy2(1))
    dy2 = dy2__mod
    allocate(dy3(1))
    dy3 = dy3__mod
    allocate(dy4(1))
    dy4 = dy4__mod
    allocate(dy5(1))
    dy5 = dy5__mod
    allocate(dz1(1))
    dz1 = dz1__mod
    allocate(dz2(1))
    dz2 = dz2__mod
    allocate(dz3(1))
    dz3 = dz3__mod
    allocate(dz4(1))
    dz4 = dz4__mod
    allocate(dz5(1))
    dz5 = dz5__mod
    allocate(dzeta(1))
    dzeta = dzeta__mod
    allocate(errnm(5))
    errnm = errnm__mod
    allocate(flux(5, 33))
    flux = flux__mod
    allocate(frc(1))
    frc = frc__mod
    allocate(frct(5, 33, 33, 33))
    frct = frct__mod
    allocate(ii1(1))
    ii1 = ii1__mod
    allocate(ii2(1))
    ii2 = ii2__mod
    allocate(invert(1))
    invert = invert__mod
    allocate(ipr(1))
    ipr = ipr__mod
    allocate(itmax(1))
    itmax = itmax__mod
    allocate(ji1(1))
    ji1 = ji1__mod
    allocate(ji2(1))
    ji2 = ji2__mod
    allocate(ki1(1))
    ki1 = ki1__mod
    allocate(ki2(1))
    ki2 = ki2__mod
    allocate(nx0(1))
    nx0 = nx0__mod
    allocate(ny0(1))
    ny0 = ny0__mod
    allocate(nz0(1))
    nz0 = nz0__mod
    allocate(omega(1))
    omega = omega__mod
    allocate(qs(33, 33, 33))
    qs = qs__mod
    allocate(rho_i(33, 33, 33))
    rho_i = rho_i__mod
    allocate(rsd(5, 33, 33, 33))
    rsd = rsd__mod
    allocate(rsdnm(5))
    rsdnm = rsdnm__mod
    allocate(tolrsd(5))
    tolrsd = tolrsd__mod
    allocate(ttotal(1))
    ttotal = ttotal__mod
    allocate(tx1(1))
    tx1 = tx1__mod
    allocate(tx2(1))
    tx2 = tx2__mod
    allocate(tx3(1))
    tx3 = tx3__mod
    allocate(ty1(1))
    ty1 = ty1__mod
    allocate(ty2(1))
    ty2 = ty2__mod
    allocate(ty3(1))
    ty3 = ty3__mod
    allocate(tz1(1))
    tz1 = tz1__mod
    allocate(tz2(1))
    tz2 = tz2__mod
    allocate(tz3(1))
    tz3 = tz3__mod
    allocate(u(5, 33, 33, 33))
    u = u__mod

    ! ----- Symbol population -----
    inorm = int(inorm__mod, c_int)
    ! Ref-counted init -- first call allocates, subsequent calls reuse.
    if (init_count == 0) then
      dace_handle = dace_init_dolu(inorm)
    end if
    init_count = init_count + 1

    ! The actual SDFG invocation.
    call dace_program_dolu(dace_handle,  &
      c_loc(a),  &
      c_loc(b),  &
      c_loc(c),  &
      c_loc(ce),  &
      c_loc(d),  &
      c_loc(deta),  &
      c_loc(dssp),  &
      c_loc(dt),  &
      c_loc(dx1),  &
      c_loc(dx2),  &
      c_loc(dx3),  &
      c_loc(dx4),  &
      c_loc(dx5),  &
      c_loc(dxi),  &
      c_loc(dy1),  &
      c_loc(dy2),  &
      c_loc(dy3),  &
      c_loc(dy4),  &
      c_loc(dy5),  &
      c_loc(dz1),  &
      c_loc(dz2),  &
      c_loc(dz3),  &
      c_loc(dz4),  &
      c_loc(dz5),  &
      c_loc(dzeta),  &
      c_loc(errnm),  &
      c_loc(flux),  &
      c_loc(frc),  &
      c_loc(frct),  &
      c_loc(ii1),  &
      c_loc(ii2),  &
      c_loc(invert),  &
      c_loc(ipr),  &
      c_loc(itmax),  &
      c_loc(ji1),  &
      c_loc(ji2),  &
      c_loc(ki1),  &
      c_loc(ki2),  &
      c_loc(nx0),  &
      c_loc(ny0),  &
      c_loc(nz0),  &
      c_loc(omega),  &
      c_loc(qs),  &
      c_loc(rho_i),  &
      c_loc(rsd),  &
      c_loc(rsdnm),  &
      c_loc(tolrsd),  &
      c_loc(ttotal),  &
      c_loc(tx1),  &
      c_loc(tx2),  &
      c_loc(tx3),  &
      c_loc(ty1),  &
      c_loc(ty2),  &
      c_loc(ty3),  &
      c_loc(tz1),  &
      c_loc(tz2),  &
      c_loc(tz3),  &
      c_loc(u),  &
      inorm)


    ! ----- Write-back for kernel-written module globals -----
    a__mod = a
    b__mod = b
    c__mod = c
    ce__mod = ce
    d__mod = d
    deta__mod = deta(1)
    dssp__mod = dssp(1)
    dx1__mod = dx1(1)
    dx2__mod = dx2(1)
    dx3__mod = dx3(1)
    dx4__mod = dx4(1)
    dx5__mod = dx5(1)
    dxi__mod = dxi(1)
    dy1__mod = dy1(1)
    dy2__mod = dy2(1)
    dy3__mod = dy3(1)
    dy4__mod = dy4(1)
    dy5__mod = dy5(1)
    dz1__mod = dz1(1)
    dz2__mod = dz2(1)
    dz3__mod = dz3(1)
    dz4__mod = dz4(1)
    dz5__mod = dz5(1)
    dzeta__mod = dzeta(1)
    flux__mod = flux
    frct__mod = frct
    ii1__mod = ii1(1)
    ii2__mod = ii2(1)
    ji1__mod = ji1(1)
    ji2__mod = ji2(1)
    ki1__mod = ki1(1)
    ki2__mod = ki2(1)
    qs__mod = qs
    rho_i__mod = rho_i
    rsd__mod = rsd
    rsdnm__mod = rsdnm
    tx1__mod = tx1(1)
    tx2__mod = tx2(1)
    tx3__mod = tx3(1)
    ty1__mod = ty1(1)
    ty2__mod = ty2(1)
    ty3__mod = ty3(1)
    tz1__mod = tz1(1)
    tz2__mod = tz2(1)
    tz3__mod = tz3(1)
    u__mod = u
  end subroutine dolu_dace

  subroutine dolu_dace_finalize()
    integer(c_int) :: err
    if (init_count > 0) then
      init_count = init_count - 1
      if (init_count == 0) then
        err = dace_exit_dolu(dace_handle)
        dace_handle = c_null_ptr
      end if
    end if
  end subroutine dolu_dace_finalize




end module dolu_dace_bindings
