"""Shared scaffolding for the full-ICON velocity_tendencies tests.

_INIT_ARRAY_ORDER (flat-arg ABI order), _OUTPUT_NAMES, and _allocate are
correctness-critical and identical across the numerical, bindings-e2e, and
auto-module-source test variants -- single source of truth.
"""

import numpy as np

# Caller flat-array dummy order -- MUST match velocity_full_caller.f90's run_velocity_flat_c argument list exactly.
_INIT_ARRAY_ORDER = (
    "p_patch_cells_area",
    "p_patch_cells_neighbor_idx",
    "p_patch_cells_neighbor_blk",
    "p_patch_cells_edge_idx",
    "p_patch_cells_edge_blk",
    "p_patch_cells_start_index",
    "p_patch_cells_end_index",
    "p_patch_cells_start_block",
    "p_patch_cells_end_block",
    "p_patch_cells_decomp_info_owner_mask",
    "p_patch_edges_cell_idx",
    "p_patch_edges_cell_blk",
    "p_patch_edges_vertex_idx",
    "p_patch_edges_vertex_blk",
    "p_patch_edges_quad_idx",
    "p_patch_edges_quad_blk",
    "p_patch_edges_tangent_orientation",
    "p_patch_edges_inv_primal_edge_length",
    "p_patch_edges_inv_dual_edge_length",
    "p_patch_edges_area_edge",
    "p_patch_edges_f_e",
    "p_patch_edges_fn_e",
    "p_patch_edges_ft_e",
    "p_patch_edges_start_index",
    "p_patch_edges_end_index",
    "p_patch_edges_start_block",
    "p_patch_edges_end_block",
    "p_patch_verts_cell_idx",
    "p_patch_verts_cell_blk",
    "p_patch_verts_edge_idx",
    "p_patch_verts_edge_blk",
    "p_patch_verts_start_index",
    "p_patch_verts_end_index",
    "p_patch_verts_start_block",
    "p_patch_verts_end_block",
    "p_int_c_lin_e",
    "p_int_e_bln_c_s",
    "p_int_cells_aw_verts",
    "p_int_rbf_vec_coeff_e",
    "p_int_geofac_grdiv",
    "p_int_geofac_rot",
    "p_int_geofac_n2s",
    "p_prog_w",
    "p_prog_vn",
    "p_diag_vn_ie_ubc",
    "p_diag_vt",
    "p_diag_vn_ie",
    "p_diag_w_concorr_c",
    "p_diag_ddt_vn_apc_pc",
    "p_diag_ddt_vn_cor_pc",
    "p_diag_ddt_w_adv_pc",
    "p_metrics_ddxn_z_full",
    "p_metrics_ddxt_z_full",
    "p_metrics_ddqz_z_full_e",
    "p_metrics_ddqz_z_half",
    "p_metrics_wgtfac_c",
    "p_metrics_wgtfac_e",
    "p_metrics_wgtfacq_e",
    "p_metrics_coeff_gradekin",
    "p_metrics_coeff1_dwdz",
    "p_metrics_coeff2_dwdz",
    "p_metrics_deepatmo_gradh_mc",
    "p_metrics_deepatmo_invr_mc",
    "p_metrics_deepatmo_gradh_ifc",
    "p_metrics_deepatmo_invr_ifc",
)

_OUTPUT_NAMES = (
    "p_prog_w",
    "p_prog_vn",
    "p_diag_vn_ie_ubc",
    "p_diag_vt",
    "p_diag_vn_ie",
    "p_diag_w_concorr_c",
    "p_diag_ddt_vn_apc_pc",
    "p_diag_ddt_vn_cor_pc",
    "p_diag_ddt_w_adv_pc",
    "z_w_concorr_me",
    "z_kin_hor_e",
    "z_vt_ie",
)


def _allocate(nproma, nlev, nlevp1, nblks_c, nblks_e, nblks_v):
    """Zeroed Fortran-order input arrays for one velocity_tendencies
    call, shaped to the ICON L137 grid dims passed in."""

    def zeros_f64(*s):
        return np.zeros(s, dtype=np.float64, order="F")

    def zeros_i32(*s):
        return np.zeros(s, dtype=np.int32, order="F")

    def zeros_i8(*s):
        return np.zeros(s, dtype=np.int8, order="F")

    return dict(
        p_patch_cells_area=zeros_f64(nproma, nblks_c),
        p_patch_cells_neighbor_idx=zeros_i32(nproma, nblks_c, 3),
        p_patch_cells_neighbor_blk=zeros_i32(nproma, nblks_c, 3),
        p_patch_cells_edge_idx=zeros_i32(nproma, nblks_c, 3),
        p_patch_cells_edge_blk=zeros_i32(nproma, nblks_c, 3),
        p_patch_cells_start_index=zeros_i32(33),
        p_patch_cells_end_index=zeros_i32(33),
        p_patch_cells_start_block=zeros_i32(33),
        p_patch_cells_end_block=zeros_i32(33),
        p_patch_cells_decomp_info_owner_mask=zeros_i8(nproma, nblks_c),
        p_patch_edges_cell_idx=zeros_i32(nproma, nblks_e, 2),
        p_patch_edges_cell_blk=zeros_i32(nproma, nblks_e, 2),
        p_patch_edges_vertex_idx=zeros_i32(nproma, nblks_e, 4),
        p_patch_edges_vertex_blk=zeros_i32(nproma, nblks_e, 4),
        p_patch_edges_quad_idx=zeros_i32(nproma, nblks_e, 4),
        p_patch_edges_quad_blk=zeros_i32(nproma, nblks_e, 4),
        p_patch_edges_tangent_orientation=zeros_f64(nproma, nblks_e),
        p_patch_edges_inv_primal_edge_length=zeros_f64(nproma, nblks_e),
        p_patch_edges_inv_dual_edge_length=zeros_f64(nproma, nblks_e),
        p_patch_edges_area_edge=zeros_f64(nproma, nblks_e),
        p_patch_edges_f_e=zeros_f64(nproma, nblks_e),
        p_patch_edges_fn_e=zeros_f64(nproma, nblks_e),
        p_patch_edges_ft_e=zeros_f64(nproma, nblks_e),
        p_patch_edges_start_index=zeros_i32(33),
        p_patch_edges_end_index=zeros_i32(33),
        p_patch_edges_start_block=zeros_i32(33),
        p_patch_edges_end_block=zeros_i32(33),
        p_patch_verts_cell_idx=zeros_i32(nproma, nblks_v, 6),
        p_patch_verts_cell_blk=zeros_i32(nproma, nblks_v, 6),
        p_patch_verts_edge_idx=zeros_i32(nproma, nblks_v, 6),
        p_patch_verts_edge_blk=zeros_i32(nproma, nblks_v, 6),
        p_patch_verts_start_index=zeros_i32(33),
        p_patch_verts_end_index=zeros_i32(33),
        p_patch_verts_start_block=zeros_i32(33),
        p_patch_verts_end_block=zeros_i32(33),
        p_int_c_lin_e=zeros_f64(nproma, 2, nblks_e),
        p_int_e_bln_c_s=zeros_f64(nproma, 3, nblks_c),
        p_int_cells_aw_verts=zeros_f64(nproma, 6, nblks_v),
        p_int_rbf_vec_coeff_e=zeros_f64(4, nproma, nblks_e),
        p_int_geofac_grdiv=zeros_f64(nproma, 5, nblks_e),
        p_int_geofac_rot=zeros_f64(nproma, 6, nblks_v),
        p_int_geofac_n2s=zeros_f64(nproma, 4, nblks_c),
        p_prog_w=zeros_f64(nproma, nlevp1, nblks_c),
        p_prog_vn=zeros_f64(nproma, nlev, nblks_e),
        p_diag_vn_ie_ubc=zeros_f64(nproma, 2, nblks_e),
        p_diag_vt=zeros_f64(nproma, nlev, nblks_e),
        p_diag_vn_ie=zeros_f64(nproma, nlevp1, nblks_e),
        p_diag_w_concorr_c=zeros_f64(nproma, nlev, nblks_c),
        p_diag_ddt_vn_apc_pc=zeros_f64(nproma, nlev, nblks_e, 3),
        p_diag_ddt_vn_cor_pc=zeros_f64(nproma, nlev, nblks_e, 3),
        p_diag_ddt_w_adv_pc=zeros_f64(nproma, nlevp1, nblks_c, 3),
        p_metrics_ddxn_z_full=zeros_f64(nproma, nlev, nblks_e),
        p_metrics_ddxt_z_full=zeros_f64(nproma, nlev, nblks_e),
        p_metrics_ddqz_z_full_e=zeros_f64(nproma, nlev, nblks_e),
        p_metrics_ddqz_z_half=zeros_f64(nproma, nlevp1, nblks_c),
        p_metrics_wgtfac_c=zeros_f64(nproma, nlevp1, nblks_c),
        p_metrics_wgtfac_e=zeros_f64(nproma, nlevp1, nblks_e),
        p_metrics_wgtfacq_e=zeros_f64(nproma, 3, nblks_e),
        p_metrics_coeff_gradekin=zeros_f64(nproma, 2, nblks_e),
        p_metrics_coeff1_dwdz=zeros_f64(nproma, nlev, nblks_c),
        p_metrics_coeff2_dwdz=zeros_f64(nproma, nlev, nblks_c),
        p_metrics_deepatmo_gradh_mc=zeros_f64(nlev),
        p_metrics_deepatmo_invr_mc=zeros_f64(nlev),
        p_metrics_deepatmo_gradh_ifc=zeros_f64(nlevp1),
        p_metrics_deepatmo_invr_ifc=zeros_f64(nlevp1),
    )
