# Copyright 2025-2026 ETH Zurich and the dace-fortran authors. All rights reserved.
# SPDX-License-Identifier: GPL-3.0-or-later
"""Static types of the ``hlfir_bridge`` extension (``bridge/bridge.cpp``).

The extension is a nanobind module built at first use, so its classes cannot be named in annotations.  These
protocols mirror the bound fields and methods the emitter reads; the emitter-side stand-ins in
:mod:`dace_fortran.builder.records` satisfy the same protocols.
"""

from __future__ import annotations

from typing import Any, Protocol, Sequence


class VarRecord(Protocol):
    """Bridge ``VarInfo``: one classified Fortran variable."""

    @property
    def fortran_name(self) -> str: ...

    @property
    def mangled_name(self) -> str: ...

    @property
    def intent(self) -> str: ...

    @property
    def rank(self) -> int: ...

    @property
    def dtype(self) -> str: ...

    @property
    def is_dynamic(self) -> bool: ...

    @property
    def is_written(self) -> bool: ...

    @property
    def shape_symbols(self) -> Sequence[str]: ...

    @property
    def lower_bounds(self) -> Sequence[str]: ...

    @property
    def role(self) -> str: ...

    @property
    def const_data(self) -> bool: ...

    @property
    def view_source(self) -> str: ...

    @property
    def view_subset(self) -> Sequence[str]: ...

    @property
    def view_dim_map(self) -> Sequence[str]: ...

    @property
    def module_origin_mod(self) -> str: ...

    @property
    def module_origin_name(self) -> str: ...

    @property
    def module_origin_allocatable(self) -> bool: ...

    @property
    def module_origin_pointer(self) -> bool: ...

    @property
    def bounds_remap_view(self) -> bool: ...

    @property
    def bounds_remap_source(self) -> str: ...

    @property
    def bounds_remap_total_extent(self) -> str: ...

    @property
    def bounds_remap_source_subset(self) -> Sequence[str]: ...

    @property
    def unbindable_section(self) -> bool: ...

    @property
    def aos_origin_mod(self) -> str: ...

    @property
    def aos_origin_struct(self) -> str: ...

    @property
    def aos_member_path(self) -> str: ...

    @property
    def aos_outer_rank(self) -> int: ...

    @property
    def global_alloc_inside(self) -> bool: ...

    @property
    def aos_struct_pointer(self) -> bool: ...

    @property
    def aos_member_pointer(self) -> bool: ...


class AccessRecord(Protocol):
    """Bridge ``AccessInfo``: one array access of a statement."""

    @property
    def array_name(self) -> str: ...

    @property
    def index_vars(self) -> Sequence[str]: ...

    @property
    def index_exprs(self) -> Sequence[str]: ...

    @property
    def is_read(self) -> bool: ...

    @property
    def is_write(self) -> bool: ...


class NodeRecord(Protocol):
    """Bridge ``ASTNode``: one statement of the lowered routine body."""

    @property
    def kind(self) -> str: ...

    @property
    def loop_iter(self) -> str: ...

    @property
    def loop_bound(self) -> str: ...

    @property
    def loop_lower(self) -> int: ...

    @property
    def loop_lower_expr(self) -> str: ...

    @property
    def loop_step(self) -> int: ...

    @property
    def loop_step_expr(self) -> str: ...

    @property
    def target(self) -> str: ...

    @property
    def expr(self) -> str: ...

    @property
    def accesses(self) -> Sequence[AccessRecord]: ...

    @property
    def pos_indices(self) -> Sequence[int]: ...

    @property
    def target_is_array(self) -> bool: ...

    @property
    def condition(self) -> str: ...

    @property
    def callee(self) -> str: ...

    @property
    def call_args(self) -> Sequence[str]: ...

    @property
    def call_arg_subsets(self) -> Sequence[str]: ...

    @property
    def aos_marshal_groups(self) -> Sequence[int]: ...

    @property
    def reduce_src(self) -> str: ...

    @property
    def reduce_wcr(self) -> str: ...

    @property
    def reduce_identity(self) -> str: ...

    @property
    def reduce_axes(self) -> Sequence[int]: ...

    @property
    def options(self) -> dict[str, Any]: ...

    @property
    def children(self) -> Sequence[NodeRecord]: ...

    @property
    def else_children(self) -> Sequence[NodeRecord]: ...


class HlfirModule(Protocol):
    """Bridge ``HLFIRModule``: parse + rewrite pipeline + extraction."""

    def parse_file(self, path: str) -> bool: ...

    def parse_files(self, paths: Sequence[str]) -> bool: ...

    def run_passes(self, pipeline: str) -> None: ...

    def get_variables(self) -> list[VarRecord]: ...

    def get_value_symbols(self) -> list[Any]: ...

    def get_ast(self) -> list[NodeRecord]: ...

    def list_functions(self) -> list[str]: ...

    def set_entry_symbol(self, entry: str) -> None: ...

    def externalize_symbols(self, names: Sequence[str]) -> list[str]: ...

    def set_external_symbols(self, names: Sequence[str]) -> None: ...

    def set_stub_symbols(self, names: Sequence[str]) -> None: ...

    def get_fortran_interface(self, entry: str) -> Any: ...

    def get_flatten_plan(self) -> Any: ...
