"""Insert the ICON OpenACC/OpenMP directives into the inlined velocity TU.

Anchors are (1-based original line, expected prefix) so an upstream TU change
fails loudly instead of silently mis-placing a directive.

Usage: annotate_velocity_acc.py [<inlined_tu.f90> <annotated.f90>]
"""
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
SRC = Path(sys.argv[1]) if len(sys.argv) > 1 else \
    REPO / "tests" / "icon" / "atmosphere" / "velocity_advection_inlined_single_tu.f90"
DST = Path(sys.argv[2]) if len(sys.argv) > 2 else \
    REPO / "samples" / "velocity_tendencies" / "velocity_advection_acc.f90"

HEADER = """\
! OpenACC/OpenMP-annotated twin of tests/icon/atmosphere/velocity_advection_inlined_single_tu.f90,
! for the Fortran baseline lanes only (samples/velocity_tendencies/baselines.sh).  GENERATED by
! scripts/annotate_velocity_acc.py -- edit that, not this.
!
! Why a twin and not in-place directives: tests/icon/atmosphere/test_extract_single_tu.py asserts the
! committed TU is BYTE-IDENTICAL to the fparser extractor output, and the extractor drops comments.
!
! Directives ported from ICON's tests/icon/full/icon-model/src/atm_dyn_iconam/mo_velocity_advection.f90
! (main kernel) plus externals/iconmath mo_lib_divrot.F90 / mo_lib_interpolation_scalar.F90 (the two
! inlined lib routines), mapped by loop variable + array names.  Deliberate deviations:
!   * DATA uses PRESENT, not ICON's COPYIN, for z_w_concorr_me/z_kin_hor_e/z_vt_ie.  Either way it
!     is a present-hit: driver_velocity.f90 stages them, like solve_nh's data region does in ICON.
!   * PRESENT(iqidx, ...) dropped: the extractor flattened those pointer aliases into
!     p_patch % edges % quad_idx etc.
!   * IF(lzacc) dropped from the two lib routines: the extractor degraded set_acc_host_or_device to
!     lzacc = .FALSE., while every call site passes lacc = .TRUE.
!   * The extractor kept the #ifndef _OPENACC arm of ICON's cpp, so the vt loop and the
!     vn_ie/z_kin_hor_e loop are separate here and get one PARALLEL region each instead of ICON's
!     fused GPU form; likewise the CFL-clipping nest keeps its clip_count short-circuit and is
!     GANG-over-jk with two VECTOR loops rather than COLLAPSE(2).
!   * ICON_OMP_DEFAULT_SCHEDULE expanded to SCHEDULE(guided) (src/include/omp_definitions.inc).
"""

ACCP = "      !$ACC PARALLEL DEFAULT(PRESENT) ASYNC(1)"
ACCE = "      !$ACC END PARALLEL"

# (line, where, expected_prefix, [directive lines]) -- where is "before" or "after".
INS = [
    # --- rot_vertex_ri_lib -----------------------------------------------------
    (125, "before", "    DO jb = i_startblk, i_endblk", [
        "!$OMP PARALLEL",
        "!$OMP DO PRIVATE(jb, jv, jk, i_startidx, i_endidx) SCHEDULE(guided)",
    ]),
    (127, "before", "      DO jv = i_startidx, i_endidx", [
        "      !$ACC PARALLEL DEFAULT(PRESENT) ASYNC(1)",
        "      !$ACC LOOP GANG VECTOR COLLAPSE(2)",
    ]),
    (131, "after", "      END DO", ["      !$ACC END PARALLEL"]),
    (132, "after", "    END DO", ["!$OMP END DO NOWAIT", "!$OMP END PARALLEL"]),
    # --- cells2verts_scalar_ri_lib --------------------------------------------
    (159, "before", "    DO jb = i_startblk, i_endblk", [
        "!$OMP PARALLEL",
        "!$OMP DO PRIVATE(jb, jv, jk, i_startidx, i_endidx) SCHEDULE(guided)",
    ]),
    (161, "before", "      DO jv = i_startidx, i_endidx", [
        "      !$ACC PARALLEL DEFAULT(PRESENT) ASYNC(1)",
        "      !$ACC LOOP GANG VECTOR COLLAPSE(2)",
    ]),
    (165, "after", "      END DO", ["      !$ACC END PARALLEL"]),
    (166, "after", "    END DO", ["!$OMP END DO NOWAIT", "!$OMP END PARALLEL"]),
    # --- velocity_tendencies: data region -------------------------------------
    (469, "before", "    IF (lextra_diffu) THEN", [
        "    !$ACC DATA CREATE(z_w_concorr_mc, z_w_con_c, cfl_clipping, z_w_con_c_full, z_v_grad_w) &",
        "    !$ACC   CREATE(z_w_v, zeta, z_ekinh, levmask, levelmask) &",
        "    !$ACC   PRESENT(z_w_concorr_me, z_kin_hor_e, z_vt_ie) &",
        "    !$ACC   PRESENT(p_diag, p_prog, p_int, p_metrics, p_patch)",
    ]),
    (478, "before", "    IF (istep == 1) THEN", [
        "!$OMP PARALLEL PRIVATE(rl_start, rl_end, i_startblk, i_endblk, rl_start_2, rl_end_2, i_startblk_2, "
        "i_endblk_2)",
    ]),
    # istep==1 edge block
    (483, "before", "      DO jb = i_startblk, i_endblk",
     ["!$OMP DO PRIVATE(jb, jk, je, i_startidx, i_endidx) SCHEDULE(guided)"]),
    (485, "before", "        DO je = i_startidx, i_endidx", [
        "        !$ACC PARALLEL DEFAULT(PRESENT) ASYNC(1)",
        "        !$ACC LOOP GANG VECTOR TILE(128, 1)",
    ]),
    (489, "after", "        END DO", ["        !$ACC END PARALLEL"]),
    (490, "before", "        DO jk = 2, nlev", [
        "        !$ACC PARALLEL DEFAULT(PRESENT) ASYNC(1)",
        "        !$ACC LOOP GANG VECTOR COLLAPSE(2)",
    ]),
    (495, "after", "        END DO", ["        !$ACC END PARALLEL"]),
    (497, "before", "          DO jk = 2, nlev", [
        "          !$ACC PARALLEL DEFAULT(PRESENT) ASYNC(1)",
        "          !$ACC LOOP GANG VECTOR COLLAPSE(2)",
    ]),
    (501, "after", "          END DO", ["          !$ACC END PARALLEL"]),
    (503, "before", "        DO jk = nflatlev_jg, nlev", [
        "        !$ACC PARALLEL DEFAULT(PRESENT) ASYNC(1)",
        "        !$ACC LOOP GANG VECTOR COLLAPSE(2)",
    ]),
    (507, "after", "        END DO", ["        !$ACC END PARALLEL"]),
    (509, "before", "          DO je = i_startidx, i_endidx", [
        "          !$ACC PARALLEL DEFAULT(PRESENT) ASYNC(1)",
        "          !$ACC LOOP GANG VECTOR",
    ]),
    (514, "after", "          END DO", ["          !$ACC END PARALLEL"]),
    (516, "before", "          DO je = i_startidx, i_endidx", [
        "          !$ACC PARALLEL DEFAULT(PRESENT) ASYNC(1)",
        "          !$ACC LOOP GANG VECTOR",
    ]),
    (521, "after", "          END DO", ["          !$ACC END PARALLEL"]),
    (523, "after", "      END DO", ["!$OMP END DO"]),
    # z_v_grad_w block
    (530, "before", "      DO jb = i_startblk, i_endblk",
     ["!$OMP DO PRIVATE(jb, jk, je, i_startidx, i_endidx) SCHEDULE(guided)"]),
    (532, "before", "        DO je = i_startidx, i_endidx", [
        "        !$ACC PARALLEL DEFAULT(PRESENT) ASYNC(1)",
        "        !$ACC LOOP GANG VECTOR TILE(32, 4)",
    ]),
    (536, "after", "        END DO", ["        !$ACC END PARALLEL"]),
    (537, "after", "      END DO", ["!$OMP END DO"]),
    # deep-atmosphere z_v_grad_w correction
    (540, "before", "      DO jb = i_startblk, i_endblk",
     ["!$OMP DO PRIVATE(jb, jk, je, i_startidx, i_endidx) SCHEDULE(guided)"]),
    (542, "before", "        DO je = i_startidx, i_endidx", [
        "        !$ACC PARALLEL DEFAULT(PRESENT) ASYNC(1)",
        "        !$ACC LOOP GANG VECTOR TILE(32, 4)",
    ]),
    (546, "after", "        END DO", ["        !$ACC END PARALLEL"]),
    (547, "after", "      END DO", ["!$OMP END DO"]),
    # cell block
    (557, "before", "    DO jb = i_startblk, i_endblk", [
        "!$OMP DO PRIVATE(jb, jk, jc, i_startidx, i_endidx, i_startidx_2, i_endidx_2, z_w_con_c, &",
        "!$OMP            z_w_concorr_mc, difcoef, vcfl, maxvcfl, cfl_clipping, clip_count) SCHEDULE(guided)",
    ]),
    (559, "before", "      DO jc = i_startidx, i_endidx", [ACCP, "      !$ACC LOOP GANG VECTOR TILE(32, 4)"]),
    (563, "after", "      END DO", [ACCE]),
    (565, "before", "        DO jc = i_startidx, i_endidx", [
        "        !$ACC PARALLEL DEFAULT(PRESENT) ASYNC(1)",
        "        !$ACC LOOP GANG VECTOR TILE(32, 4)",
    ]),
    (569, "after", "        END DO", ["        !$ACC END PARALLEL"]),
    (570, "before", "        DO jk = nflatlev_jg + 1, nlev", [
        "        !$ACC PARALLEL DEFAULT(PRESENT) ASYNC(1)",
        "        !$ACC LOOP GANG VECTOR COLLAPSE(2)",
    ]),
    (574, "after", "        END DO", ["        !$ACC END PARALLEL"]),
    (576, "before", "      DO jk = 1, nlev", [ACCP, "      !$ACC LOOP GANG VECTOR COLLAPSE(2)"]),
    (580, "after", "      END DO", [ACCE]),
    (581, "before", "      DO jc = i_startidx, i_endidx", [ACCP, "      !$ACC LOOP GANG VECTOR"]),
    (583, "after", "      END DO", [ACCE]),
    (584, "before", "      DO jk = nlev, nflatlev_jg + 1, - 1", [ACCP, "      !$ACC LOOP GANG VECTOR COLLAPSE(2)"]),
    (588, "after", "      END DO", [ACCE]),
    (589, "before", "      DO jk = MAX(3, nrdmax_jg - 2), nlev - 3", [ACCP, "      !$ACC LOOP GANG VECTOR"]),
    (591, "after", "      END DO", [ACCE]),
    # CFL clipping: gang over jk, two vector loops, CYCLE keeps the CPU short-circuit
    (593, "before", "      DO jk = MAX(3, nrdmax_jg - 2), nlev - 3", [
        "      !$ACC PARALLEL DEFAULT(PRESENT) ASYNC(1) COPY(maxvcfl)",
        "      !$ACC LOOP GANG PRIVATE(clip_count) REDUCTION(MAX: maxvcfl)",
    ]),
    (595, "before", "        DO jc = i_startidx, i_endidx", ["        !$ACC LOOP VECTOR REDUCTION(+: clip_count)"]),
    (600, "before", "        DO jc = i_startidx, i_endidx",
     ["        !$ACC LOOP VECTOR PRIVATE(vcfl) REDUCTION(MAX: maxvcfl)"]),
    (612, "after", "      END DO", [ACCE]),
    (613, "before", "      DO jk = 1, nlev", [ACCP, "      !$ACC LOOP GANG VECTOR COLLAPSE(2)"]),
    (617, "after", "      END DO", [ACCE]),
    (618, "before", "      vcflmax(jb) = maxvcfl", ["      !$ACC WAIT"]),
    # vertical advection of w
    (622, "before", "      DO jk = 2, nlev", [ACCP, "      !$ACC LOOP GANG(STATIC: 1) VECTOR TILE(32, 4)"]),
    (627, "before", "      DO jc = i_startidx_2, i_endidx_2", ["      !$ACC LOOP GANG(STATIC: 1) VECTOR TILE(32, 4)"]),
    (631, "after", "      END DO", [ACCE]),
    (633, "before", "        DO jk = MAX(3, nrdmax_jg - 2), nlev - 3", [
        "        !$ACC PARALLEL DEFAULT(PRESENT) ASYNC(1)",
        "        !$ACC LOOP SEQ",
    ]),
    (635, "before", "            DO jc = i_startidx_2, i_endidx_2",
     ["            !$ACC LOOP GANG VECTOR PRIVATE(difcoef)"]),
    (642, "after", "        END DO", ["        !$ACC END PARALLEL"]),
    (644, "after", "    END DO", ["!$OMP END DO"]),
    (645, "before", "    DO jk = MAX(3, nrdmax_jg - 2), nlev - 3", [
        "    !$ACC PARALLEL DEFAULT(PRESENT) ASYNC(1)",
        "    !$ACC LOOP GANG VECTOR",
        "!$OMP DO PRIVATE(jk)",
    ]),
    (647, "after", "    END DO", ["!$OMP END DO", "    !$ACC END PARALLEL"]),
    # horizontal wind advection
    (652, "before", "    DO jb = i_startblk, i_endblk",
     ["!$OMP DO PRIVATE(jb, jk, je, i_startidx, i_endidx, ie, w_con_e, difcoef) SCHEDULE(guided)"]),
    (655, "before", "        DO je = i_startidx, i_endidx", [
        "        !$ACC PARALLEL DEFAULT(PRESENT) ASYNC(1)",
        "        !$ACC LOOP GANG VECTOR TILE(32, 4)",
    ]),
    (659, "after", "        END DO", ["        !$ACC END PARALLEL"]),
    (661, "before", "          DO jk = 1, nlev", [
        "          !$ACC PARALLEL DEFAULT(PRESENT) ASYNC(1)",
        "          !$ACC LOOP GANG VECTOR TILE(32, 4)",
    ]),
    (665, "after", "          END DO", ["          !$ACC END PARALLEL"]),
    (668, "before", "        DO je = i_startidx, i_endidx", [
        "        !$ACC PARALLEL DEFAULT(PRESENT) ASYNC(1)",
        "        !$ACC LOOP GANG VECTOR TILE(32, 4)",
    ]),
    (672, "after", "        END DO", ["        !$ACC END PARALLEL"]),
    (674, "before", "          DO jk = 1, nlev", [
        "          !$ACC PARALLEL DEFAULT(PRESENT) ASYNC(1)",
        "          !$ACC LOOP GANG VECTOR TILE(32, 4)",
    ]),
    (678, "after", "          END DO", ["          !$ACC END PARALLEL"]),
    (683, "before", "        DO jk = MAX(3, nrdmax_jg - 2), nlev - 4", [
        "        !$ACC PARALLEL DEFAULT(PRESENT) ASYNC(1)",
        "        !$ACC LOOP SEQ",
    ]),
    (685, "before", "            DO je = i_startidx, i_endidx",
     ["            !$ACC LOOP GANG VECTOR PRIVATE(difcoef, w_con_e)"]),
    (693, "after", "        END DO", ["        !$ACC END PARALLEL"]),
    (695, "after", "    END DO", ["!$OMP END DO", "!$OMP END PARALLEL", "    !$ACC WAIT"]),
    (699, "after", "    p_diag % max_vcfl_dyn = max_vcfl_dyn", ["    !$ACC END DATA"]),
]

lines = SRC.read_text().splitlines()
before: dict[int, list[str]] = {}
after: dict[int, list[str]] = {}
for lineno, where, expect, directives in INS:
    got = lines[lineno - 1]
    if not got.startswith(expect):
        raise SystemExit(f"anchor mismatch at line {lineno}: want {expect!r}, got {got!r}")
    (before if where == "before" else after).setdefault(lineno, []).extend(directives)

WIDTH = 118  # .fprettify.rc line-length 120, and nvfortran hard-stops free form at 1000 columns


def fold(line: str) -> list[str]:
    """Break one over-long statement at token boundaries with free-form continuations."""
    if len(line) <= WIDTH or line.lstrip().startswith("!"):
        return [line]
    if "'" in line or '"' in line:
        raise SystemExit(f"refusing to fold a line with a character literal: {line[:80]}...")
    indent = len(line) - len(line.lstrip())
    cont = " " * (indent + 2)
    out, cur, empty = [], " " * indent, True
    for word in line.split():
        if not empty and len(cur) + 1 + len(word) + 2 > WIDTH:
            out.append(cur + " &")
            cur, empty = cont + word, False
            continue
        cur, empty = (cur + word if empty else cur + " " + word), False
    out.append(cur)
    return out


out: list[str] = HEADER.splitlines()
for i, line in enumerate(lines, start=1):
    out.extend(before.get(i, ()))
    out.extend(fold(line))
    out.extend(after.get(i, ()))
DST.write_text("\n".join(out) + "\n")
ndirs = sum(len(v) for v in before.values()) + sum(len(v) for v in after.values())
print(f"wrote {DST}: {len(lines)} -> {len(out)} lines, {ndirs} directive lines")
