#!/usr/bin/env python3
"""Standalone driver: build the DaCe-backed ``libsolve_nh.so``
(and ICON-side wrapper) that a patched ICON atmosphere model links against.

Lifts the build steps out of ``tests/icon/full/test_dycore_from_icon_source.py``
and ``test_icon_solve_nh_swap.py`` so they can be run outside ``pytest``.

The SDFG is lowered from ICON's REAL ``mo_solve_nonhydro.f90`` so the binding's
flattened struct layout matches ICON's actual ``t_nh_state`` / ``t_patch`` /
``t_int_state`` / ``t_prepare_adv`` types.  ``velocity_tendencies`` is kept as
an external and resolves at ICON link time to the stock Fortran implementation.

Usage::

    python -m scripts.build_icon_solve_nh_libs \
        --icon-src tests/icon/full/icon-model \
        --icon-build tests/icon/full/icon-model/build/stock_cpu \
        --out-dir $WORK/solve-nh-dace-libs

See ``docs/ICON_INTEGRATION.md`` for the surrounding workflow.
"""
import argparse
import os
import shutil
import sys
from pathlib import Path

import dace

_DACE_FORTRAN = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(_DACE_FORTRAN / "tests"))
from _util import have_flang
from icon.full._icon_solve_nh_patch import SOLVE_NH_WRAPPER_NAME
from icon.full.test_dycore_from_icon_source import (
    _ICON_DEFINES_FALLBACK,
    _ICON_EXTERNAL_STUBS,
)

import dace_fortran
from dace_fortran.bindings import build_fortran_library, FlattenPlan
from dace_fortran.bindings.fortran_interface import build_auto_interface

_RELEASE_FFLAGS = (
    "-O3",
    "-fno-fast-math",
    "-ffp-contract=off",
    "-ffree-line-length-none",
)

_DEBUG_FFLAGS = (
    "-O0",
    "-g",
    "-fno-fast-math",
    "-ffp-contract=off",
    "-ffree-line-length-none",
)

_RELEASE_CXX_FLAGS = (
    "-O3",
    "-fno-fast-math",
    "-ffp-contract=off",
    "-fPIC",
    "-Wno-unused-parameter",
    "-Wno-unused-label",
)

_DEBUG_CXX_FLAGS = (
    "-O0",
    "-g",
    "-fno-fast-math",
    "-ffp-contract=off",
    "-fPIC",
    "-Wno-unused-parameter",
    "-Wno-unused-label",
)

#: Fortran object target used to extract ICON's real compile flags.
_SOLVE_NH_TARGET = "src/atm_dyn_iconam/mo_solve_nonhydro.o"

#: ``module::procedure`` entry passed to ``build_sdfg_from_hlfir``.
_SOLVE_NH_ENTRY = "mo_solve_nonhydro::solve_nh"


def _real_source(icon_src: Path) -> Path:
    """Pristine ``mo_solve_nonhydro.f90``; prefer ``.bak`` when the live file
    has been patched."""
    src = icon_src / "src" / "atm_dyn_iconam" / "mo_solve_nonhydro.f90"
    bak = src.with_suffix(".f90.bak")
    return bak if bak.is_file() else src


def _icon_search_dirs(icon_src: Path) -> list:
    """Roots for the ``merge_used_modules`` search closure."""
    return [
        icon_src / "src",
        icon_src / "externals/fortran-support/src",
        icon_src / "externals/mtime/src",
        icon_src / "externals/iconmath/src",
        icon_src / "externals/cdi/src",
        icon_src / "externals/memman/src/bindings/fortran",
        icon_src / "support",
    ]


def _icon_compile_args(icon_src: Path, icon_build: Path) -> dict:
    """ICON's real ``-D`` / ``-I`` set when a configured build exists."""
    if (icon_build / "Makefile").is_file():
        return dace_fortran.extract_make_compile_args(makefile_dir=icon_build, target=_SOLVE_NH_TARGET)
    return {
        "defines": list(_ICON_DEFINES_FALLBACK),
        "include_dirs": [icon_src / "src/include"],
    }


def _icon_mod_dirs(icon_build: Path) -> list:
    """Every directory under the ICON build holding compiled ``.mod`` files."""
    return sorted({p.parent.resolve() for p in icon_build.rglob("*.mod")})


def _render_icon_wrapper() -> str:
    """Render a Fortran wrapper ``solve_nh_dace_icon`` that forwards to the
    SDFG-generated ``solve_nh_dace`` inside ``solve_nh_dace_bindings``.

    The wrapper signature matches ``tests/icon/full/_icon_solve_nh_patch.py``
    exactly so the patched ``mo_solve_nonhydro.f90`` INTERFACE block resolves.
    """
    name = SOLVE_NH_WRAPPER_NAME
    lines = [
        "! ICON-side wrapper: forwards to the SDFG-generated",
        "! ``solve_nh_dace`` under the free-standing name ``solve_nh_dace_icon``.",
        "! Generated by scripts/build_icon_solve_nh_libs.py -- do not edit.",
        f"SUBROUTINE {name}(p_nh, p_patch, p_int, prep_adv, &",
        "                                  nnow, nnew, &",
        "                                  l_init, l_recompute, lsave_mflx, &",
        "                                  lprep_adv, lclean_mflx, &",
        "                                  idyn_timestep, jstep, dtime, lacc)",
        "  USE iso_c_binding,     ONLY: c_int, c_double, c_bool",
        "  USE solve_nh_dace_bindings, ONLY: solve_nh_dace",
        "  USE mo_model_domain,   ONLY: t_patch",
        "  USE mo_intp_data_strc, ONLY: t_int_state",
        "  USE mo_nonhydro_types, ONLY: t_nh_state",
        "  USE mo_prepadv_types,  ONLY: t_prepare_adv",
        "  TYPE(t_nh_state),    TARGET, INTENT(INOUT) :: p_nh",
        "  TYPE(t_int_state),   TARGET, INTENT(IN)    :: p_int",
        "  TYPE(t_patch),       TARGET, INTENT(INOUT) :: p_patch",
        "  TYPE(t_prepare_adv), TARGET, INTENT(INOUT) :: prep_adv",
        "  INTEGER(c_int),              INTENT(IN)    :: nnow, nnew",
        "  LOGICAL(c_bool),             INTENT(IN)    :: l_init",
        "  LOGICAL(c_bool),             INTENT(IN)    :: l_recompute",
        "  LOGICAL(c_bool),             INTENT(IN)    :: lsave_mflx",
        "  LOGICAL(c_bool),             INTENT(IN)    :: lprep_adv",
        "  LOGICAL(c_bool),             INTENT(IN)    :: lclean_mflx",
        "  INTEGER(c_int),              INTENT(IN)    :: idyn_timestep",
        "  INTEGER(c_int),              INTENT(IN)    :: jstep",
        "  REAL(c_double),              INTENT(IN)    :: dtime",
        "  LOGICAL(c_bool),             INTENT(IN)    :: lacc",
        "  CALL solve_nh_dace(p_nh, p_patch, p_int, prep_adv, &",
        "                   nnow, nnew, &",
        "                   l_init, l_recompute, lsave_mflx, &",
        "                   lprep_adv, lclean_mflx, &",
        "                   idyn_timestep, jstep, dtime, lacc)",
        f"END SUBROUTINE {name}",
        "",
    ]
    return "\n".join(lines)


def build_solve_nh_sdfg(icon_src: Path, icon_build: Path, sdfg_dir: Path):
    """Lower ICON's REAL ``mo_solve_nonhydro.f90`` to an SDFG."""
    args = _icon_compile_args(icon_src, icon_build)
    print(
        f"[build_icon_solve_nh_libs] ICON defines from {icon_build}: {len(args['defines'])} -D, "
        f"{len(args['include_dirs'])} -I",
        flush=True,
    )
    entry_src = _real_source(icon_src)
    print(f"[build_icon_solve_nh_libs] real ICON solve_nh source: {entry_src}", flush=True)

    hlfir = dace_fortran.emit_hlfir_from_codebase(
        entry_source=entry_src.read_text(),
        out_path=sdfg_dir / "solve_nh.hlfir",
        search_dirs=_icon_search_dirs(icon_src),
        library_stubs=["mpi", "netcdf"],
        defines=args["defines"] + ["NO_MPI_CHOICE_ARG"],
        include_dirs=args["include_dirs"],
        cache_dir=Path(os.environ.get("DACE_FORTRAN_CACHE", str(Path.home() / ".cache" / "dace-fortran"))),
    )
    dace_fortran.clear_external_registry()
    dace_fortran.apply_external_functions(do_not_emit=_ICON_EXTERNAL_STUBS)
    try:
        return dace_fortran.build_sdfg_from_hlfir(hlfir, entry=_SOLVE_NH_ENTRY)
    finally:
        dace_fortran.clear_external_registry()


def build_solve_nh_binding(icon_src: Path, icon_build: Path, out_dir: Path, release: bool = False):
    """Build ``libsolve_nh.so`` from ICON's real ``mo_solve_nonhydro.f90``.

    The output directory receives the .so, the .mod
    (``solve_nh_dace_bindings.mod``), and the wrapper source.
    """
    out_dir = out_dir.resolve()
    out_dir.mkdir(parents=True, exist_ok=True)
    fflags = _RELEASE_FFLAGS if release else _DEBUG_FFLAGS
    cxx_flags = _RELEASE_CXX_FLAGS if release else _DEBUG_CXX_FLAGS

    print(f"[build_icon_solve_nh_libs] ICON source: {icon_src}", flush=True)
    print(f"[build_icon_solve_nh_libs] ICON build:  {icon_build}", flush=True)
    print(f"[build_icon_solve_nh_libs] output dir:  {out_dir}", flush=True)
    print(f"[build_icon_solve_nh_libs] mode:        {'release' if release else 'debug'}", flush=True)

    sdfg_dir = out_dir / "_sdfg_build"
    sdfg_dir.mkdir(parents=True, exist_ok=True)

    wrapper_f90 = out_dir / "solve_nh_icon_wrapper.f90"
    diff_f90 = _DACE_FORTRAN / "tests" / "icon" / "full" / "mo_solve_nh_diff.f90"

    orig_cxx_args = dace.Config.get("compiler", "cpu", "args")
    dace.Config.set("compiler", "cpu", "args", value=" ".join(cxx_flags))
    try:
        sdfg = build_solve_nh_sdfg(icon_src.resolve(), icon_build.resolve(), sdfg_dir)
        sdfg.name = "solve_nh"
        sdfg.build_folder = str(sdfg_dir / "dacecache")

        iface = build_auto_interface(sdfg._fortran_interface_raw, "solve_nh")
        plan = FlattenPlan.from_dict(sdfg._flatten_plan_raw or {})

        wrapper_f90.write_text(_render_icon_wrapper())
        icon_incs = tuple(f"-I{d}" for d in _icon_mod_dirs(icon_build))
        lib = build_fortran_library(
            sdfg,
            iface=iface,
            plan=plan,
            out_dir=str(out_dir),
            name="solve_nh",
            prelude_sources=[diff_f90],
            extra_sources=[wrapper_f90],
            bind_c_shim=False,
            flags=(*fflags, *icon_incs),
        )
    finally:
        dace.Config.set("compiler", "cpu", "args", value=orig_cxx_args)

    print(f"[build_icon_solve_nh_libs] artifact: {lib.so_path}", flush=True)
    return lib


def main():
    ap = argparse.ArgumentParser(description=__doc__.split("\n\n")[0],
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--icon-src", type=Path, required=True, help="ICON source tree (e.g. tests/icon/full/icon-model).")
    ap.add_argument("--icon-build",
                    type=Path,
                    required=True,
                    help="Build dir of the ICON CONFIGURATION this lib will be linked into.")
    ap.add_argument("--out-dir", type=Path, required=True, help="Where libsolve_nh.so + .mod files go.")
    ap.add_argument("--release", action="store_true", help="Use -O3 -fno-fast-math -ffp-contract=off instead of -O0.")
    args = ap.parse_args()

    if not shutil.which("gfortran") or not have_flang():
        print("error: need gfortran + an LLVM flang on PATH", file=sys.stderr)
        return 1
    if not (args.icon_build / "Makefile").is_file():
        print(f"error: no ICON build at {args.icon_build} (expected a configured Makefile)", file=sys.stderr)
        return 1

    build_solve_nh_binding(args.icon_src, args.icon_build, args.out_dir, release=args.release)
    return 0


if __name__ == "__main__":
    sys.exit(main())
