! (C) Copyright 1988- ECMWF.
!
! This software is licensed under the terms of the Apache Licence Version 2.0
! which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
!
! In applying this licence, ECMWF does not waive the privileges and immunities
! granted to it by virtue of its status as an intergovernmental organisation
! nor does it submit to any jurisdiction.

MODULE CLOUDSC_OUTPUT_MOD
  !
  ! Simple HDF5 output for CLOUDSC prognostic fields.
  ! Writes PT, PQ, PA, PCLV at each timestep into a single HDF5 file
  ! with groups /step_0001, /step_0002, etc.
  !

  USE PARKIND1, ONLY: JPIM, JPRB, JPRD, JPRL
  USE HDF5
  USE ISO_C_BINDING, ONLY: C_PTR, C_LOC

  IMPLICIT NONE

  PRIVATE
  PUBLIC :: CLOUDSC_OUTPUT_OPEN, CLOUDSC_OUTPUT_WRITE_STEP, CLOUDSC_OUTPUT_CLOSE

  INTEGER(HID_T) :: OUT_FILE_ID
  LOGICAL :: OUT_IS_OPEN = .FALSE.

CONTAINS

  SUBROUTINE CLOUDSC_OUTPUT_OPEN(FILENAME)
    CHARACTER(LEN=*), INTENT(IN) :: FILENAME
    INTEGER :: IERR

    CALL H5OPEN_F(IERR)
    CALL H5FCREATE_F(FILENAME, H5F_ACC_TRUNC_F, OUT_FILE_ID, IERR)
    IF (IERR /= 0) THEN
      WRITE(0,*) 'ERROR: Failed to create output file: ', TRIM(FILENAME)
      RETURN
    END IF
    OUT_IS_OPEN = .TRUE.
    WRITE(0,'(1X,A,A)') 'Output file created: ', TRIM(FILENAME)
  END SUBROUTINE CLOUDSC_OUTPUT_OPEN

  SUBROUTINE CLOUDSC_OUTPUT_WRITE_STEP(JSTEP, NPROMA, NLEV, NCLV, NBLOCKS, &
    & PT, PQ, PA, PCLV)
    INTEGER(KIND=JPIM), INTENT(IN) :: JSTEP, NPROMA, NLEV, NCLV, NBLOCKS
    REAL(KIND=JPRB), INTENT(IN), TARGET :: PT(NPROMA, NLEV, NBLOCKS)
    REAL(KIND=JPRB), INTENT(IN), TARGET :: PQ(NPROMA, NLEV, NBLOCKS)
    REAL(KIND=JPRB), INTENT(IN), TARGET :: PA(NPROMA, NLEV, NBLOCKS)
    REAL(KIND=JPRL), INTENT(IN), TARGET :: PCLV(NPROMA, NLEV, NCLV, NBLOCKS)

    INTEGER(HID_T) :: GRP_ID
    CHARACTER(LEN=20) :: GRP_NAME
    INTEGER :: IERR

    IF (.NOT. OUT_IS_OPEN) RETURN

    ! Create group for this step
    WRITE(GRP_NAME, '(A,I4.4)') 'step_', JSTEP
    CALL H5GCREATE_F(OUT_FILE_ID, TRIM(GRP_NAME), GRP_ID, IERR)

    ! Write 3D fields (NPROMA, NLEV, NBLOCKS)
    CALL WRITE_FIELD_3D(GRP_ID, 'PT', PT, NPROMA, NLEV, NBLOCKS)
    CALL WRITE_FIELD_3D(GRP_ID, 'PQ', PQ, NPROMA, NLEV, NBLOCKS)
    CALL WRITE_FIELD_3D(GRP_ID, 'PA', PA, NPROMA, NLEV, NBLOCKS)

    ! Write 4D field (NPROMA, NLEV, NCLV, NBLOCKS)
    CALL WRITE_FIELD_4D(GRP_ID, 'PCLV', PCLV, NPROMA, NLEV, NCLV, NBLOCKS)

    CALL H5GCLOSE_F(GRP_ID, IERR)

  END SUBROUTINE CLOUDSC_OUTPUT_WRITE_STEP

  SUBROUTINE CLOUDSC_OUTPUT_CLOSE()
    INTEGER :: IERR
    IF (OUT_IS_OPEN) THEN
      CALL H5FCLOSE_F(OUT_FILE_ID, IERR)
      OUT_IS_OPEN = .FALSE.
      WRITE(0,'(1X,A)') 'Output file closed.'
    END IF
  END SUBROUTINE CLOUDSC_OUTPUT_CLOSE

  ! --- Internal helpers ---

  SUBROUTINE WRITE_FIELD_3D(GRP_ID, NAME, FIELD, N1, N2, N3)
    ! Always writes as FP64 in HDF5 — avoids HDF5 lacking FP16 type support
    ! and the compare script reads as float64 anyway.
    INTEGER(HID_T), INTENT(IN) :: GRP_ID
    CHARACTER(LEN=*), INTENT(IN) :: NAME
    INTEGER(KIND=JPIM), INTENT(IN) :: N1, N2, N3
    REAL(KIND=JPRB), INTENT(IN) :: FIELD(N1, N2, N3)

    INTEGER(HID_T) :: DSPACE_ID, DSET_ID, TYPE_ID
    INTEGER(HSIZE_T) :: DIMS(3)
    INTEGER :: IERR
    TYPE(C_PTR) :: PTR
    REAL(KIND=JPRD), ALLOCATABLE, TARGET :: BUF(:,:,:)

    DIMS = (/ INT(N1, HSIZE_T), INT(N2, HSIZE_T), INT(N3, HSIZE_T) /)
    TYPE_ID = H5KIND_TO_TYPE(JPRD, H5_REAL_KIND)

    ALLOCATE(BUF(N1, N2, N3))
    BUF = REAL(FIELD, JPRD)
    PTR = C_LOC(BUF(1,1,1))

    CALL H5SCREATE_SIMPLE_F(3, DIMS, DSPACE_ID, IERR)
    CALL H5DCREATE_F(GRP_ID, NAME, TYPE_ID, DSPACE_ID, DSET_ID, IERR)
    CALL H5DWRITE_F(DSET_ID, TYPE_ID, PTR, IERR)
    CALL H5DCLOSE_F(DSET_ID, IERR)
    CALL H5SCLOSE_F(DSPACE_ID, IERR)
    DEALLOCATE(BUF)
  END SUBROUTINE WRITE_FIELD_3D

  SUBROUTINE WRITE_FIELD_4D(GRP_ID, NAME, FIELD, N1, N2, N3, N4)
    INTEGER(HID_T), INTENT(IN) :: GRP_ID
    CHARACTER(LEN=*), INTENT(IN) :: NAME
    INTEGER(KIND=JPIM), INTENT(IN) :: N1, N2, N3, N4
    REAL(KIND=JPRL), INTENT(IN) :: FIELD(N1, N2, N3, N4)

    INTEGER(HID_T) :: DSPACE_ID, DSET_ID, TYPE_ID
    INTEGER(HSIZE_T) :: DIMS(4)
    INTEGER :: IERR
    TYPE(C_PTR) :: PTR
    REAL(KIND=JPRD), ALLOCATABLE, TARGET :: BUF(:,:,:,:)

    DIMS = (/ INT(N1, HSIZE_T), INT(N2, HSIZE_T), INT(N3, HSIZE_T), INT(N4, HSIZE_T) /)
    TYPE_ID = H5KIND_TO_TYPE(JPRD, H5_REAL_KIND)

    ALLOCATE(BUF(N1, N2, N3, N4))
    BUF = REAL(FIELD, JPRD)
    PTR = C_LOC(BUF(1,1,1,1))

    CALL H5SCREATE_SIMPLE_F(4, DIMS, DSPACE_ID, IERR)
    CALL H5DCREATE_F(GRP_ID, NAME, TYPE_ID, DSPACE_ID, DSET_ID, IERR)
    CALL H5DWRITE_F(DSET_ID, TYPE_ID, PTR, IERR)
    CALL H5DCLOSE_F(DSET_ID, IERR)
    CALL H5SCLOSE_F(DSPACE_ID, IERR)
    DEALLOCATE(BUF)
  END SUBROUTINE WRITE_FIELD_4D

END MODULE CLOUDSC_OUTPUT_MOD
