"""Emit sbatch scripts for daint.alps + beverin from a JSON config.

Reads a JSON config (see ``tools/submissions/example.json``) and emits
one ``run_<experiment>_<platform>.sh`` per (experiment x platform) cell
under ``--out-dir``. Each emitted script is fully self-contained: it
re-loads the spack toolchain via the activate.sh that ships with the
SC26 AD harness, sets the platform-specific env, then invokes
``python -m utils.stages.stage<N> <flags>`` per config in the
experiment's ``configs`` list.

Schema (top-level keys):

    defaults:    dict of fields inherited by every experiment
                 (stage, stage_flags, reps, configs, time, account,
                  pipeline_dir, results_subdir)
    platforms:   dict[str, platform_def] (must include 'daint' and/or 'beverin')
    experiments: list of experiment defs (each may override defaults)

A platform_def supports:

    partition, cpus_per_task, gpus_per_task, time, account,
    extra_setup (list of shell lines, e.g. spack loads),
    env (dict[str, str] of name=value to export),
    activate_path (default: ``../../SC26-Layout-AD/Experiments/common/activate.sh``)

Per-experiment overrides take precedence over defaults; defaults take
precedence over platform-level fields.

Usage:

    python tools/generate_submissions.py \
        --config tools/submissions/example.json \
        --out-dir submissions/

The emitted scripts are sbatch-ready; ``cd`` into ``--out-dir`` and run
``sbatch run_<experiment>_<platform>.sh``.
"""

import argparse
import json
import os
import stat
from pathlib import Path
from string import Template


_PLATFORMS = ("daint", "beverin")


_HEADER_TEMPLATE = Template(
    """#!/usr/bin/env bash
#SBATCH --job-name=$jobname
#SBATCH --nodes=1
#SBATCH --partition=$partition
#SBATCH --time=$time
$account_line#SBATCH --ntasks=1
#SBATCH --gpus-per-task=$gpus_per_task
#SBATCH --cpus-per-task=$cpus_per_task
#SBATCH --exclusive
#SBATCH --chdir=.
#SBATCH --output=$results_dir/%x_%j.out
#SBATCH --error=$results_dir/%x_%j.err
#
# Auto-generated by tools/generate_submissions.py from $config_src.
# Do NOT edit by hand -- re-run the generator instead.

set -euo pipefail

EXP_DIR="$${SLURM_SUBMIT_DIR:-$$(cd "$$(dirname "$${BASH_SOURCE[0]}")" && pwd)}"

# Activate the spack-python venv and pin DaCe to the requested branch.
ACTIVATE_PATH="$${ACTIVATE_PATH:-$activate_path}"
if [[ -f "$${ACTIVATE_PATH}" ]]; then
  # shellcheck disable=SC1090
  source "$${ACTIVATE_PATH}"
else
  echo "[$jobname] activate.sh not found at $${ACTIVATE_PATH}" >&2
  echo "[$jobname]   override via ACTIVATE_PATH=<path>" >&2
  exit 1
fi

"""
)


def _expand(value, env=None):
    if isinstance(value, str):
        return os.path.expandvars(value) if env is None else Template(value).safe_substitute(env)
    return value


def _platform_setup(platform: str, plat_cfg: dict) -> str:
    lines = []
    for line in plat_cfg.get("extra_setup", []) or []:
        lines.append(line)
    for k, v in (plat_cfg.get("env", {}) or {}).items():
        lines.append(f'export {k}="{v}"')
    if lines:
        return "# --- platform setup (" + platform + ") ---\n" + "\n".join(lines) + "\n\n"
    return ""


def _experiment_body(exp: dict, defaults: dict, platform: str) -> str:
    stage = exp.get("stage", defaults.get("stage", 6))
    stage_flags = exp.get("stage_flags", defaults.get("stage_flags", "--optimize --compile"))
    configs = exp.get("configs", defaults.get("configs", []))
    pipeline_dir = exp.get("pipeline_dir", defaults.get("pipeline_dir", "$HOME/Work/VelocityTendenciesPipeline"))
    results_subdir = exp.get("results_subdir", defaults.get("results_subdir", "results"))

    lines = [
        f'PIPELINE_DIR="${{PIPELINE_DIR:-{pipeline_dir}}}"',
        'if [[ ! -d "${PIPELINE_DIR}" ]]; then',
        f'  echo "[{exp["name"]}/{platform}] PIPELINE_DIR=${{PIPELINE_DIR}} not found" >&2',
        '  exit 1',
        'fi',
        '',
        f'RESULTS_DIR="${{EXP_DIR}}/{results_subdir}/{platform}/{exp["name"]}"',
        'mkdir -p "${RESULTS_DIR}"',
        '',
        'cd "${PIPELINE_DIR}"',
        '',
    ]

    if not configs:
        lines.append(f'python -m utils.stages.stage{stage} {stage_flags}')
    else:
        for cfg in configs:
            cfg_clean = str(cfg).strip()
            if cfg_clean == "full_sweep":
                lines.append(f'python -m utils.stages.stage{stage} {stage_flags}')
            else:
                lines.append(f'python -m utils.stages.stage{stage} {stage_flags} --config "{cfg_clean}"')

    # Copy CSVs from PIPELINE_DIR/codegen/stage<N>/ into RESULTS_DIR/<config>/
    lines += [
        '',
        f'STAGE_OUT_DIR="${{PIPELINE_DIR}}/codegen/stage{stage}"',
        'if [[ -d "${STAGE_OUT_DIR}" ]]; then',
        '  for d in "${STAGE_OUT_DIR}"/*/; do',
        '    cfg="$(basename "${d}")"',
        '    mkdir -p "${RESULTS_DIR}/${cfg}"',
        '    find "${d}" -maxdepth 2 -name \'*.csv\' -exec cp -v {} "${RESULTS_DIR}/${cfg}/" \\;',
        '  done',
        'fi',
        '',
        f'echo "[{exp["name"]}/{platform}] done. CSVs under ${{RESULTS_DIR}}/<config>/"',
        '',
    ]
    return "\n".join(lines)


def _render(exp: dict, platform: str, plat_cfg: dict, defaults: dict, config_src: str) -> str:
    activate_default = "${EXP_DIR}/../SC26-Layout-AD/Experiments/common/activate.sh"
    header = _HEADER_TEMPLATE.substitute(
        jobname=f'{exp["name"]}_{platform}',
        partition=plat_cfg.get("partition", exp.get("partition", "normal")),
        time=exp.get("time", plat_cfg.get("time", defaults.get("time", "06:00:00"))),
        account_line=(
            f'#SBATCH --account={plat_cfg.get("account", defaults.get("account", ""))}\n'
            if (plat_cfg.get("account") or defaults.get("account"))
            else ""
        ),
        gpus_per_task=plat_cfg.get("gpus_per_task", 1),
        cpus_per_task=plat_cfg.get("cpus_per_task", 64),
        results_dir=f'{exp.get("results_subdir", defaults.get("results_subdir", "results"))}/{platform}/{exp["name"]}',
        config_src=config_src,
        activate_path=plat_cfg.get("activate_path", activate_default),
    )
    setup = _platform_setup(platform, plat_cfg)
    body = _experiment_body(exp, defaults, platform)
    return header + setup + body


def main(argv=None):
    argp = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    argp.add_argument("--config", required=True, help="JSON config path.")
    argp.add_argument(
        "--out-dir",
        default="submissions",
        help="Directory to write the per-(experiment, platform) sbatch scripts (default: submissions/).",
    )
    argp.add_argument(
        "--platforms",
        nargs="*",
        default=None,
        help=f"Subset of platforms to emit for. Default: every platform listed in the JSON. Known: {_PLATFORMS}.",
    )
    args = argp.parse_args(argv)

    cfg_path = Path(args.config).resolve()
    cfg = json.loads(cfg_path.read_text())

    defaults = cfg.get("defaults", {}) or {}
    platforms_cfg = cfg.get("platforms", {}) or {}
    experiments = cfg.get("experiments", []) or []

    requested = args.platforms or list(platforms_cfg.keys())
    unknown = [p for p in requested if p not in platforms_cfg]
    if unknown:
        raise SystemExit(f"[generate_submissions] unknown platform(s): {unknown}")

    out_dir = Path(args.out_dir).resolve()
    out_dir.mkdir(parents=True, exist_ok=True)

    written = []
    for exp in experiments:
        for platform in requested:
            plat_cfg = platforms_cfg[platform]
            content = _render(exp, platform, plat_cfg, defaults, str(cfg_path))
            out_path = out_dir / f'run_{exp["name"]}_{platform}.sh'
            out_path.write_text(content)
            mode = out_path.stat().st_mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH
            out_path.chmod(mode)
            written.append(out_path)
            print(f"[generate_submissions] wrote {out_path}")

    print(f"[generate_submissions] {len(written)} script(s) under {out_dir}")


if __name__ == "__main__":
    main()
