! (C) Copyright 1988- ECMWF.
!
! This software is licensed under the terms of the Apache Licence Version 2.0
! which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
!
! In applying this licence, ECMWF does not waive the privileges and immunities
! granted to it by virtue of its status as an intergovernmental organisation
! nor does it submit to any jurisdiction.

MODULE YOECLDP

USE PARKIND1,    ONLY : JPIM, JPRB, JPRL
USE FILE_IO_MOD, ONLY : LOAD_SCALAR, LOAD_ARRAY

IMPLICIT NONE

SAVE

!     -----------------------------------------------------------------
!     ** YOECLDP - CONTROL PARAMETERS FOR PROGNOSTIC CLOUD SCHEME
!     -----------------------------------------------------------------

!     * E.C.M.W.F. PHYSICS PACKAGE *

!     C. JAKOB     E.C.M.W.F.    94/02/07
!     A. Tompkins  E.C.M.W.F.  2004/12/03 total water variance setup for
!                                                  moist advection-diffusion PBL
!     A. Tompkins  E.C.M.W.F.  2004/09/02 Aerosol in microphysics switches
!     JJMorcrette  ECMWF       20100813   Aerosol index for aerosol-cloud interactions
!     R. Forbes    ECMWF       20110301   Added ice deposition parameters
!     R. Forbes    ECMWF       20150115   Added additional ice, snow and rain parameters

!      NAME     TYPE      PURPOSE
!      ----     ----      -------

!     *RAMID*   REAL      BASE VALUE FOR CALCULATION OF RELATIVE 
!                         HUMIDITY THRESHOLD FOR ONSET OF STRATIFORM
!                         CONDENSATION (TIEDTKE, 1993, EQUATION 24)
!     *RCLDIFF* REAL      DIFFUSION-COEFFICIENT FOR EVAPORATION BY
!                         TURBULENT MIXING (IBID., EQU. 30)
!     *RCLDIFF_CONVI*REAL ENHANCEMENT FACTOR OF  RCLDIFF FOR CONVECTION
!     *RCLCRIT* REAL      BASE VALUE OF CRITICAL CLOUD WATER CONTENT 
!                         FOR CONVERSION TO RAIN (SUNDQUIST, 1988)
!     *RCLCRIT_SEA* REAL  BASE VALUE OF CRITICAL CLOUD WATER CONTENT FOR SEA
!     *RCLCRIT_LAND* REAL BASE VALUE OF CRITICAL CLOUD WATER CONTENT FOR LAND
!     *RKCONV*  REAL      BASE VALUE FOR CONVERSION COEFFICIENT (IBID.)
!     *RPRC1*   REAL      COALESCENCE CONSTANT (IBID.)
!     *RPRC2*   REAL      BERGERON-FINDEISEN CONSTANT (IBID.)
!     *RCLDMAX* REAL      MAXIMUM CLOUD WATER CONTENT
!     *RPECONS* REAL      EVAPORATION CONSTANT AFTER KESSLER 
!                         (TIEDTKE, 1993, EQU.35)
!     *RPRECRHMAX* REAL   MAX THRESHOLD RH FOR EVAPORATION FOR ZERO COVER
!     *RTAUMEL* REAL      RELAXATION TIME FOR MELTING OF SNOW
!     *RAMIN*   REAL      LIMIT FOR A
!     *RLMIN*   REAL      LIMIT FOR L
!     *RKOOPTAU*  REAL    TIMESCALE FOR ICE SUPERSATURATION REMOVAL
!     *RVICE*     REAL    FIXED ICE FALLSPEED
!     *RVRAIN*    REAL    FIXED RAIN FALLSPEED
!     *RVSNOW*    REAL    FIXED SNOW FALLSPEED
!     *RTHOMO*    REAL    TEMPERATURE THRESHOLD FOR SPONTANEOUS FREEZING OF LIQUID DROPLETS
!     *RCOVPMIN*  REAL    MINIMUM PRECIPITATION COVERAGE REQUIRED FOR THE NEW PROGNOSTIC PRECIP
!     *RCLDTOPP*  REAL    TOP PRESSURE FOR CLOUD CALCULATION
!     *NCLDTOP*   INTEGER TOP LEVEL FOR CLOUD CALCULATION
!     *NSSOPT*  INTEGER   PARAMETRIZATION CHOICE FOR SUPERSATURATION
!     *NCLDDIAG*INTEGER   CONTROLS CLOUDSC DIAGNOSTICS IN PEXTRA
!     *NCLV*     INTEGER   NUMBER OF PROGNOSTIC EQUATIONS IN CLOUDSC 
!                         (INCLUDES WATER VAPOUR AS DUMMY VARIABLE) 
!      NAERCLD         INT  INDEX TO CONTROL SWITCHES FOR 
!                           AEROSOL-MICROPHYSICS INTERACTION, LAER*
!      NAECLxx         INT  INDEX OF GEMS AEROSOLS USED IN AEROSOL-CLOUD INTERACTIONS
!      RCCN            REAL DEFAULT CCN (CM-3)
!      RNICE           REAL DEFAULT ICE NUMBER CONCENTRATION (CM-3)
!      LAERLIQAUTOLSP  LOG  AEROSOLS AFFECT RAIN AUTOCONVERSION IN LSP
!      LAERLIQAUTOCP   LOG  AEROSOLS AFFECT RAIN AUTOCONVERSION IN CP
!      LAERLIQCOLL     LOG  AEROSOLS AFFECT RAIN COLLECTION 
!      LAERICESED      LOG  AEROSOLS AFFECT ICE SEDIMENTATION
!      LAERICEAUTO     LOG  AEROSOLS AFFECT ICE AUTOCONVERSION
!      RCCNOM          REAL CONSTANT IN MENON PARAM FOR ORGANIC MATTER -> CCN
!      RCCNSS          REAL CONSTANT IN MENON PARAM SEA SALT -> CCN
!      RCCNSU          REAL CONSTANT IN MENON PARAM FOR SULPHATE -> CCN
!      RCLDTOPCF       REAL Cloud fraction threshold that defines cloud top 
!      RDEPLIQREFRATE  REAL Fraction of deposition rate in cloud top layer
!      RDEPLIQREFDEPTH REAL Depth of supercooled liquid water layer (m)
!      RVRFACTOR       REAL KESSLER FACTOR=5.09E-3 FOR EVAPORATION OF CLEAR-SKY RAIN  (KESSLER,1969)

INTEGER(KIND=JPIM),PARAMETER :: NCLV=5      ! number of microphysics variables
INTEGER(KIND=JPIM),PARAMETER :: NCLDQL=1    ! liquid cloud water
INTEGER(KIND=JPIM),PARAMETER :: NCLDQI=2    ! ice cloud water
INTEGER(KIND=JPIM),PARAMETER :: NCLDQR=3    ! rain water
INTEGER(KIND=JPIM),PARAMETER :: NCLDQS=4    ! snow
INTEGER(KIND=JPIM),PARAMETER :: NCLDQV=5    ! vapour


TYPE :: TECLDP
REAL(KIND=JPRL) :: RAMID
REAL(KIND=JPRL) :: RCLDIFF
REAL(KIND=JPRL) :: RCLDIFF_CONVI
REAL(KIND=JPRL) :: RCLCRIT
REAL(KIND=JPRL) :: RCLCRIT_SEA
REAL(KIND=JPRL) :: RCLCRIT_LAND
REAL(KIND=JPRL) :: RKCONV
REAL(KIND=JPRL) :: RPRC1
REAL(KIND=JPRL) :: RPRC2
REAL(KIND=JPRL) :: RCLDMAX
REAL(KIND=JPRL) :: RPECONS
REAL(KIND=JPRL) :: RVRFACTOR
REAL(KIND=JPRL) :: RPRECRHMAX
REAL(KIND=JPRL) :: RTAUMEL
REAL(KIND=JPRL) :: RAMIN
REAL(KIND=JPRL) :: RLMIN
REAL(KIND=JPRL) :: RKOOPTAU
REAL(KIND=JPRL) :: RCLDTOPP
REAL(KIND=JPRL) :: RLCRITSNOW
REAL(KIND=JPRL) :: RSNOWLIN1
REAL(KIND=JPRL) :: RSNOWLIN2
REAL(KIND=JPRL) :: RICEHI1
REAL(KIND=JPRL) :: RICEHI2
REAL(KIND=JPRL) :: RICEINIT
REAL(KIND=JPRL) :: RVICE
REAL(KIND=JPRL) :: RVRAIN
REAL(KIND=JPRL) :: RVSNOW
REAL(KIND=JPRL) :: RTHOMO
REAL(KIND=JPRL) :: RCOVPMIN
REAL(KIND=JPRL) :: RCCN
REAL(KIND=JPRL) :: RNICE
REAL(KIND=JPRL) :: RCCNOM
REAL(KIND=JPRL) :: RCCNSS
REAL(KIND=JPRL) :: RCCNSU
REAL(KIND=JPRL) :: RCLDTOPCF
REAL(KIND=JPRL) :: RDEPLIQREFRATE
REAL(KIND=JPRL) :: RDEPLIQREFDEPTH
!--------------------------------------------------------
! Autoconversion/accretion (Khairoutdinov and Kogan 2000)
!--------------------------------------------------------
REAL(KIND=JPRL) :: RCL_KKAac
REAL(KIND=JPRL) :: RCL_KKBac
REAL(KIND=JPRL) :: RCL_KKAau
REAL(KIND=JPRL) :: RCL_KKBauq
REAL(KIND=JPRL) :: RCL_KKBaun
REAL(KIND=JPRL) :: RCL_KK_cloud_num_sea
REAL(KIND=JPRL) :: RCL_KK_cloud_num_land
!--------------------------------------------------------
! Ice
!--------------------------------------------------------
REAL(KIND=JPRL) :: RCL_AI
REAL(KIND=JPRL) :: RCL_BI
REAL(KIND=JPRL) :: RCL_CI
REAL(KIND=JPRL) :: RCL_DI
REAL(KIND=JPRL) :: RCL_X1I  ! SC2026: JPRL — value(s) exceed FP16 max
REAL(KIND=JPRL) :: RCL_X2I
REAL(KIND=JPRL) :: RCL_X3I
REAL(KIND=JPRL) :: RCL_X4I
REAL(KIND=JPRL) :: RCL_CONST1I
REAL(KIND=JPRL) :: RCL_CONST2I  ! SC2026: JPRL — value(s) exceed FP16 max
REAL(KIND=JPRL) :: RCL_CONST3I
REAL(KIND=JPRL) :: RCL_CONST4I
REAL(KIND=JPRL) :: RCL_CONST5I
REAL(KIND=JPRL) :: RCL_CONST6I
REAL(KIND=JPRL) :: RCL_APB1  ! SC2026: JPRL — value(s) exceed FP16 max
REAL(KIND=JPRL) :: RCL_APB2  ! SC2026: JPRL — value(s) exceed FP16 max
REAL(KIND=JPRL) :: RCL_APB3
!--------------------------------------------------------
! Snow
!--------------------------------------------------------
REAL(KIND=JPRL) :: RCL_AS
REAL(KIND=JPRL) :: RCL_BS
REAL(KIND=JPRL) :: RCL_CS
REAL(KIND=JPRL) :: RCL_DS
REAL(KIND=JPRL) :: RCL_X1S  ! SC2026: JPRL — value(s) exceed FP16 max
REAL(KIND=JPRL) :: RCL_X2S
REAL(KIND=JPRL) :: RCL_X3S
REAL(KIND=JPRL) :: RCL_X4S
REAL(KIND=JPRL) :: RCL_CONST1S
REAL(KIND=JPRL) :: RCL_CONST2S  ! SC2026: JPRL — value(s) exceed FP16 max
REAL(KIND=JPRL) :: RCL_CONST3S
REAL(KIND=JPRL) :: RCL_CONST4S
REAL(KIND=JPRL) :: RCL_CONST5S
REAL(KIND=JPRL) :: RCL_CONST6S
REAL(KIND=JPRL) :: RCL_CONST7S  ! SC2026: JPRL — value(s) exceed FP16 max
REAL(KIND=JPRL) :: RCL_CONST8S
!--------------------------------------------------------
! Rain
!--------------------------------------------------------
REAL(KIND=JPRL) :: RDENSWAT
REAL(KIND=JPRL) :: RDENSREF
REAL(KIND=JPRL) :: RCL_AR
REAL(KIND=JPRL) :: RCL_BR
REAL(KIND=JPRL) :: RCL_CR
REAL(KIND=JPRL) :: RCL_DR
REAL(KIND=JPRL) :: RCL_X1R
REAL(KIND=JPRL) :: RCL_X2R
REAL(KIND=JPRL) :: RCL_X4R
REAL(KIND=JPRL) :: RCL_KA273
REAL(KIND=JPRL) :: RCL_CDENOM1  ! SC2026: JPRL — value(s) exceed FP16 max
REAL(KIND=JPRL) :: RCL_CDENOM2  ! SC2026: JPRL — value(s) exceed FP16 max
REAL(KIND=JPRL) :: RCL_CDENOM3
REAL(KIND=JPRL) :: RCL_SCHMIDT
REAL(KIND=JPRL) :: RCL_DYNVISC
REAL(KIND=JPRL) :: RCL_CONST1R
REAL(KIND=JPRL) :: RCL_CONST2R  ! SC2026: JPRL — value(s) exceed FP16 max
REAL(KIND=JPRL) :: RCL_CONST3R
REAL(KIND=JPRL) :: RCL_CONST4R
REAL(KIND=JPRL) :: RCL_FAC1
REAL(KIND=JPRL) :: RCL_FAC2
! Rain freezing
REAL(KIND=JPRL) :: RCL_CONST5R  ! SC2026: JPRL — value(s) exceed FP16 max
REAL(KIND=JPRL) :: RCL_CONST6R
REAL(KIND=JPRL) :: RCL_FZRAB
REAL(KIND=JPRL) :: RCL_FZRBB

LOGICAL :: LCLDEXTRA, LCLDBUDGET

INTEGER(KIND=JPIM) :: NSSOPT
INTEGER(KIND=JPIM) :: NCLDTOP
INTEGER(KIND=JPIM) :: NAECLBC, NAECLDU, NAECLOM, NAECLSS, NAECLSU
INTEGER(KIND=JPIM) :: NCLDDIAG

! aerosols
INTEGER(KIND=JPIM) :: NAERCLD
LOGICAL :: LAERLIQAUTOLSP
LOGICAL :: LAERLIQAUTOCP
LOGICAL :: LAERLIQAUTOCPB
LOGICAL :: LAERLIQCOLL
LOGICAL :: LAERICESED
LOGICAL :: LAERICEAUTO

! variance arrays
REAL(KIND=JPRL) :: NSHAPEP
REAL(KIND=JPRL) :: NSHAPEQ
INTEGER(KIND=JPIM) :: NBETA
REAL(KIND=JPRL) :: RBETA(0:100)
REAL(KIND=JPRL) :: RBETAP1(0:100)


END TYPE TECLDP

TYPE(TECLDP), ALLOCATABLE :: YRECLDP

CONTAINS

  SUBROUTINE YRECLDP_LOAD_PARAMETERS()
    ! SC2026: All REAL members are now JPRL. LOAD_SCALAR expects JPRB,
    ! so we bridge every real load through a JPRB temp variable.
    REAL(KIND=JPRB) :: ZTMP
    REAL(KIND=JPRB) :: ZTMP_ARR(0:100)
    IF(.NOT.ALLOCATED(YRECLDP)) ALLOCATE(YRECLDP)
    CALL LOAD_SCALAR('YRECLDP_RAMID', ZTMP); YRECLDP%RAMID = ZTMP
    CALL LOAD_SCALAR('YRECLDP_RCLDIFF', ZTMP); YRECLDP%RCLDIFF = ZTMP
    CALL LOAD_SCALAR('YRECLDP_RCLDIFF_CONVI', ZTMP); YRECLDP%RCLDIFF_CONVI = ZTMP
    CALL LOAD_SCALAR('YRECLDP_RCLCRIT', ZTMP); YRECLDP%RCLCRIT = ZTMP
    CALL LOAD_SCALAR('YRECLDP_RCLCRIT_SEA', ZTMP); YRECLDP%RCLCRIT_SEA = ZTMP
    CALL LOAD_SCALAR('YRECLDP_RCLCRIT_LAND', ZTMP); YRECLDP%RCLCRIT_LAND = ZTMP
    CALL LOAD_SCALAR('YRECLDP_RKCONV', ZTMP); YRECLDP%RKCONV = ZTMP
    CALL LOAD_SCALAR('YRECLDP_RPRC1', ZTMP); YRECLDP%RPRC1 = ZTMP
    CALL LOAD_SCALAR('YRECLDP_RPRC2', ZTMP); YRECLDP%RPRC2 = ZTMP
    CALL LOAD_SCALAR('YRECLDP_RCLDMAX', ZTMP); YRECLDP%RCLDMAX = ZTMP
    CALL LOAD_SCALAR('YRECLDP_RPECONS', ZTMP); YRECLDP%RPECONS = ZTMP
    CALL LOAD_SCALAR('YRECLDP_RVRFACTOR', ZTMP); YRECLDP%RVRFACTOR = ZTMP
    CALL LOAD_SCALAR('YRECLDP_RPRECRHMAX', ZTMP); YRECLDP%RPRECRHMAX = ZTMP
    CALL LOAD_SCALAR('YRECLDP_RTAUMEL', ZTMP); YRECLDP%RTAUMEL = ZTMP
    CALL LOAD_SCALAR('YRECLDP_RAMIN', ZTMP); YRECLDP%RAMIN = ZTMP
    CALL LOAD_SCALAR('YRECLDP_RLMIN', ZTMP); YRECLDP%RLMIN = ZTMP
    CALL LOAD_SCALAR('YRECLDP_RKOOPTAU', ZTMP); YRECLDP%RKOOPTAU = ZTMP
    CALL LOAD_SCALAR('YRECLDP_RCLDTOPP', ZTMP); YRECLDP%RCLDTOPP = ZTMP
    CALL LOAD_SCALAR('YRECLDP_RLCRITSNOW', ZTMP); YRECLDP%RLCRITSNOW = ZTMP
    CALL LOAD_SCALAR('YRECLDP_RSNOWLIN1', ZTMP); YRECLDP%RSNOWLIN1 = ZTMP
    CALL LOAD_SCALAR('YRECLDP_RSNOWLIN2', ZTMP); YRECLDP%RSNOWLIN2 = ZTMP
    CALL LOAD_SCALAR('YRECLDP_RICEHI1', ZTMP); YRECLDP%RICEHI1 = ZTMP
    CALL LOAD_SCALAR('YRECLDP_RICEHI2', ZTMP); YRECLDP%RICEHI2 = ZTMP
    CALL LOAD_SCALAR('YRECLDP_RICEINIT', ZTMP); YRECLDP%RICEINIT = ZTMP
    CALL LOAD_SCALAR('YRECLDP_RVICE', ZTMP); YRECLDP%RVICE = ZTMP
    CALL LOAD_SCALAR('YRECLDP_RVRAIN', ZTMP); YRECLDP%RVRAIN = ZTMP
    CALL LOAD_SCALAR('YRECLDP_RVSNOW', ZTMP); YRECLDP%RVSNOW = ZTMP
    CALL LOAD_SCALAR('YRECLDP_RTHOMO', ZTMP); YRECLDP%RTHOMO = ZTMP
    CALL LOAD_SCALAR('YRECLDP_RCOVPMIN', ZTMP); YRECLDP%RCOVPMIN = ZTMP
    CALL LOAD_SCALAR('YRECLDP_RCCN', ZTMP); YRECLDP%RCCN = ZTMP
    CALL LOAD_SCALAR('YRECLDP_RNICE', ZTMP); YRECLDP%RNICE = ZTMP
    CALL LOAD_SCALAR('YRECLDP_RCCNOM', ZTMP); YRECLDP%RCCNOM = ZTMP
    CALL LOAD_SCALAR('YRECLDP_RCCNSS', ZTMP); YRECLDP%RCCNSS = ZTMP
    CALL LOAD_SCALAR('YRECLDP_RCCNSU', ZTMP); YRECLDP%RCCNSU = ZTMP
    CALL LOAD_SCALAR('YRECLDP_RCLDTOPCF', ZTMP); YRECLDP%RCLDTOPCF = ZTMP
    CALL LOAD_SCALAR('YRECLDP_RDEPLIQREFRATE', ZTMP); YRECLDP%RDEPLIQREFRATE = ZTMP
    CALL LOAD_SCALAR('YRECLDP_RDEPLIQREFDEPTH', ZTMP); YRECLDP%RDEPLIQREFDEPTH = ZTMP
    CALL LOAD_SCALAR('YRECLDP_RCL_KKAac', ZTMP); YRECLDP%RCL_KKAac = ZTMP
    CALL LOAD_SCALAR('YRECLDP_RCL_KKBac', ZTMP); YRECLDP%RCL_KKBac = ZTMP
    CALL LOAD_SCALAR('YRECLDP_RCL_KKAau', ZTMP); YRECLDP%RCL_KKAau = ZTMP
    CALL LOAD_SCALAR('YRECLDP_RCL_KKBauq', ZTMP); YRECLDP%RCL_KKBauq = ZTMP
    CALL LOAD_SCALAR('YRECLDP_RCL_KKBaun', ZTMP); YRECLDP%RCL_KKBaun = ZTMP
    CALL LOAD_SCALAR('YRECLDP_RCL_KK_cloud_num_sea', ZTMP); YRECLDP%RCL_KK_cloud_num_sea = ZTMP
    CALL LOAD_SCALAR('YRECLDP_RCL_KK_cloud_num_land', ZTMP); YRECLDP%RCL_KK_cloud_num_land = ZTMP
    CALL LOAD_SCALAR('YRECLDP_RCL_AI', ZTMP); YRECLDP%RCL_AI = ZTMP
    CALL LOAD_SCALAR('YRECLDP_RCL_BI', ZTMP); YRECLDP%RCL_BI = ZTMP
    CALL LOAD_SCALAR('YRECLDP_RCL_CI', ZTMP); YRECLDP%RCL_CI = ZTMP
    CALL LOAD_SCALAR('YRECLDP_RCL_DI', ZTMP); YRECLDP%RCL_DI = ZTMP
    CALL LOAD_SCALAR('YRECLDP_RCL_X1I', ZTMP); YRECLDP%RCL_X1I = ZTMP
    CALL LOAD_SCALAR('YRECLDP_RCL_X2I', ZTMP); YRECLDP%RCL_X2I = ZTMP
    CALL LOAD_SCALAR('YRECLDP_RCL_X3I', ZTMP); YRECLDP%RCL_X3I = ZTMP
    CALL LOAD_SCALAR('YRECLDP_RCL_X4I', ZTMP); YRECLDP%RCL_X4I = ZTMP
    CALL LOAD_SCALAR('YRECLDP_RCL_CONST1I', ZTMP); YRECLDP%RCL_CONST1I = ZTMP
    CALL LOAD_SCALAR('YRECLDP_RCL_CONST2I', ZTMP); YRECLDP%RCL_CONST2I = ZTMP
    CALL LOAD_SCALAR('YRECLDP_RCL_CONST3I', ZTMP); YRECLDP%RCL_CONST3I = ZTMP
    CALL LOAD_SCALAR('YRECLDP_RCL_CONST4I', ZTMP); YRECLDP%RCL_CONST4I = ZTMP
    CALL LOAD_SCALAR('YRECLDP_RCL_CONST5I', ZTMP); YRECLDP%RCL_CONST5I = ZTMP
    CALL LOAD_SCALAR('YRECLDP_RCL_CONST6I', ZTMP); YRECLDP%RCL_CONST6I = ZTMP
    CALL LOAD_SCALAR('YRECLDP_RCL_APB1', ZTMP); YRECLDP%RCL_APB1 = ZTMP
    CALL LOAD_SCALAR('YRECLDP_RCL_APB2', ZTMP); YRECLDP%RCL_APB2 = ZTMP
    CALL LOAD_SCALAR('YRECLDP_RCL_APB3', ZTMP); YRECLDP%RCL_APB3 = ZTMP
    CALL LOAD_SCALAR('YRECLDP_RCL_AS', ZTMP); YRECLDP%RCL_AS = ZTMP
    CALL LOAD_SCALAR('YRECLDP_RCL_BS', ZTMP); YRECLDP%RCL_BS = ZTMP
    CALL LOAD_SCALAR('YRECLDP_RCL_CS', ZTMP); YRECLDP%RCL_CS = ZTMP
    CALL LOAD_SCALAR('YRECLDP_RCL_DS', ZTMP); YRECLDP%RCL_DS = ZTMP
    CALL LOAD_SCALAR('YRECLDP_RCL_X1S', ZTMP); YRECLDP%RCL_X1S = ZTMP
    CALL LOAD_SCALAR('YRECLDP_RCL_X2S', ZTMP); YRECLDP%RCL_X2S = ZTMP
    CALL LOAD_SCALAR('YRECLDP_RCL_X3S', ZTMP); YRECLDP%RCL_X3S = ZTMP
    CALL LOAD_SCALAR('YRECLDP_RCL_X4S', ZTMP); YRECLDP%RCL_X4S = ZTMP
    CALL LOAD_SCALAR('YRECLDP_RCL_CONST1S', ZTMP); YRECLDP%RCL_CONST1S = ZTMP
    CALL LOAD_SCALAR('YRECLDP_RCL_CONST2S', ZTMP); YRECLDP%RCL_CONST2S = ZTMP
    CALL LOAD_SCALAR('YRECLDP_RCL_CONST3S', ZTMP); YRECLDP%RCL_CONST3S = ZTMP
    CALL LOAD_SCALAR('YRECLDP_RCL_CONST4S', ZTMP); YRECLDP%RCL_CONST4S = ZTMP
    CALL LOAD_SCALAR('YRECLDP_RCL_CONST5S', ZTMP); YRECLDP%RCL_CONST5S = ZTMP
    CALL LOAD_SCALAR('YRECLDP_RCL_CONST6S', ZTMP); YRECLDP%RCL_CONST6S = ZTMP
    CALL LOAD_SCALAR('YRECLDP_RCL_CONST7S', ZTMP); YRECLDP%RCL_CONST7S = ZTMP
    CALL LOAD_SCALAR('YRECLDP_RCL_CONST8S', ZTMP); YRECLDP%RCL_CONST8S = ZTMP
    CALL LOAD_SCALAR('YRECLDP_RDENSWAT', ZTMP); YRECLDP%RDENSWAT = ZTMP
    CALL LOAD_SCALAR('YRECLDP_RDENSREF', ZTMP); YRECLDP%RDENSREF = ZTMP
    CALL LOAD_SCALAR('YRECLDP_RCL_AR', ZTMP); YRECLDP%RCL_AR = ZTMP
    CALL LOAD_SCALAR('YRECLDP_RCL_BR', ZTMP); YRECLDP%RCL_BR = ZTMP
    CALL LOAD_SCALAR('YRECLDP_RCL_CR', ZTMP); YRECLDP%RCL_CR = ZTMP
    CALL LOAD_SCALAR('YRECLDP_RCL_DR', ZTMP); YRECLDP%RCL_DR = ZTMP
    CALL LOAD_SCALAR('YRECLDP_RCL_X1R', ZTMP); YRECLDP%RCL_X1R = ZTMP
    CALL LOAD_SCALAR('YRECLDP_RCL_X2R', ZTMP); YRECLDP%RCL_X2R = ZTMP
    CALL LOAD_SCALAR('YRECLDP_RCL_X4R', ZTMP); YRECLDP%RCL_X4R = ZTMP
    CALL LOAD_SCALAR('YRECLDP_RCL_KA273', ZTMP); YRECLDP%RCL_KA273 = ZTMP
    CALL LOAD_SCALAR('YRECLDP_RCL_CDENOM1', ZTMP); YRECLDP%RCL_CDENOM1 = ZTMP
    CALL LOAD_SCALAR('YRECLDP_RCL_CDENOM2', ZTMP); YRECLDP%RCL_CDENOM2 = ZTMP
    CALL LOAD_SCALAR('YRECLDP_RCL_CDENOM3', ZTMP); YRECLDP%RCL_CDENOM3 = ZTMP
    CALL LOAD_SCALAR('YRECLDP_RCL_SCHMIDT', ZTMP); YRECLDP%RCL_SCHMIDT = ZTMP
    CALL LOAD_SCALAR('YRECLDP_RCL_DYNVISC', ZTMP); YRECLDP%RCL_DYNVISC = ZTMP
    CALL LOAD_SCALAR('YRECLDP_RCL_CONST1R', ZTMP); YRECLDP%RCL_CONST1R = ZTMP
    CALL LOAD_SCALAR('YRECLDP_RCL_CONST2R', ZTMP); YRECLDP%RCL_CONST2R = ZTMP
    CALL LOAD_SCALAR('YRECLDP_RCL_CONST3R', ZTMP); YRECLDP%RCL_CONST3R = ZTMP
    CALL LOAD_SCALAR('YRECLDP_RCL_CONST4R', ZTMP); YRECLDP%RCL_CONST4R = ZTMP
    CALL LOAD_SCALAR('YRECLDP_RCL_FAC1', ZTMP); YRECLDP%RCL_FAC1 = ZTMP
    CALL LOAD_SCALAR('YRECLDP_RCL_FAC2', ZTMP); YRECLDP%RCL_FAC2 = ZTMP
    CALL LOAD_SCALAR('YRECLDP_RCL_CONST5R', ZTMP); YRECLDP%RCL_CONST5R = ZTMP
    CALL LOAD_SCALAR('YRECLDP_RCL_CONST6R', ZTMP); YRECLDP%RCL_CONST6R = ZTMP
    CALL LOAD_SCALAR('YRECLDP_RCL_FZRAB', ZTMP); YRECLDP%RCL_FZRAB = ZTMP
    CALL LOAD_SCALAR('YRECLDP_RCL_FZRBB', ZTMP); YRECLDP%RCL_FZRBB = ZTMP
    CALL LOAD_SCALAR('YRECLDP_LCLDEXTRA', YRECLDP%LCLDEXTRA)
    CALL LOAD_SCALAR('YRECLDP_LCLDBUDGET', YRECLDP%LCLDBUDGET)
    CALL LOAD_SCALAR('YRECLDP_NSSOPT', YRECLDP%NSSOPT)
    CALL LOAD_SCALAR('YRECLDP_NCLDTOP', YRECLDP%NCLDTOP)
    CALL LOAD_SCALAR('YRECLDP_NAECLBC', YRECLDP%NAECLBC)
    CALL LOAD_SCALAR('YRECLDP_NAECLDU', YRECLDP%NAECLDU)
    CALL LOAD_SCALAR('YRECLDP_NAECLOM', YRECLDP%NAECLOM)
    CALL LOAD_SCALAR('YRECLDP_NAECLSS', YRECLDP%NAECLSS)
    CALL LOAD_SCALAR('YRECLDP_NAECLSU', YRECLDP%NAECLSU)
    CALL LOAD_SCALAR('YRECLDP_NCLDDIAG', YRECLDP%NCLDDIAG)
    CALL LOAD_SCALAR('YRECLDP_NAERCLD', YRECLDP%NAERCLD)
    CALL LOAD_SCALAR('YRECLDP_LAERLIQAUTOLSP', YRECLDP%LAERLIQAUTOLSP)
    CALL LOAD_SCALAR('YRECLDP_LAERLIQAUTOCP', YRECLDP%LAERLIQAUTOCP)
    CALL LOAD_SCALAR('YRECLDP_LAERLIQAUTOCPB', YRECLDP%LAERLIQAUTOCPB)
    CALL LOAD_SCALAR('YRECLDP_LAERLIQCOLL', YRECLDP%LAERLIQCOLL)
    CALL LOAD_SCALAR('YRECLDP_LAERICESED', YRECLDP%LAERICESED)
    CALL LOAD_SCALAR('YRECLDP_LAERICEAUTO', YRECLDP%LAERICEAUTO)
    CALL LOAD_SCALAR('YRECLDP_NSHAPEP', ZTMP); YRECLDP%NSHAPEP = ZTMP
    CALL LOAD_SCALAR('YRECLDP_NSHAPEQ', ZTMP); YRECLDP%NSHAPEQ = ZTMP
    CALL LOAD_SCALAR('YRECLDP_NBETA', YRECLDP%NBETA)
    ! The last two are actually arrays — bridge through JPRB temp array
    CALL LOAD_ARRAY('YRECLDP_RBETA', 1, 101, 101, 101, ZTMP_ARR(0:100))
    YRECLDP%RBETA(0:100) = ZTMP_ARR(0:100)
    CALL LOAD_ARRAY('YRECLDP_RBETAP1', 1, 101, 101, 101, ZTMP_ARR(0:100))
    YRECLDP%RBETAP1(0:100) = ZTMP_ARR(0:100)
  END SUBROUTINE YRECLDP_LOAD_PARAMETERS

END MODULE YOECLDP
